### ISSUE TITLE
custom Cipher selection is needed for a stronger encryption

### ISSUE THREAD

**Issue by merinfor2021** [calamares/calamares#1917] opened 2022-04-09 19:40 UTC
I would like to bump this 2-years-old feature request: https://github.com/calamares/calamares/issues/1452 . Please add to Calamares UI the options for cipher selection, so that a user could choose i.e.
> --type luks1 --cipher serpent-xts-plain64 --key-size 512 --hash whirlpool --iter-time 10000 --use-random --verify-passphrase luksFormat

**Comment by demmm** [comment] 2022-04-10 11:00
Please keep the conversation in the bug report linked, opening duplicates with no new info, but just a link is not helpful.
Duplicate of https://github.com/calamares/calamares/issues/1452

**Closed by demmm** 2022-04-10 11:00 UTC
Labels: M duplicate
