### ISSUE TITLE
runtime regression: users created with no session

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#964] opened 2018-05-22 14:14 UTC
#### Submission type

  - [x] Bug report
  - [x] Feature Request

on master f2677b08791ec7dbed8ab4e787610410b8b40f0a changed the way useradd is called.

this causes major issues

1. no shell is set in `/etc/passwd` on ubuntu 16.04 which seems generally wrong (bug in useradd?)
1. this changes behavior and as such should arguably be opt-in so as to remain backwards compatible. in fact, I am particularly annoyed because it regressed all my autotests and I had to go dig through all possible offenders to even find out that cala changed the behavior
1. there is a conflict between generic useradd settings and when cala is used on a desktop system. e.g. on ubuntu `/etc/default/useradd` sets sh, because it is the most available on all the different permutations of ubuntu, that doesn't mean that it is the best choice for most if any of them. In fact on a desktop system using sh instead of bash/zsh/whatevs is fairly unreasonable. To that end cala needs to have a setting in the module config to force a given shell regardless of what the useradd config says.

As a solution for 2 and 3 at the same time I'd propose a module config to set a shell, which can be a path to the shell or 'default' to defer the choice to useradd.

```
defaultShell: /bin/bash
```

If the config key isn't set at all simply go for bash for backwards compatibility (until cala 4.x?)

**Comment by philmmanjaro** [comment] 2018-05-22 17:40
@fhdk: do we see any regression by your commit within Manjaro?

**Comment by blackcrack** [comment] 2018-05-22 17:54
where do you see to be Manjaro involved, why do you ever spamming with manjaro, there is the theme Ubuntu !

**Comment by philmmanjaro** [comment] 2018-05-22 18:00
@blackcrack: what is the problem here? A Manjaro Developer had changed it and I just want to double-check if it might had also created a regression on our end.

**Comment by adriaandegroot** [comment] 2018-05-22 18:18
@philmmanjaro OK, so that was the reason to drop `-s /bin/bash` .. which then breaks (as @abucodonosor warned me about) when no proper useradd configuration is there. I'm introducing a config key (e.g. solution 3), and probably also doing some prep-work for pulling the shell from globalStorage, so that some future UI that lets you pick the user shell (there's a feature-issue filed for that, even though I don't like the idea).

So this should be fixed tomorrow some time, and then end up in 3.2.1

**Comment by blackcrack** [comment] 2018-05-22 18:29
@agaida 
>Schulferien? Oder keine Hausaufgaben ...
 ich hab in den bbs'es meine Hausaufgaben gemacht, du solltest mal checken wo du stehst, wenn du meinst andere aufheizen zu können.. und auserdem iss das 1. offtopic , 2. gehst Du Leute persöhnlich an..

**Comment by abucodonosor** [comment] 2018-05-22 18:56
@blackcrack 

is me 'crazy' , can you please stop all this ? 

well the commit causing that was done from Mnajaro devels but that does not *matter*.

@philmmanjaro 

Timisoara ( RO ) ?:)

@adriaandegroot 

Why don't we rip out the shell code from PR #280 and make everyone happy ?
There is a configuration and UIX settings .. so Users and Distros should be happy with these.

**Comment by kkofler** [comment] 2018-05-22 22:22
Can we please focus on the facts and stop the technical attacks? Otherwise, I will have to hit that "Delete" button a couple times.

And please stick to English. Nicht jeder hier spricht Deutsch. Thanks in advance!

**Comment by fhdk** [comment] 2018-05-23 08:07
@philmmanjaro 
No regression - in fact I get the chosen shell after installation.

So having the correct `useradd` file is setting the shell as expected.

**Closed** 2018-05-23 11:33 UTC

**Comment by adriaandegroot** [comment] 2018-05-28 10:45
The problem is that "correct `useradd` file" is an unwarranted assumption. The configuration has been expanded, and for 3.2.1 Calamares can be configured to swing all the different ways.
