### ISSUE TITLE
Run it on debian Linux livecd but it wasn‘t take work

### ISSUE THREAD

**Issue by Zhouseeie** [calamares/calamares#1732] opened 2021-06-25 02:02 UTC
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
I can't install my livecd although it finish squashfs
命令/usr/sbin/bootloader-config以退出代码100 
完成输出：Running bootloader-config... * install grub... (bios) Reading package lists... E: Unable to mkstemp /tmp/clearsigned.message.u81QKr GetTempFile (2: No such file or directory) E: The package lists or status file could not be parsed or opened.
x86_64 bit
Bios
all disk is wipe

**To Reproduce**
1. install packages （calamares* SlaxLinux script rsync）
2. build livecd
3. enter Calamares

**Expected behavior**
follow the installer step

**Screenshots and Logs**

emmm computer can‘t surf to github because of GFW
Here some details：
命令/usr/sbin/bootloader-config以退出代码100 
完成输出：Running bootloader-config... * install grub... (bios) Reading package lists... E: Unable to mkstemp /tmp/clearsigned.message.u81QKr GetTempFile (2: No such file or directory) E: The package lists or status file could not be parsed or opened.
![E35ACDD6-8670-4E48-9D32-63F8482B4CD0](https://user-images.githubusercontent.com/72480930/123357187-b3e97200-d59b-11eb-954a-82214710da69.png)

**Additional context**
Please solve it in time

**Comment by demmm** [comment] 2021-06-25 09:48
Is this related to https://github.com/calamares/calamares/pull/1733?

**Comment by Zhousy233** [comment] 2021-06-25 09:50
> Is this related to #1733?

may be

**Comment by CC2130** [comment] 2021-06-26 04:32
#1733 make it can run well in aarch64 machine

If I were you, I'd chroot to the chroot env, run /usr/sbin/bootloader-config manually

**Comment by adriaandegroot** [comment] 2021-06-29 09:11
Sorry, I can't see clearly what the problem is. The bootloader-config program (which isn't part of Calamares) is running and failing in the target system, with a not-very-useful error message. That isn't something that we can debug from here. @CC2130 has a good suggestion: after the installation fails, look into the target system yourself. My best guess is that `/tmp` does not exist or is not writable on the target system -- that might be a problem with the squashfs that you have used.

**Comment by adriaandegroot** [comment] 2021-07-12 14:27
Closing as "downstream issue". We don't have useful debugging information here.

**Closed by adriaandegroot** 2021-07-12 14:27 UTC
