### ISSUE TITLE
Calamares fails to correctly install GRUB

### ISSUE THREAD

**Issue by rancelec** [calamares/calamares#2340] opened 2024-06-01 14:22 UTC
Hi,
I tried calamares on installing on a VM EndeavourOS and Calam-Arch-Installer, the latest versions.
In both case the installation finish without problem but, at the restart the VM present a blinking cursor on a black screen... like there is not system to boot.
This is partition scheme on VM:
partition table = MBR
23 GB ext4 root
2 GB swap

In the end of installation in the VM, just before reboot, I gave terminal command

cat /home/liveuser/endeavour-install.log | eos-sendlog

and this is result

[https://0x0.st/XNlw.txt](url)

**Comment by dalto8** [comment] 2024-06-01 14:28
This is a duplicate of #2318

**Closed by dalto8** 2024-06-01 14:28 UTC
