### ISSUE TITLE
erase disk not offered when a swap is mounted

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1165] opened 2019-06-03 14:12 UTC
**Describe the bug**
When a disk already contains a swap partition, chances are it will get auto mounted. When a swap is mounted the partitioning no longer offers an Erase Disk option. 

**To Reproduce**
1. install a system with auto partitioning
2. reboot back to installer
3. `swapon -s` likely has the disk's swap as used now
4. start cala again
5. observe that the partitioning step no longer offers an erase option
6. unswap everything `swapoff -v -a`
7. restart cala and observe it offering the erase option again

**Expected behavior**
Erase option should be available regardless of used swap, in fact, regardless of any currently mounted partitions even IMHO.

**Comment by abucodonosor** [comment] 2019-06-03 14:41
Well, you can't erase the disc when you have mounted partitions.

Debug on cli should tell you that this disc is excluded from erasing.

**Comment by wxl** [comment] 2019-06-03 17:01
#860 is relevant here.

**Comment by kkofler** [comment] 2019-06-03 22:23
Known issue, see https://github.com/calamares/calamares/issues/1112#issuecomment-490482080

**Comment by abucodonosor** [comment] 2020-02-16 17:25
Duplicate of #860

**Closed by abucodonosor** 2020-02-16 17:25 UTC
Labels: M duplicate, bug
