### ISSUE TITLE
Please display partition name/label while partitioning

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#540] opened 2016-09-11 10:29 UTC
Jira issue originally created by user riinav:

Please display partition label while partitionling.
It's difficult to visualize without labels, as to which partition am I manipulating.

Without label we have to open gparted to see the partition name and label.
While using Thus, it's much more easier to partition as it displays label.

For new and first time users it's really important for them to display this info as they are often scared to manipulate partitions and install linux. Often times we loose such consumers

**Comment by abucodonosor** [comment] 2017-09-09 13:27
seems like a dupe of #449

**Closed** 2022-04-25 14:08 UTC
Labels: feature: improvement, help: wanted
