### ISSUE TITLE
Segmentation fault partition module

### ISSUE THREAD

**Issue by AlmAck** [calamares/calamares#685] opened 2017-02-24 22:29 UTC
Launching Calamares (3.0.91) without an internet connection it launches fine and gives that warning box that some features might be disabled.
If you then exit, connect to internet and then launch Calamares again, it crashes.
One has to reboot, connect to the internet first and then launch Calamares for it to work properly.
This is the gdb output when running Calamares after connecting to the internet>

```
[New Thread 0x7fffc2d4a700 (LWP 2414)]
[New Thread 0x7fffc2549700 (LWP 2415)]
Backtrace has 12 calls on stack:
  12: /usr/lib/libparted.so.2(ped_assert+0x44) [0x7fffe10ce8f4]
  11: /usr/lib/libparted.so.2(ped_device_open+0x5c) [0x7fffe10ced6c]
  10: /usr/lib/libparted.so.2(ped_disk_new+0x17) [0x7fffe10d3817]
  9: /usr/lib/qt5/plugins/libpmlibpartedbackendplugin.so(+0x7b6b) [0x7fffd2a8db6b]
  8: /usr/lib/qt5/plugins/libpmlibpartedbackendplugin.so(+0x85ad) [0x7fffd2a8e5ad]
  7: /usr/lib/calamares/modules/partition/libcalamares_viewmodule_partition.so(_ZN19PartitionCoreModule6doInitEv+0x49) [0x7fffd9ab9c49]
  6: /usr/lib/calamares/modules/partition/libcalamares_viewmodule_partition.so(_ZN19PartitionCoreModule4initEv+0x33) [0x7fffd9abb213]
  5: /usr/lib/calamares/modules/partition/libcalamares_viewmodule_partition.so(_ZN12QtConcurrent15RunFunctionTaskIvE3runEv+0x75) [0x7fffd9abb8c5]
  4: /usr/lib/libQt5Core.so.5(+0xab2c3) [0x7ffff69322c3]
  3: /usr/lib/libQt5Core.so.5(+0xaef78) [0x7ffff6935f78]
  2: /usr/lib/libpthread.so.0(+0x7444) [0x7ffff4ca2444]
  1: /usr/lib/libc.so.6(clone+0x5f) [0x7ffff60381af]

Thread 5 "Thread (pooled)" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffd286d700 (LWP 2324)]
0x00007ffff5f83114 in raise () from /usr/lib/libc.so.6
```

**Comment by shadeslayer** [comment] 2017-03-15 14:30
Hi
Could you try the following things :
* Update to Calamares 3.1.0
* Install the debugging symbols for parted, partitionmanager and calamares
* Try and reproduce the crash
* Paste the full backtrace here

**Comment by shadeslayer** [comment] 2017-03-17 11:34
This the same as #686. Closing this one as a dupe.

**Closed by shadeslayer** 2017-03-17 11:34 UTC
