### ISSUE TITLE
plasmalnf settings not being saved

### ISSUE THREAD

**Issue by jghodd** [calamares/calamares#1646] opened 2021-02-26 02:45 UTC
Sorry to bring up plasmalnf again, and this is probably more plasmalnf-adjacent, and probably not even your issue, but I wanted to pass it by you anyway.

Your new plasmalnf code appears to be working and the chosen look-and-feel comes up on the desktop as expected on first login. However, the plasma-org.kde.plasma.desktop-appletsrc file's ItemGeometriesHorizontal setting is not getting set, so after logging out, then logging back in, the entire look-and-feel is scrambled - ItemGeometriesHorizontal stores the applet positions. The only way I've found around this is to make any minor adjustment to any applet on the desktop which causes plasma to write out the ItemGeometriesHorizontal value. Normally, just logging out would cause a complete update of plasma-org.kde.plasma.desktop-appletsrc, so this is a new (broken) behaviour.

Again, I understand this may not be your issue - it's probably the kde/plasma group's problem - but getting any response from them on a bug report either takes quite a while or you never hear from them at all. On the other hand, because folks are going to experience this after performing an installation using calamares, this may end up being dropped on you repeatedly anyway (so, heads-up!).

Is there any chance you might know how to force plasma to write out its entire configuration? Perhaps a qdbus command...? Javascript? Qml? I've being digging around the internet trying to find some solution to this, but the documentation is so limited and this issue appears to be a new one. So, no answers so far.

**Comment by kkofler** [comment] 2021-02-26 02:58
The only way would be for Calamares to directly write the desired setting to the appletsrc, but the issue is, how are we supposed to compute the geometries?

Using qdbus is not going to work inside the chroot with no Plasma running within the chroot. It would only talk to the Plasma on the live image, so at most it could get it to write the settings to the throwaway live overlay in RAM, not to the installed system.

**Comment by jghodd** [comment] 2021-02-26 04:18
My thought was to add an a firstRun script of some sort, if I knew what to run to force plasma to update appletsrc. Previous versions or plasma only required a logout for this happen. Now logout does nothing to update ItemGeometriesHorizontal, only making a minor adjustment - resize or move - to an applet causes the update. Everything else from the layout-template is correctly set in the appletsrc file, except the ItemGeometriesHorizontal property. So, after successfully completing a calamares installation using the plasmalnf module, the initial login to the installed system comes up correctly, drawing from the look-and-feel layout, as expected. But ItemGeometriesHorizontal is not set in appletsrc and logging out and logging back in again is no longer forcing plasma to update this property, so the second login presents the user with a scrambled desktop. If the user were to carefully select and move the applets back into their original positions (and sizes), plasma correctly sets ItemGeometriesHorizontal. I realise that this is a kde/plasma bug, probably in plasma-desktop, but I could use a workaround really badly at the moment, given that the kde/plasma devs take a long time to respond to bug reports, if at all. Also, you need this brought to your attention, because this will likely come back on you. I know from prior interactions with Adriaan - particularly when I reported a problem with lookandfeeltool - that y'all can get to the devs at kde/plasma faster than ordinary users can. This unquestionably a kde/plasma bug, which I'd be happy to report, but I could use a workaround, or, if you can contact the kde/plasma devs, a patch that fixes this.

**Comment by jghodd** [comment] 2021-02-27 03:50
Just to provide some followup. There is an update script called move_desktop_layout_config.js under /usr/share/plasma/shells/org.kde.plasma.desktop that runs the following:

`var allDesktops = desktops();

for (var i = 0; i < allDesktops.length; ++i) {
    var desktop = allDesktops[i];
    desktop.currentConfigGroup = ["General"];
    var serializedItems = desktop.readConfig("ItemsGeometries");
    desktop.currentConfigGroup = [];
    desktop.writeConfig("ItemGeometriesHorizontal", serializedItems);
    desktop.reloadConfig()
}`

This is part of the latest issue, because ItemsGeometries does not exist. So, it's reading a non-existent property to get the geometries which returns an empty list. It then writes that empty list to a new property, named ItemGeometriesHorizontal which is used to position the desktop's applets. Thus the scrambled desktop on the second login. I was able to determine that if you remove that update script when building the iso image, ItemGeometriesHorizontal is never created (and still ItemsGeometries does not exist), so it is that script that is attempting to perform something that should be going on in plasma itself.

I'm going to try to find some way to iterate through the desktop's applets and potentially create the ItemGeometriesHorizontal property that way. I don;t know yet how or if this can be done. If it can be done, the javascript can be run on initial login to properly create ItemGeometriesHorizontal. Perhaps something similar to their update script that grabs the geometries of the desktop's applets and builds that serializedItems list.

Again, if you know anything that can help... I'd appreciate any assistance I can get. Plasma javascripting is poorly documented.

**Comment by jghodd** [comment] 2021-02-27 18:57
Again, keeping you in the loop...

```
var allDesktops = desktops();

for (var i = 0; i < allDesktops.length; ++i) {
    var desktop = allDesktops[i];
    var allWidgets = desktop.widgets();
    var geomString = "";
    
    for (var j = 0; j < allWidgets.length; ++j) {
        var widget = allWidgets[j];
        var widgetGeom = widget.geometry;
        
        geomString = geomString + "Applet-" + widget.id + ":" + widgetGeom.x + "," +
            widgetGeom.y + "," + widgetGeom.width + "," + widgetGeom.height + ",0;";
    }
    
    desktop.currentConfigGroup = ["General"];
    desktop.writeConfig("ItemsGeometries", geomString);
}
```
Named it create_items_geometries.js and dropped it into the desktop shell's updates directory. The updates are run alphabetically, so it will create ItemsGeometries before move_desktop_layout_config.js is run which moves ItemsGeometries to ItemGeometriesHorizontal. I'm doing a build on my distro now to test it out. I did notice that the geometry of many of the widgets, but not all of them, are out by 5 pixels for x and y, and 10 pixels for width and height - I'm not sure why...

**Comment by jghodd** [comment] 2021-03-01 04:29
Last version of the javascript update:

```
var allDesktops = desktops();

for (var i = 0; i < allDesktops.length; ++i) {
    var desktop = allDesktops[i];
    var allWidgets = desktop.widgets();
    var serializedItems = "";
    
    desktop.currentConfigGroup = ["General"];
    serializedItems = desktop.readConfig("ItemsGeometries");

    if (serializedItems == "") {
        desktop.currentConfigGroup = [];
        serializedItems = desktop.readConfig("ItemGeometriesHorizontal");

        if (serializedItems == "") {
            for (var j = 0; j < allWidgets.length; ++j) {
                var widget = allWidgets[j];
                var widgetGeom = widget.geometry;
        
                serializedItems = serializedItems + "Applet-" + widget.id + ":" + widgetGeom.x + "," +
                    widgetGeom.y + "," + widgetGeom.width + "," + widgetGeom.height + "," + i + ";";
            }
        }
    }
    
    desktop.currentConfigGroup = [];
    desktop.writeConfig("ItemGeometriesHorizontal", serializedItems);
    desktop.reloadConfig()
}
```

Named verify_geometries.js so that it runs last and installed into /usr/share/plasma/shells/org.kde.plasma.desktop/contents/updates.

After a number of test builds and installations, this script appears to be solid and works every time. It is a workaround, and I can now go ahead and open a ticket with kde/plasma. Feel free to offer it to any distro builders running into the same issue.

**Comment by jghodd** [comment] 2021-03-01 17:17
KDE/Plasma bug report 433799:

https://bugs.kde.org/show_bug.cgi?id=433799

**Comment by notmart** [comment] 2021-03-18 11:03
A possible fix for it is 
https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/696

**Comment by adriaandegroot** [comment] 2021-11-16 10:41
Since this was closed in KDE Plasma, I'm going to close the Calamares issue and assume that the plasmalnf tool does the right thing now.

**Closed by adriaandegroot** 2021-11-16 10:41 UTC
