### ISSUE TITLE
calamares has root password field even though setRootPassword:false

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1477] opened 2020-08-04 10:20 UTC
**Describe the bug**
In calamares calamares the users page has root password input fields despite setRootPassword:false being set in the users.conf

**To Reproduce**
1. https://files.kde.org/neon/images/focal-preview/unstable/
2. start calamares
3. go to users page
4. see root inputs

**Expected behavior**
No rooty options

**Screenshots and Logs**
[cala.log](https://github.com/calamares/calamares/files/5021531/cala.log)
![Screenshot_20200804_121748](https://user-images.githubusercontent.com/809987/89283025-bc1b8480-d64c-11ea-95ed-28024cf1b98a.png)

**Comment by demmm** [comment] 2020-08-04 10:39
Duplicate of https://github.com/calamares/calamares/issues/1469

**Closed** 2020-08-07 09:31 UTC
Labels: M duplicate
