### ISSUE TITLE
emprove accessibility

### ISSUE THREAD

**Issue by mhussaincov** [calamares/calamares#1076] opened 2019-02-01 08:45 UTC
hi there,
please could the accessibility be emproved with the installer?
when ran with orca the screen reader, it is completely in accessible.
this places a barrier on installing linux distributions that use your installer to install there opperateing systems.
I would be grateful if this was looked in too.
Majid

**Comment by abucodonosor** [comment] 2019-02-02 14:12
Please see

https://github.com/calamares/calamares/issues/470
https://github.com/calamares/calamares/issues/523

**Comment by adriaandegroot** [comment] 2019-02-06 08:58
Closing this one as a duplicate of #523 .. the Qt fix has never landed and looks like it no longer applies to current Qt versions. That means that only a wholesale Calamares-without-root will do the job (which would also sove some other things, like Wayland and WebEngine problems). That is a lengthy process, though.

**Closed by adriaandegroot** 2019-02-06 08:58 UTC
