### ISSUE TITLE
Calamares won't detect installed kernel unless packages are reinstalled

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#903] opened 2018-02-04 22:17 UTC
#### Info regarding which version of Calamares is used, which Distribution

Lubuntu Bionic Daily, using Calamares 3.1.12. The config that's used is located at https://github.com/lubuntu-team/calamares-settings-ubuntu/tree/master/lubuntu

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

Just using the standard install, with the config provided.

#### What do you expect to have happen when Calamares installs?

Calamares should install the system in a way that rebooting will boot into the newly installed system.

#### Describe the issue you encountered

On reboot, memtest86+ is the only option. After further investigation, it seems that grub-update won't detect the newly installed system. The only thing that will work is completely removing all of the kernel packages and reinstalling them.

#### Steps to reproduce the problem

1. Download [a Lubuntu Bionic ISO](http://cdimage.ubuntu.com/lubuntu/daily-live/pending/bionic-desktop-amd64.iso) and install Calamares using `sudo apt install calamares`.
1. Deploy Lubuntu's settings to /etc/calamares/ from https://github.com/lubuntu-team/calamares-settings-ubuntu/tree/master/lubuntu and revert commit `a2a9b6ac9c601810a59965ee58a16714e907723e`.
1. Run Calamares as normal, and reboot.

**Comment by abucodonosor** [comment] 2018-02-04 22:40
Not a Calamares issue .. please fix your packages and configuration files.

**Comment by abucodonosor** [comment] 2018-02-04 22:40
* AND* your LiveCD ..

**Comment by abucodonosor** [comment] 2018-02-05 03:54
Let me explain you that once again.

1) You are using a LiveISO is not designed for calamres
2) You have broken apt policy's ( figure from ubi installer not our job right ? )
3) you have wrong / missing packages on that ISO
4) Calamares is doing what you are asking for..
    ( ofc it can fix your packages .. this is your job )

Meaning , once you've figure at least 1,2,3 things will work for you.
Ofc to figure these you have to at least read some debian/ubuntu docs.

That said it is not our job to provide you a working ISO for your custom Distribution.

Giving you and example for pacman based Distributions:

1) Provide a configuration/policy file with something like this:
  ...
  HoldPkg = kernel
  IgnorePkg = kernel
 ...
2) tell calamares to install/update the kernel 
3) watch how isn't working
....

See ? PEBKAK ..

**Comment by tsimonq2** [comment] 2018-02-05 03:58
I got it the first time...

**Comment by adriaandegroot** [comment] 2018-02-06 15:38
Reopening this as "not-a-bug, but @abucodonosor, please be polite when closing feature and support requests."

@tsimonq2, you can use the interactive terminal module to get a widget / window part-way through the installation process. That might help you figure out what is in the resulting target system. If your grub-update isn't detecting the installed system (from inside that system), I'd suggest the problem is with the things you have installed (or with grub-update). Does (re)installing the kernel packages run any post-install scripts? If that changes something in the target system, it shows that the image being unsquashed is missing something.

**Comment by abucodonosor** [comment] 2018-02-06 22:27
@adriaandegroot 

This is not a feature nor a bug .. We explained that on IRC NOT only once .. and not only
myself but @agaida etc too.

I wasted my time to debug that 2 times already .. So please don't tell me about
being polite.. This is simple 'whoever' maintais the distro is clueless about 
packaging or about on 'howto' create a working calmares ISO.

However from now on you can handle bug reports yourself .. since I don't
care anymore..

**Comment by adriaandegroot** [comment] 2018-03-06 12:35
Closing this with "downstream needs to sort it out"

**Closed by adriaandegroot** 2018-03-06 12:35 UTC
Labels: not-a-bug

**Comment by apachelogger** [comment] 2018-03-28 12:47
@tsimonq2 https://bazaar.launchpad.net/~kdeneon/livecd-rootfs-neon/bionic/revision/1363 has some additional background on why this happens and how we think this may be solved via a shellprocess.

The motivation behind that live-build behaviour is that one can split the rootfs from the device kernel/config and then have the installer unpack the device specific stuff (which is e.g. handy on ARM devices where kernels are usually per-dervice). It's use for desktop ISOs eludes me a bit, but that's why it is the way it is.
For lubuntu it may either be a good approach to implement a proper shellprocess which copies kernels around (ubiquity's code for that is in install.py IIRC), or to have lubuntu disable the feature in livecd-rootfs.

**Comment by tsimonq2** [comment] 2018-03-28 22:24
> https://bazaar.launchpad.net/~kdeneon/livecd-rootfs-neon/bionic/revision/1363 has some additional background on why this happens and how we think this may be solved via a shellprocess.

Aha. I had a feeling it was livecd-rootfs.

I'll talk with some Core Developers in Ubuntu and see what would be preferred, and I'll report back.
