### ISSUE TITLE
Calamares 3.2.40, Debian testing, Keyboard & Users (Displaymanager) Modules Problems.

### ISSUE THREAD

**Issue by pcrepix** [calamares/calamares#1668] opened 2021-04-01 21:09 UTC
Hi,
I'm getting some issues I didn't experience with earlier versions (or didn't notice).

I have setup Calamares 3.2.40 on Debian Testing & Stable, XFCE4 & Cinnamon Environments. It also uses Lightdm.

Problem 1:

User Module.

I have enabled autologin as default in the conf file, but if you run the the calamares installer, that box isn't checked. It used to be in earlier versions.

If you then enable autologin during the installation, the system still doesn't logon automatically after the installation has finished.
When I look at the config file in /etc/lightdm, the user account for the autologin is starred out and no user inserted.

Problem 2:

Keyboard Module.

In the /etc/default/keyboard the option "XKBMODEL=" doesn't take what has been set during the installation process, for example "kb105", even if the keyboard.conf file was setup with true for that option.

> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

Cheers,
rindi

**Comment by adriaandegroot** [comment] 2021-04-01 21:14
Do you have ISO links for this?

I have seen chat about autologin / checkbox elsewhere today, but I suspect that if you're seeing this there's something *else* that fell over in the DM module. Note that there is no 3.2.40 release yet, so it would be helpful to have the exact git hash you're building.

**Comment by pcrepix** [comment] 2021-04-01 21:26
Here's the Changelog for that release:

https://github.com/calamares/calamares/blob/calamares/CHANGES

The Library files also use 3.2.40

It's just the latest download on Github.

I'd have to upload an iso to somewhere. Not sure where to...

**Comment by pcrepix** [comment] 2021-04-01 21:47
I've uploaded an iso to mega. Not sure if this will work, as I haven't really used this before to share files:

https://mega.nz/file/mUYQHDpJ#x6vKo_MhSTOOSsnISSqnE_axS8Eo6AprGu1ERHDh4aU

https://mega.nz/file/jZRmWZ4L#NXndnzCreIfxY6c5IMypqCUv0hSpizGGkJsMgR3PUHY

**Comment by adriaandegroot** [comment] 2021-04-02 11:05
Looking at your setup:
- I'm not exactly sure what your `Installer-Script` is doing, but if it is doing sed or other text-replacements on the config files, that **really** shouldn't be necessary. You can start Calamares with `-c` and `-X` flags to point it to specific configuration directories.
- yes, autologin is **specifically** messed up,

**Comment by adriaandegroot** [comment] 2021-04-02 11:49
The commit above addresses the configuration issue, not applying-it-to-lightdm.
I can confirm that even with the box ticked, the lightdm configuration does not get autologin set; by editing the lightdm.conf file after installation -- editing it in the way that the *displaymanager* module **should** have edited it -- I do get autologin.

**Comment by adriaandegroot** [comment] 2021-04-02 12:24
The autologin-configuration problem was fixed in 3.2.39.1; while your package is from git, it looks like it is from a slightly older revision before that fix was applied (and merged to the development branch). See 9d4c2bf1c78c1c68cab6ddf86e1fdbd3a9ed28e3 .

Overall, the ISO you have is kind of weird: there are at least two copies of Calamares configurations and modules in it. `/usr/share/MakuluSetup/` has **really** old Calamares modules, and `/usr/local/lib/x86_64-linux-gnu` contains (I think) current Debian packages.

**Comment by adriaandegroot** [comment] 2021-04-02 12:50
XKBMODEL is not written; confirmed. I can see what the problem is, too: if you leave the default (pc105) selected and don't touch the *model* drop-down at all, the model selection remains empty in the internal settings, even if it looks like pc105 in the UI -- and then an empty selection is written. Picking anything else, and then pc105, will write the correct value.

**Comment by pcrepix** [comment] 2021-04-02 13:32
The /usr/share/MakuluSetup was a backup of an older setup and isn't used. The Installer-Script doesn't do any commands, it just provides the User Interface so the user can select which packages-list to install, or to select his preferred repository mirror.

This morning I did see that displaymanager fix, and redownloaded from git built and compiled the new version. About to test it soon. Thanks.

**Closed** 2021-04-02 14:25 UTC

**Comment by adriaandegroot** [comment] 2021-04-02 14:49
(You will probably want the 3.2.39.2 tag, rather than the *calamares* branch, but both branches contain the fixes for this particular issue)

**Comment by pcrepix** [comment] 2021-04-02 14:55
Downloaded and rebuilding right now. Thanks.

**Comment by pcrepix** [comment] 2021-04-02 17:36
Tested and works.
