### ISSUE TITLE
Problems with language on time zone screen

### ISSUE THREAD

**Issue by scootergrisen** [calamares/calamares#714] opened 2017-04-09 02:37 UTC
When i select danish or any other language, on the time zone screen it seems always says:
"The System language will be set to English (UnitedKingdom)."
"The numbers and dates locales will be set to English (UnitedKingdom)."

If i click the Change... buttons it seems a lot of language codes are missing from the lists. For example there are no "da" or "da_DK" even though "Danish" is on the language selection screen.

Tested in OpenMandrivaLx.3.01-PLASMA.x86_64.iso

**Comment by philmmanjaro** [comment] 2017-04-09 09:49
That depends on the distro if they provide the needed locales to choose from. You can check for example with another distro to compare. The latest ISOs of Manjaro can be found [here](https://manjaro.org/get-manjaro/).

**Comment by adriaandegroot** [comment] 2017-06-01 11:24
I'm closing this one as a duplicate of #688 -- the string on the location page isn't updated when you have changed the language on the welcome screen. The second issue named here does seem to be a distro issue.

**Closed by adriaandegroot** 2017-06-01 11:24 UTC
