### ISSUE TITLE
Getting Calamares installations to actually work for 32 bit OS's on EFI hardware

### ISSUE THREAD

**Issue by pcrepix** [calamares/calamares#971] opened 2018-05-30 13:23 UTC
#### Submission type

  - [x ] Bug report
  - [x ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> …3.2.0 (Debian Testing, current, but the version isn't important, it is the same with other versions too)

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> …Not important for this "bug"

#### What do you expect to have happen when Calamares installs?

> …Installation woks on for 32 bit OS's on EFI

#### Describe the issue you encountered

> …EFI installations fail for 32 bit OS's. Changing the /modules/bootloader/main.py (lines 251 and 252) and adding the option "--no-nvram" fixes the problem:

"247        check_target_env_call([libcalamares.job.configuration["grubInstall"],
248                              "--target=" + efi_target,
249                              "--efi-directory=" + efi_directory,
250                              "--bootloader-id=" + efi_bootloader_id,
251                              "--force", 
252                              "--no-nvram"])"

#### Steps to reproduce the problem

> …

#### Include the installation.log (usually ~/Calamares/Calamares/Calamares.log, of the user Calamares runs as):

> …
[bootloader.tar.gz](https://github.com/calamares/calamares/files/2054067/bootloader.tar.gz)

**Comment by abucodonosor** [comment] 2018-06-01 00:09
Please attach full installation log.

**Comment by pcrepix** [comment] 2018-06-01 07:33
I don't think an installation log will help much here though. If you chroot into the environment and try installing Grub in EFI mode with a 32 bit OS without the "--no-nvram" option it will fail, but if you use the "--no-nvram" option it works. On 64 bit OS's it works with or without the "--no-nvram" option.

So if you edit the bootloader/main.py module and change the entries in lines 251 and 252 and add that option it will work both for 32 and 64 bit OS's

**Comment by pcrepix** [comment] 2018-06-01 09:50
I don't know if it is a specific debian issue, as I have only used it on Debian. The --no-nvram fixed the problem on all EFI based hardware I have tried it on, and also in VM's with EFI enabled (VirtualBox and VMWare Workstation (Player)), so I don't think it is hardware dependent.

**Comment by abucodonosor** [comment] 2018-06-01 10:12
@pcrepix 

Again we need to see the full installtion lol.

While you think the disk(s) setup does not matter .. I fact is
the only think matters here.

Normally --no-nvram is used when you want to have your /boot on
a USB stick or on a multi-boot USB stick.

So there need to be different problem.
Whatever is a Distribution or Hardaware issue need be figured.

@philmmanjaro 

I can only find reports about Debian and Ubuntu with these..

@agaida 

Ideas ?

**Comment by abucodonosor** [comment] 2018-06-01 15:36
@pcrepix 

@highvoltage told on IRC Debian setup won't allow that as is..

**Comment by agaida** [comment] 2018-06-01 16:22
@abucodonosor - i have a few ideas - but no matching hardware to do anything - one of the ideas is asking Kano (Jörg Schirottke), the founder of Kanotix, about on freenode #kanotix. He is making (working) isos for EFI since ages - and his Kanotix was the only beside pure Debian that works with my Lenovo Miix 2 Baytrail (32bit UEFI + Atom Z) out of the box - so this should be possible to achive.

**Comment by pcrepix** [comment] 2018-06-01 16:53
That's the error I get when the modules/bootloader/main.py file is original:

![screenshot from 2018-06-01 16-29-34](https://user-images.githubusercontent.com/17968189/40852988-b5f464e8-65cc-11e8-8333-f50934223bf2.png)

And this is the log:

[OriginalFileSession.log](https://github.com/calamares/calamares/files/2063493/OriginalFileSession.log)

And this is the log when the file is edited and the installation works:

[EditedFileSession.log](https://github.com/calamares/calamares/files/2063494/EditedFileSession.log)

**Comment by abucodonosor** [comment] 2018-06-01 18:50
@pcrepix 

yes bc is trying to install 64bit on 32bit .. also it seems efivars is missing ?

However I don't really know the status of all this in Debian , I'm 
quoting @highvoltage from IRC:

```
<highvoltage> crazy: 32bit efi is not impossible to support on calamares on debian, but the current settings doesn't support it

...

<highvoltage> ok so, in debian our live CDs are only amd64 and i386. i386 ISOs don't support EFI yet, so, in the calamares-settings scripts we add, we merely check whether we have an efi system or not, and if it is efi, install 64 bit grub-efi or otherwise the legacy grub
<highvoltage> but if you shipped the packages for the 32 bit grub efi and add another check in the scripts, then I think it should work just fine.
<highvoltage> for that, you wouldn't need any direct code in calamares, and for the checks itself, there are some parts that could be re-used among distros.
```
So I let that to Debian peoples to figure.

**Comment by pcrepix** [comment] 2018-06-01 19:14
The PC's and VM's are 64bit with 64bit EFI firmware. For that you also need to install the 64bit EFI file even if you are installing a 32 bit OS.

Efivars doesn't work as expected in a 32 bit OS on 64 bit environment. The /sys/firmware/efi/efivars is there but empty, while on 64 bit OS's it is populated.

To get the OS to install nevertheless, you need to add the --no-nvram option.

**Comment by abucodonosor** [comment] 2018-06-01 19:58
@pcrepix 

na --no-nvram is not a proper fix.

**Comment by pcrepix** [comment] 2018-06-01 20:12
Why not? It makes the installation work, and it doesn't matter whether you are installing a 32 bit or 64 bit OS. The --no-nvram option makes the system ignore the contents of the /sys/firmware/efi/efivars/, which is irrelevant to grub anyway.

Also, if you install to conventional BIOS, another section of the file is used so then those lines aren't even read and the installation works too.

I've been editing that file for some time and haven't had any issues. The only problem is that everytime I get a Calamares update via the Debian Testing repo it overwrites the edited file and I have to edit it again. Reporting this here I was hoping that the file got corrected at the source, and eventually that change would also go into the Debian repo...

**Comment by V3n3RiX** [comment] 2018-06-01 20:28
Quick question : As others already stated, --no-nvram is just a workaround because for some reason you have your efivars mounted as readonly ... you can also try to run : mount -o rw,remount /sys/firmware/efi/efivars just before installation, and see if that helps (this should remount efivars as read write) ... if it works, then is just a live environment issue, and not a calamares issue ...

**Comment by pcrepix** [comment] 2018-06-01 21:02
Trying that I get "mount point not mounted or bad option".

**Comment by abucodonosor** [comment] 2018-06-01 21:18
@pcrepix 

yes ofc it works as workaround .. but not as proper fix for everyone.

There are Distros where 32bit EFI works as is and like I've posted before
Debian setup as is , is 'not supporting what you are trying to do'.

We need to wait for Debian peoples to tell what is missing in the LiveISO
setup they have to support that combo. 
( Like I understand calamare-setup script need to be changed and some package(s)
 need be installed on the Debian LiveISO )

**Comment by agaida** [comment] 2018-06-01 21:26
The second thing is: Make it sense to install a 64bit OS on a system with 32bit UEFI and how much work it is - the most cheap baytrail (32bit UEFI) things are really small and basic machines with an Atom and max. 2G Ram (according to the Microsoft Home basic spec) - so a 32bit system fits in the very most cases far better than a 64 bit OS (like in the mentiond Tablet/Convertible)

**Comment by pcrepix** [comment] 2018-06-01 21:37
It isn't about installing a 64 bit OS on 32 bit UEFI, but actually quite the opposite. It is about installing a 32 bit OS on UEFI hardware (the EFI firmware can be either 32 bit or 64 bit, and also the CPU can be either 32 or 64 bit capable).

**Comment by agaida** [comment] 2018-06-01 21:42
Ok, you know how to have fun :D - in the 64 -> 32 case i might be able to help

**Comment by pcrepix** [comment] 2018-06-01 21:59
@abucodonosor, even with the --no-nvram option the setup should probably still work on EFI32 firmware. But as I don't have any such hardware I can't test it. What I can just say is that the --no-nvram option hasn't done any harm to any installation I have seen, and it works, while without it, it just won't always work. So why not just add it?

**Comment by abucodonosor** [comment] 2018-06-01 22:17
@pcrepix 

again , beacuse is wrong that way :-)

**Comment by pcrepix** [comment] 2018-06-01 23:00
Why is it wrong if it works?

**Comment by pcrepix** [comment] 2018-06-01 23:11
Or does anyone have a link to an iso for a 32 bit OS that uses Calamares as installer that isn't Debian based? Maybe I can then test the installation and check whether the --no-nvram option works there too... If it works there wouldn't that clear up any doubts?

**Comment by philmmanjaro** [comment] 2018-06-02 06:29
@pcrepix: please give [Manjaro 32 bit](https://osdn.net/projects/manjaro32/storage/xfce/) a try. There it works just fine without changing anything. Tested with VirtualBox on my end.

**Comment by pcrepix** [comment] 2018-06-02 07:52
Actually it doesn't work. I get the same error message as with debian:

![manjaro](https://user-images.githubusercontent.com/17968189/40872178-581e0490-664a-11e8-9da6-ec61fe3c17ff.png)

When you tried it in VBox, did you setup the VM with "EFI" enabled (in the System settings, 2nd lowest checkbox)?

**Comment by pcrepix** [comment] 2018-06-02 08:16
And after editing the file, the installation works fine! So it is not a "Debian" issue.

**Comment by abucodonosor** [comment] 2018-06-02 10:11
@pcrepix 

Please can you stop that ? Your issue is a Debian one , clearly from the logs and
from what Debian peoples confirmed.

A --no-nvram option for everyone by default won't be.

Manajro rc1 ISO got an missing package that is all. 

@philmmanjaro 

This rc1 ISO is missing efibootmgr on the installed system

After installing it all is fine:

```
(1/1) Installiere efibootmgr                                                                                     [####################################################################] 100%
:: Starte post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[root@manjaro /]# grub-install --target=i386-efi --efi-directory=/boot/efi --bootloader-id=Manjaro --force
i386-efi wird für Ihre Plattform installiert.
installation beendet. Keine Fehler aufgetreten.

```

**Comment by adriaandegroot** [comment] 2018-06-18 10:54
> Efivars doesn't work as expected in a 32 bit OS on 64 bit environment. The /sys/firmware/efi/efivars is there but empty, while on 64 bit OS's it is populated.

This is supported by the [log file](https://github.com/calamares/calamares/files/2063493/OriginalFileSession.log), which prints (twice) *EFI variables are not supported*. That's probably from efibootmgr. The last couple of comments about Manjaro are a red herring.

So the underlying question is: why don't you @pcrepix have support for EFI variables? If we can reliably detect that they can't be written to, then -- and only then -- can we switch on `--no-nvram` when needed. I don't know what efi variables are being updated, though, and I can imagine that **not** updating them has interesting failure modes as well (e.g. after wiping the disk) so that unconditionally using that flag is wrong as well.

**Comment by mirh** [comment] 2018-08-18 00:09
> Getting Calamares installations to actually work for 32 bit OS's on EFI hardware

Sorry, what is this bug even about?

x86 OS not booting on <any> uefi system
x64 OS not booting on x86 uefi
Or [some] firmware having someway broken NVRAM that cannot somehow be written to?

Could the title be adjusted?

**Comment by adriaandegroot** [comment] 2018-10-08 08:05
I'm going to close this issue, echoing @mirh's comment that the issue has become overly muddled. I'll open a related issue for UEFI32 support -- installing a 64-bit Debian derivative on a system with a 32-bit EFI, which is the kind of machine @agaida describes above, and there are specific downstream questions about them.

**Closed by adriaandegroot** 2018-10-08 08:05 UTC
