### ISSUE TITLE
Feren OS Installer never loads - Continuous Spinner

### ISSUE THREAD

**Issue by blu-frog** [calamares/calamares#1718] opened 2021-06-05 16:05 UTC
Unable to get the first window of the OS Installer to successfully load. I was able to use this same Live USB stick to successfully install on a different system (Toshiba Laptop).

Repro Steps:

Double-click the "Install Feren OS" shortcut on the desktop
Wait for the application to fully load so as to change the Language Selection (from EN-UK to EN-US)
Repro Rate: 3/3 (Including booting with `nomodeset` for the nVidia Card)

![calamares_FerenOS](https://user-images.githubusercontent.com/40070339/120897818-e6c3ca00-c5dc-11eb-9f42-95f34c4b5375.png)

Note: Cannot terminate calamares when this application window gets stuck either.

System Info:
**Dell Optiplex 755 (Desktop) with NVIDIA GK208B [GeForce GT 710]**

Operating System: Feren OS 2021.04
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.8.0-48-generic
OS Type: 64-bit
Graphics Platform: X11
Processors: 2 × Intel® Core™2 Duo CPU E8400 @ 3.00GHz
Memory: 7.6 GiB of RAM
Graphics Processor: llvmpipe

Cross-Posted in [the Feren OS Reporting Center](https://github.com/feren-OS/Bug-Reporting-Center/issues/233) too.

**Comment by abucodonosor** [comment] 2021-06-05 17:48
Please attach logs, without, those bug reports are useless.
( I want to see a dmesg too when that happens )

Bugs regarding nvidia -> nvidia forum and/or your vendor / distribution.

**Comment by adriaandegroot** [comment] 2021-06-08 15:51
Fetching the FerenOS april 2021 snapshot to try this .. @dominichayesferen this something you can double-check?

**Comment by adriaandegroot** [comment] 2021-06-08 16:18
The screenshot shows "waiting on 6 modules", so it's like all the modules that want to / need to report some kind of startup check are waiting on each other (for almost a half-hour now!). I just started the system on a VM, and it "just worked".

But then I looked back: the reporter's machine is a 2-core thingy, and even my VMs are set up with 4 cores these days, so the check is not representative. Starting it up again with changed VM settings, .. (BTW, the graphics are **super** glitchy in my VirtualBox, possibly something to do with transparency and VBox having a rather limited GPU emulation) .. has no effect. Neither does having 1 CPU, or booting in EN-US. I'm having a hard time reproducing this.

@blu-frog if you start the installed ISO, and then start a terminal (start button -> *System* -> *Konsole*), you can then take a look at the command that is run by the installer icon when you click on it on the desktop, e.g. by looking at the whole file (`cat`) or just at the command (`grep`):

```
cat Desktop/calamares.desktop
grep Exec Desktop/calamares.desktop
```
You'll see a line starting with `Exec=` followed by `sudo env` and so on. You can run the command after `Exec=` by copy-pasting into the terminal. If you do so, tack on `-D6` at the end. When you do so, Calamares will spit out a bunch of debugging information (and probably continue to do so every few seconds). Cancel the install. The debugging log is stored at `/root/.cache/calamares/session.log`. You could pastebin it, or attach it here.

I *vaguely* suspect that os-prober is doing something and taking a long time about it, and that's hanging up the rest.

**Comment by blu-frog** [comment] 2021-06-08 16:45
@adriaandegroot - Will try and do so this evening (Pacific Time Zone).

**Comment by dominichayesferen** [comment] 2021-06-09 22:12
> Fetching the FerenOS april 2021 snapshot to try this .. @dominichayesferen this something you can double-check?

Every time I've tried it over here it progresses fine past the spinner.

**Comment by adriaandegroot** [comment] 2021-06-11 12:28
Closing this as "unable to reproduce", sorry. It **sounds** like it's getting wedged, waiting on probing all the disks in the system, but without a log file there's not much we can say.

**Closed by adriaandegroot** 2021-06-11 12:28 UTC
Labels: hacking: in-progress
