### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by Justman10000** [calamares/calamares#2055] opened 2022-10-06 22:49 UTC
**Describe the bug**
Calamares cannot be installed!

**To Reproduce**
1. Download newest [.tar.gz](https://github.com/calamares/calamares/releases/download/v3.2.61/calamares-3.2.61.tar.gz)
2. `gunzip *.gz`
3. `tar xvf *.tar`
4. `cd calamares-3.2.61`
5. `apt install build-essential -y`
6. `apt install cmake -y`
7. `cmake`

**Screenshots and Logs**
![grafik](https://user-images.githubusercontent.com/49990629/194432507-e9fdb383-c0dd-41e6-ac69-881bf7cb4be5.png)

**Comment by dalto8** [comment] 2022-10-06 22:51
It looks like you haven't installed all the dependencies.

**Comment by kkofler** [comment] 2022-10-06 23:20
You need Qt 5 with development headers, and a whole bunch of other libraries. Not a bug, closing.

**Closed by kkofler** 2022-10-06 23:20 UTC
