### ISSUE TITLE
OEM mode

### ISSUE THREAD

**Issue by Strit** [calamares/calamares#762] opened 2017-07-07 12:13 UTC
HI there.

I haven't been able to find anything related to OEM installs on github or anywhere else.

I would love to see OEM installs made possible with Calamares.
OEM makes it easier to ship computers pre-loaded with the distrobution of choice, where the end user finishes the setup with username, password localizations etc.

**Comment by kkofler** [comment] 2017-07-09 22:20
Isn't that what the no-chroot mode is for?

**Comment by adriaandegroot** [comment] 2017-07-10 10:36
This is roughly the same as issue #291 , doing some kind of setup on first boot -- and @kkofler , dont-chroot mode is seriously under-documented (all I could find was https://github.com/calamares/calamares/blob/master/settings.conf )

**Comment by kkofler** [comment] 2017-07-10 11:57
As far as I know, that mode was added for the Netrunner ARM images, it was mostly an internal Blue Systems thing. But it should also work for other distros.

And yes, I think this bug is a duplicate of #291.

**Comment by philmmanjaro** [comment] 2017-09-08 05:57
Currently working on some: https://github.com/philmmanjaro/project-sx

**Comment by kkofler** [comment] 2017-09-08 08:29
How does your setup look like? I see that https://github.com/philmmanjaro/project-sx/blob/master/calamares-oem/postinstall-settings/settings.conf has `dont-chroot: false`, so how are you running the postinstaller? I'd expect the postinstaller to run from within the installed environment, with `dont-chroot: true`.

**Comment by philmmanjaro** [comment] 2017-09-08 13:09
You may check one of our [ISOs](https://sourceforge.net/projects/manjaro-sx/) we release for our hardware. Seems I forgot that option. Therefore I used the workaround via [postoem](https://github.com/philmmanjaro/project-sx/blob/master/calamares-oem/modules/postoem/main.py) module.

**Comment by abucodonosor** [comment] 2017-09-18 20:03
@philmmanjaro 

So can I assign that to you ? and add WIP label ?

**Comment by adriaandegroot** [comment] 2017-09-25 10:00
The Netrunner ARM images do have a post-install (well, since the images are written to SD card, there's never really an install to speak of) mode, where Calamares does some resizing, user creation, etc., inside the installed system. It seems to work pretty well. I have not looked at the configuration used there, though.

So I suspect this is "already done", but under-documented. And whatever Manjaro has done is pretty much invisible without a PR.

**Comment by abucodonosor** [comment] 2017-09-26 15:44
@adriaandegroot 

So all we need are some docs and *maybe* some example configuration files ?

**Comment by adriaandegroot** [comment] 2017-12-07 13:05
Closing this as dup of #291

**Closed by adriaandegroot** 2017-12-07 13:05 UTC
Labels: New Feature
