### ISSUE TITLE
ssd_extra_mount_options is not defined in fstab module main.py, Calamares 3.3.0

### ISSUE THREAD

**Issue by ArrayBolt3** [calamares/calamares#1980] opened 2022-06-07 17:29 UTC
**Describe the bug**
I'm testing the new Calamares 3.3.0 from the tip of the Master branch (or at least it was from the tip of the Master branch yesterday), and have run into a bug. I'm using Lubuntu 22.10 Kinetic Kudu Alpha, and I have rewritten the Calamares config to be compatible with Calamares 3.3.0. The configuration I'm using is at [ArrayBolt3/calamares-settings-ubuntu](https://github.com/ArrayBolt3/calamares-settings-ubuntu), in the lubuntu/modules directory.

When the installer gets to the "Writing fstab" stage, an error appears stating that `ssd_extra_mount_options` is not defined in the [fstab module, main.py file](https://github.com/calamares/calamares/blob/calamares/src/modules/fstab/main.py). The line of code that is erroring out is at line 417. I removed the `ssd_extra_mount_options` from that line, and also from line 102, and the installer was then able to pass the "Writing fstab" stage (though I have no idea if it wrote anything useful in fstab, as I wasn't able to get a successful install due to a different bug).

**To Reproduce**
1. Download the latest Lubuntu Kinetic ISO.
2. Launch it in a Gnome Boxes VM, with 8 GB RAM and 40 GB disk space.
3. For every file in the `/etc/calamares/modules` directory, replace it with the corresponding file from `ArrayBolt3/calamares-settings-ubuntu/lubuntu/modules`.
4. Add the kinetic-proposed repo to the Lubuntu Live environment by clicking on the Application Menu, clicking "Software Sources", clicking "Updates", checking "Pre-released updates", and then clicking "Close" (I think that's what the button is called). Allow it to refresh the software list.
5. Open a terminal, and run `sudo apt install calamares`. This will pull the latest Calamares build into Lubuntu.
6. Open a terminal, and run `sudo -E bash`.
7. Run `export $(dbus-launch)`. This is required to get Calamares to run.
8. Run `calamares -D6` to launch Calamares.
9. Proceed with the installation process and wait for the error.

**Expected behavior**
The installation should finish without errors.

**Screenshots and Logs**
I don't have any log files ATM, since I'm writing this in a hurry, but the bug is very easy to reproduce in a VM, and is able to be reproduced reliably. If you need logs, I'll attach them later.

**Comment by dalto8** [comment] 2022-06-07 18:40
The config for the mount and fstab modules is significantly different for Calmares 3.3.  You will need to go back to the sample configs and make your customizations from there.

**Comment by monetaryabyss** [comment] 2022-06-07 18:53
> The config for the mount and fstab modules is significantly different for Calmares 3.3.  You will need to go back to the sample configs and make your customizations from there.
> 
> Much of the configuration that was previously done in fstab.conf has moved to mount.conf.  Also, the format of many of the options has changed.

The configuration files were edited to follow the new 3.3.x format. There is indeed an issue with the main.py in fstab that references ssd_extra_mount_options. It looks like that code was intended to be removed in this module but maybe not completely or it needs to be returned. Either way there is an undefined variable.

**Comment by dalto8** [comment] 2022-06-07 18:58
I see.  It looks like it happened when 3.3 was merged.

**Comment by demmm** [comment] 2022-06-07 19:23
This merge moved the old, no longer compatible settings back:
https://github.com/calamares/calamares/commit/63ee982d36584fd56c8ac096440406facfec2240

**Comment by monetaryabyss** [comment] 2022-06-08 03:12
Looking at the code I believe the `ssd_extra_mount_options` is just a leftover artifact. The "extra" options appear to be part of the mount module configuration now and go into the Calamares globalstorage as the `mount_options_list`. The fstab module then consumes that to create the fstab for the system.

**Closed** 2022-06-08 19:35 UTC
