### ISSUE TITLE
Make a good docs to make people added it to their distros

### ISSUE THREAD

**Issue by BeyondDevy** [calamares/calamares#1703] opened 2021-05-23 11:54 UTC
I wanna add calamares to my distro but i can't because i don't there is not good docs to do that

**Comment by demmm** [comment] 2021-05-23 17:47
You'll have to be much more specific then this. What exactly did you read? There are docs to help build, there are docs to help you deploy, every single module comes with a .conf with extensive explanations how to use that module.
https://github.com/calamares/calamares/wiki
https://github.com/calamares/calamares/wiki/Develop-Guide#build
https://github.com/calamares/calamares/wiki/Deploy-Guide
Examples of module .conf:
https://github.com/calamares/calamares/blob/calamares/src/modules/bootloader/bootloader.conf
https://github.com/calamares/calamares/blob/calamares/src/modules/partition/partition.conf

Closing this issue, since it is not a bug report or feature request, nor is there any indication what is read or what is not clear.

**Closed by demmm** 2021-05-23 17:47 UTC
