### ISSUE TITLE
Error: Failed to add new partition (ext4) on '/dev/sda. Old situation: /dev/sda2: sector 0 already used. Failed to add #2 partition: numerical result of out of range

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#1339] opened 2020-03-16 09:57 UTC
**Describe the bug**
Error: Failed to add new partition (ext4) on '/dev/sda. Old situation: /dev/sda2: sector 0 already used. Failed to add #2 partition: numerical result of out of range

**To Reproduce**
User want to install Manjaro 19.0.2 KDE version to his portable SSD, and was using UEFI + GPT. His partition plan was a 2GB for /boot/efi, 16 GB for linuxswap, 60GB for /, and 320 GB for /home. However, when he starts installing, the error message says "Failed to add new partition (ext4) on '/dev/sda. Old situation: /dev/sda2: sector 0 already used. Failed to add #2 partition: numerical result of out of range".

**Expected behavior**
Able to install Manjaro 19.0.2 with desired manual partition scheme.

**Screenshots and Logs**
![f4abcb487836d6599f1e0fbdae37aa5ac1174f00](https://user-images.githubusercontent.com/5050022/76744415-8268e080-6774-11ea-9cfa-9a120c54e2f9.jpeg)

**Additional context**
Most likely related to https://github.com/calamares/calamares/issues/1332#issuecomment-593361528

@karelzak and @stikonas: did we add a regression by patching **linux-utils** as we did for #1332?

**Comment by philmmanjaro** [comment] 2020-03-16 09:59
Additional information:

https://forum.manjaro.org/t/129642
https://www.reddit.com/r/ManjaroLinux/comments/fhyytq/noob_question_formatting_hdd/

**Comment by Pisces311** [comment] 2020-03-17 16:37
I finnally solved this problem by leaving 32 MB free space at the beginning of my SSD. Seems that in this situation 1 MB is not enough.

**Comment by demmm** [comment] 2020-03-17 20:06
Closing, not a bug, but user error, GPT on MBR needs 8 Mb of empty space (not 32) at the beginning of the drive.

**Comment by demmm** [comment] 2020-03-18 11:53
For reference, KaOS has used a pop-up warning for over three years to avoid this issue, see the comment:
https://github.com/calamares/calamares/issues/720#issuecomment-313510224
The linked patch does not check for any setup, just checks if a BIOS setup is detected in manual, thus never submitted for calamares master (upstream).

**Comment by adriaandegroot** [comment] 2020-03-18 21:15
Reopening as a reminder to pull in @demmm patch from above.

**Comment by demmm** [comment] 2020-03-19 01:51
@adriaandegroot do you want to use as is? Then I can open a pull request.  If you want to add drive setup checks, then I will leave the patching up to you.

**Closed** 2020-03-24 21:37 UTC
Labels: bug: not-really
