### ISSUE TITLE
summary window expands, cutting off buttons with 800x600 screen

### ISSUE THREAD

**Issue by wxl** [calamares/calamares#1121] opened 2019-04-15 06:31 UTC
**Describe the bug**
I know much work has been done to deal with smaller screen sizes. I also know that the fix for #778 resulted in a preference for expanding window sizes versus scroll bars. However, I think that it also needs the small screen treatment. In this case, with an 800x600 resolution (VirtualBox default), the summary window expands, cutting off buttons and yet still resulting in a scroll bar as well.

**To Reproduce**
 1. Ensure you're using an 800x600 resolution
 1. Load Calamares
 3. Complete all the steps up to and including the step to put in your username and password
 4. Click Next

**Expected behavior**
Summary window stays the same size as previous.

**Actual behavior**
 * Summary window enlarges. 
 * If you go back to the previous screen, the enlarged size remains. 
 * It appears the enlarging occurs both vertically and horizontially because the top of the screen is filled and the buttons are cut off.
 * Scroll bars, still.

It's clear that the height violates the proposed window height (perhaps bounding the enlargement by the proposed window size might be a good fix?):

```
2019-04-15 - 06:00:11 [6]: Available desktop QSize(800, 568) minimum size QSize(800, 520) 
2019-04-15 - 06:00:11 [6]:   Proposed window size: 800 520 
⋮
2019-04-14 - 23:00:29 [6]: Summary widget is larger than viewport, enlarge by 102 to QSize(688, 571) 
```

**Screenshots and Logs**
![bug in action](https://i.imgur.com/lS1te5D.gif)

**Additional context**
Lubuntu 19.04 20190413.2
calamares 3.2.4-0ubuntu3

[Downstream bug](https://bugs.launchpad.net/ubuntu/+source/calamares/+bug/1824758)

**Comment by adriaandegroot** [comment] 2019-04-15 10:58
Looks like on startup it's using desktop space taking-into-account the taskbar, and on expand it's using the screen size. You can influence this in 3.2.4 with the *windowExpanding* setting in `branding.desc`

**Comment by adriaandegroot** [comment] 2019-04-15 11:44
You can influence this in 3.2.4 with the *windowExpanding* setting in `branding.desc`.

The thing is, your desktop size is 800x568; that means it's taking the 32-pixel taskbar at the bottom into account. (You can check by dragging to a larger taskbar; it will show a smaller space-available). However, that does **not** take the height of the window decorations into account. So Calamares resizes to the maximum available size, which it could have if you didn't have those 32-or-so pixels of kwin decoration.

**Comment by abucodonosor** [comment] 2019-04-15 13:57
@adriaandegroot 

I think with Kwin all is fine .. Lubuntu may use openbox or some such.

**Comment by wxl** [comment] 2019-04-15 15:58
I agree that `windowExpanding` provides solutions to this, both in `fullscreen` and `noexpand` and those are welcome additions. I think going forward, Lubuntu will use `fullscreen` as this is ultimately the most robust of solutions. 

Still, I think that the code is allowing for expansion beyond the available space is problematic. Excuse my ignorance, but is it possible include window decorations into the calculation? I can agree with @adriaandegroot that Kwin works fine and Openbox (which, yes, is what Lubuntu uses) is the problem child.

**Comment by abucodonosor** [comment] 2019-04-15 18:56
@wxl 

I don't think the windeco is the problem here. The problem is most probably
the 'panel' for Openbox.

I am not sure lxqt has some option to allow/disallow windows going unter the panel,
and is not clear to me even they do Openbox will respect that.

Maybe @agaida knows ?

If is a Openbox && panel ( which I think it is ) issue there is not much one
magically can do to fix that since you can set the panel size ( I guess ) from
16px to XXpx , with no way for calamares to figure.

**Comment by agaida** [comment] 2019-04-15 19:10
@wxl and @abucodonosor  - no, we don't care about WM specific things - LXQt is WM agnostic. So the only chance is to tell openbox about directly if possible.

**Comment by adriaandegroot** [comment] 2019-04-15 20:36
@wxl So with plasma and an 800x600 screen, I get a suggested 800x570 maximum size, but when it grows in the summary phase, KWin seems to keep the window inside the **actual** desktop area, taking window-deco into account. The code is in `CalamaresWindow.cpp`, around line 82. That's where the window size is set. The desktop's `availableGeometry()` is called, and that seems to yield sensible results (also with your WM). Then the resize happens, and .. actually, you might try editing the `windowPreferredHeight` to, say, 590, to see what happens. You'd need to try in both KWin and something else, though.

**Comment by abucodonosor** [comment] 2019-04-15 20:39
@adriaandegroot 

is Openbox doing funny things.. it ignores the panel it seems

**Comment by wxl** [comment] 2019-04-16 04:55
@adriaandegroot For better or for worse, we're not using KWin, so that's not really an option for us. 

@abucodonosor LXDE had an option to reserve space for the panel with maximized windows. It sounds like if LXQt had something similar we'd be good to go, right?

**Comment by abucodonosor** [comment] 2019-04-16 09:46
@wxl 

yes that should work fine then.

**Comment by adriaandegroot** [comment] 2019-04-25 10:33
I'm closing this one as "Calamares does what it can according to the information it gets, and then it's up to the window manager to help out". With suitable window-expanding settings and a minimum size that would be fullscreen, or simply going fullscreen (assuming the WM handles **that** case correctly) you'll get a workable solution. I've added some better scrollarea support in the summary and licenses page. If there's specific things still buggy, please file other issues.

**Closed by adriaandegroot** 2019-04-25 10:33 UTC
