### ISSUE TITLE
Calamares fails to create partitions

### ISSUE THREAD

**Issue by zoeruda** [calamares/calamares#1872] opened 2022-01-09 03:53 UTC
Posting here because I have failed at identifying any uniqueness in my configuration which might cause this problem, and I have successfully replicated it many times now.

**Describe the bug**
Installer fails to create partitions on NVMe disk.
Machine details:
CPU: quad core Intel Core i5-8250U (-MT MCP-) speed/min/max: 900/400/3400 MHz
Kernel: 5.15.13-zen1-1-zen x86_64 Up: 16m Mem: 3796.2/7730.3 MiB (49.1%)
Storage: 357.68 GiB (2.0% used) Procs: 227 Shell: Bash inxi: 3.3.11

**To Reproduce**
1. Boot from a live image of KDE Neon Unstable/Garuda Linux KDE Git
2. Open the Calamares installer
3. Choose the "Erase Disk" option

**Expected behavior**
Installation succeeds seamlessly.

**Screenshots and Logs**
[log](https://github.com/calamares/calamares/files/7834818/RAqWTjLb.txt)

**Additional context**
The log and screenshot are from Garuda Linux, but I successfully replicated this bug in KDE Neon, which uses ext4 for main partition.
Another note: after launching Calamares again and choosing manual partitioning, then mounting the existing partitions, installation succeeds with no problem. It is only when trying to both create the partitions and mount them at the same go.

**Comment by adriaandegroot** [comment] 2022-01-09 21:18
The log, unfortunately, shows the regular kpmcore failure report -- which is completely useless. We don't know **why** the last command, creating the filesystem, might have failed. Do you have pre-existing partitions on the drive? I vaguely recall an issue reported here where it turned out that tools were detecting a partition signature and refusing to work.

**Comment by zoeruda** [comment] 2022-01-09 22:02
Thanks for commenting. This seems to be a similar issue indeed, as I have been testing installations one after the other and this shows up when a similar partition table already exists from a previous installation. Any way I can extract more information on what's going on? I used `sudo calamares -D6`

**Comment by demmm** [comment] 2022-01-10 12:55
Easiest to get real useful info would be to run the failing command(s) manually (not starting the installer).  Would it be possible to run `mkfs.btrfs --force /dev/nvme0n1p2` and see if that brings some more output?  Make sure though the target partition does not contain needed data and probably best to do this from a live ISO.

**Comment by vedranmiletic** [comment] 2022-03-12 17:10
Does unchecking `On Login` and `On Attach` in Plasma `System Settings` -> `Removable Storage` -> `Removable Devices` help? It helped in my case (I'm using Garuda Linux).

**Comment by demmm** [comment] 2022-03-12 20:45
Any of you having this issue, what Plasma version is in use?
See:
https://github.com/calamares/calamares/issues/1885

**Comment by vedranmiletic** [comment] 2022-03-12 20:49
@demmm 5.24.3 in my case.

**Comment by demmm** [comment] 2022-03-13 10:52
Since the original report was for unstable/git versions of their distro, it is fair to assume this was for Plasma 5.24 beta already, so closing this report as a duplicate of https://github.com/calamares/calamares/issues/1885
If you can reproduce with any plasma version 5.23.5 or older, please reopen.

**Closed by demmm** 2022-03-13 10:52 UTC

**Comment by valueerrorx** [comment] 2022-09-07 13:16
this problem is still present in KDE 5.24.6

it is actually not the partitioning that fails (calamares creates a partition without problems) - it is the filesystem check afterwards
```e2fsck -f -y -v /dev/sda1```
fails because the partition is mounted!!

why is it mounted? because KDE does that with known devices.

as @vedranmiletic mentioned you can workaround this problem by deactivating automount of known devices in systemsettings
https://github.com/calamares/calamares/issues/1872#issuecomment-1065921394

**Comment by demmm** [comment] 2022-09-07 13:21
As noted in https://github.com/calamares/calamares/issues/1872 (comment with closing), this is a known upstream issue and fixed in Plasma 5.25 and beyond, those using 5.24 will have to use the workaround posted in that issue or apply the upstream (plasma) patch to fix.

**Comment by php4fan** [comment] 2022-09-24 14:30
I downloaded a Plasma Edition Manjaro ISO a few hours ago and tried to install, and I get the "failed to create partition" error. Is it the known issue? If so, how come the latest ISOs don't have the latest Plasma with the fix yet?

**Comment by demmm** [comment] 2022-09-24 14:49
> I downloaded a Plasma Edition Manjaro ISO a few hours ago and tried to install, and I get the "failed to create partition" error. Is it the known issue? If so, how come the latest ISOs don't have the latest Plasma with the fix yet?

This is not a Manjaro bug tracker, no-one here knows how Manjaro builds their Calamares version or ISO, you need to report this with your distribution.
See:
https://calamares.io/issues/
And especially:
https://calamares.io/issues/#end-users
