### ISSUE TITLE
Erase disk; select no-swap & 'Next' is greyed

### ISSUE THREAD

**Issue by guiverc** [calamares/calamares#1959] opened 2022-05-22 04:11 UTC
**Describe the bug**

Trying to install Lubuntu using current kinetic (*development*) daily, on clicking ERASE DISK and then changing in the drop-down the "Swap to file" to "No Swap", as I don't want encryption I want to continue via pressing of NEXT button; alas it's greyed.

To get NEXT to un-grey requires me to change to another option (ie. click manual, then back to erase disk, or click encryption & enter passwords then uncheck encryption) & NEXT can be selected.

Bug reported on Ubuntu can be found here - https://bugs.launchpad.net/ubuntu/+source/calamares/+bug/1975393

**To Reproduce**

1. Select the "Erase disk " radio box and the select from the dropdown option "No Swap"

2. This results in being unable to continue with the install by selecting "Next" in the lower right hand corner ( see attached image)

3. In order to proceed select the "Manual partitioning" radio box and the again "Erase disk" option
this enabled selecting "no swap" and then able to proceed with next and continue the installation.

**Expected behavior**

NEXT should be acceptable without extra clicks changing options, then needing to reverse those changes

**Screenshots and Logs**

I haven't produced any; however if helpful/required - please let me know & I'll re-run testing.
This was tested on multiple boxes including both uEFI & BIOS/legacy/CSM

**Additional context**

Calamares used is
  Version table:
     3.2.58-1ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu kinetic/universe amd64 Packages

`calamares --version` reports 3.2.58

I've not tested beyond Lubuntu; if you need me to test another non-Ubuntu system (remove out settings) please let me know.

**Comment by demmm** [comment] 2022-05-22 09:08
Duplicate of https://github.com/calamares/calamares/issues/1953
Fixed in 3.2.58.1
https://github.com/calamares/calamares/releases/tag/v3.2.58.1

**Closed by demmm** 2022-05-22 09:08 UTC

**Comment by guiverc** [comment] 2022-05-22 11:31
Apologies, I looked but didn't see it.
