### ISSUE TITLE
Installation failed while unpackfs 

### ISSUE THREAD

**Issue by casualx85** [calamares/calamares#1089] opened 2019-02-19 22:30 UTC
##############################################
"Installation failed"
Boost.Python-error in job "unpackfs".
<class 'KeyError'>
('unpack',)

Traceback:

File "/usr/lib/calamares/modules/unpackfs/main.py, line 315, in run
    for entry in job.configuration["unpack"]:

##############################################

https://pastebin.com/9xwDNqW5 (Output of "cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib -DWITH_PYTHONQT:BOOL=ON")

**Comment by adriaandegroot** [comment] 2019-02-20 10:44
Your configuration is broken. You have enabled the *unpackfs* module, but you either have no *unpackfs.conf*, or the one you do have has no *unpack* key in it.

**Comment by adriaandegroot** [comment] 2019-02-22 11:54
.. and in this case I think this is worth leaving like it is: if the distro is not configuring unpackfs correctly,  that's the most important part of an **installation** process, there's really no point in holding hands. So I'm going to close this as "works as intended, please fix your configuration file". **If** you're reporting this for an actual installation image (like, for instance, a Lubuntu liveCD), please report to them.

**Closed by adriaandegroot** 2019-02-22 11:54 UTC
