### ISSUE TITLE
Latin keyboard layout should be added if a non-latin one is selected

### ISSUE THREAD

**Issue by AleksejShilin** [calamares/calamares#1211] opened 2019-08-03 07:31 UTC
**Describe the bug**
There are many keyboard layouts which are not supersets of the standard latin layout. (See [this list](https://sources.debian.org/src/console-setup/1.191/Keyboard/kbdcompiler/#L44), for example.) When such layout is selected in Calamares, it immediately becomes the only one available, both during next installation steps and for the installed system. This leads to the following issues:

1. User is unable to enter his/her preferred login during installation.
2. User is unable to enter his/her preferred hostname during installation.

To proceed with the installation, user has to manually add a latin keyboard layout using available configuration tools like the GNOME Settings app. But then after successful installation and rebooting into the installed system:

3. User is unable to enter his/her login.
4. In case the display manager allows to select the account with a mouse, user may not be able to enter his/her password.

It is very common for operating system installers to also add a latin layout like 'us' when a non-latin one is selected. They also add a key combination to toggle between these layouts. (See the attached /etc/default/keyboard files from Debian GNU/Linux systems installed using Calamares and standard Debian Installer with Russian keyboard layout selected.)

**Expected behavior**
Calamares should add a latin keyboard layout e.g. 'us' when a non-latin one is selected, both during installation and for the installed system.

**Screenshots and Logs**
![Снимок экрана от 2019-08-03 10-11-48](https://user-images.githubusercontent.com/53618417/62408927-8165b300-b5d8-11e9-81e7-4e6a3df9b207.png)
[session.log](https://github.com/calamares/calamares/files/3463479/session.log)
[etc.default.keyboard (Calamares).txt](https://github.com/calamares/calamares/files/3463482/etc.default.keyboard.Calamares.txt)
[etc.default.keyboard (Debian Installer).txt](https://github.com/calamares/calamares/files/3463483/etc.default.keyboard.Debian.Installer.txt)

**Comment by Pixeliz3d** [comment] 2020-03-08 11:24
Any progress on this issue?

**Comment by adriaandegroot** [comment] 2020-03-09 01:57
PRs are welcome, and encouraged. The example keyboard-config files are useful, for sure, but otherwise nothing is happening in this issue until someone mentions it in a commit, merge, or sticks it on a milestone.

**Comment by kkofler** [comment] 2020-07-04 08:57
The problem is that there is only one systemwide keyboard layout. Toggling is implemented by the desktop environment and hence depends on the desktop environment the user is running (and the available choices are normally configured per user, not systemwide). So this feature request is not something Calamares can easily implement (and I disagree with the "bug" label, it's an RFE).

**Comment by kkofler** [comment] 2020-07-04 09:06
Actually, it was pointed out on IRC that `/etc/X11/xorg.conf.d/00-keyboard.conf` does actually support multiple keyboard layouts: https://www.x.org/releases/X11R7.7/doc/xorg-docs/input/XKB-Config.html#Advanced_Configuration

**Comment by Jedi-Mind-Tricks** [comment] 2020-07-04 14:38
@AleksejShilin provided a great explanation and even shared debian way to handle the issue (see one of his [links](https://sources.debian.org/src/console-setup/1.191/Keyboard/kbdcompiler/#L44)).

I think maintainers are not fully understand how big the deal is: **all users who use non-latin superset KB layouts** (af am ara ben bd bg bt by deva et ge gh gr guj guru il in iq ir iku kan kh kz la lao lk kg ma mk mm mn mv mal np ori pk ru scc sy syr tel th tj tam tib ua uig uz) are affected.

The problems they encounter:
1. If you want to use non-latin KB layout there's no point at all for you to change it in Calamares since at the point of choosing login you can't use non-latin characters anyway.
Typically you want to chooe 2 layouts in OS installer: US and a local one.

2. Some people (me included) got awful cases in OS installation:
1) leave US (english) layout in Calamares
2) set username and password
3) realize you should set layout to RU since you will need to type in it anyway
4) go back in wizard and set layout to RU (but password and username are still remains in english)
5) install, reboot and can't log in into OS (login screen only got RU layout and can't change it - this is X server "layer" we're talking about)
6) add it manually via CLI (Manjaro community even have tutorials on how to fix this)
or just rage quit

Now on config file that @kkofler mentioned:
- I reproduced the scenario above in VM and got installed OS with password in english but with only russian KB layout.
- Then I added "us" layout and default shortcut to switch them to the config (/etc/X11/xorg.conf.d/00-keyboard.conf).
- After reboot I got layout selector on login menu. Also I could type in any application on both languages and there is layout selector on the taskbar.
- But in system settings in Manjaro KDE (Input Devices > Keyboard > Layouts) I could only see russian (RU) layout is presented.


At this point I don't know what to do next since I don't know if it's Manjaro or KDE's problem from which config it get Layout settings. Or maybe for Manjaro usage of /etc/X11/xorg.conf.d/00-keyboard.conf is not logical at all.
At my standalone desktop installation (Manjaro KDE) I got:
- 'ru' in  /etc/default/keyboard 
- 'us' in /etc/X11/xorg.conf.d/00-keyboard.conf
And in (Input Devices > Keyboard > Layouts) it have both layouts present.


PS: In Calamares the source file responsible for KB layouts is src/modules/keyboard/SetKeyboardLayoutJob.cpp

**Comment by WerySkok** [comment] 2020-07-24 18:53
Current workaround I use is installing system with English layout and then changing layout in DE settings after installation.

**Comment by adriaandegroot** [comment] 2020-09-09 13:38
Point 1 from @Jedi-Mind-Tricks is particularly relevant: the username field needs to be ASCII in all the systems I know of. There is [systemd documentation](https://systemd.io/USER_NAMES/) that tries to go over the variants and versions that are possible -- that said, I just had a friend create a user with a German ß in the username, and `adduser` accepted that.

There's **four** (maybe five) relevant things here:
- the "live" keyboard layout; this is updated with `setxkbmap` which supports multiple layouts. We could do a suitable call with two layouts; to do so a "is-this-latin" method would be needed to pick out the ones that can type latin directly, and if the keyboard layout is not latin-capable, then add a second *us* layout. Choosing what scheme to use for switching groups, though, is more tricky. I'm inclined to set it to `grp:alt_shift_toggle` if no *grp* has been set yet; telling the user that is possibly difficult.
- the vconsole keyboard layout; this should probably be a latin-compatible layout because you're interacting first with login, which is going to need your username. Password is complicated though: ЭтоСлон is a fine password, and the UTF-8 sequence can be run through whatever hashing is needed for the password. It would be really awkward to have an ASCII username and a non-ASCII password.
- the X.org default layout can be written with multiple layouts, as @kkofler linked to the docs there
- For Debian(?) purposes there is also `/etc/default/keyboard` where I'm not sure if that supports multiple layouts
- (maybe) For GRUB with disk encryption, the layout might also be *us* at boot time

**Comment by adriaandegroot** [comment] 2020-09-29 18:42
(See any other #hacktoberfest2020 ticket in the Calamares repository for Procedural information)

## Functional

- [ ] *KeyboardPage::onListVariantCurrentItemChanged()* in `KeyboardPage.cpp` is one of the places that invokes *xkbmap*. You may need to look for more places.
- [ ] Ideally, this would migrate to `Config.cpp` as a method of the config-object (so that it can also be called from QML), where it would take a parameter for variant and layout. There is some timer trickery going on to avoid running xkbmap too often if the user is arrow-keying through the list.
- [ ] With xkbmap it is possible to query settings as well: if there's no group-switching a group-switcher can be added right there
- [ ] Some way of deciding which layouts are ASCII-capable is needed
- [ ] The invocation for xkbmap should be extended with a second layout and options for group switching -- the latter only if nothing is set yet (which you can query from xkbmap as well)

**Comment by adriaandegroot** [comment] 2020-10-02 08:57
Artem Grinev is working on this.

**Comment by Pointedstick** [comment] 2020-10-24 18:35
Does Artem have a GitHub account? I'd like to follow up with him.

**Comment by adriaandegroot** [comment] 2020-10-28 10:43
That's @LordTermor . Initial work has landed for this.

**Closed** 2020-10-28 16:11 UTC
Labels: bug, hacktoberfest, help: wanted

**Comment by Pointedstick** [comment] 2020-10-28 18:06
Hooray!
