### ISSUE TITLE
Toggle log not working if calamares was closed once

### ISSUE THREAD

**Issue by Neo-29** [calamares/calamares#2001] opened 2022-06-28 15:39 UTC
**Describe the bug**
If calamares is closed once, the toggle log won't reinitialize and won't show the logs

**To Reproduce**
1. Start calamares 
2. Close or cancel
3. Re-open calamares and start installation 
4. Toggle log will just show the previous inputs only 

**Expected behavior**
Show logs of the actual installation 

**Screenshots and Logs**

**Additional context**

**Comment by Neo-29** [comment] 2022-06-28 16:41
1 last version of calamares
2 archlinux ( my own installer)
Logs prompted by the button toggle log.

What else do you need?

Have you tried the steps i gave?

Tks

**Comment by killajoe** [comment] 2022-06-28 16:46
at least a link to the configs used or to the ISO itself. 
And if you have it the debug log from Calamares /var/log/Calamares.log

**Comment by killajoe** [comment] 2022-06-28 16:51
And i see that the log is working here after closing calamares before.. it only "hangs" till you scroll it down again. 
Same happens when you scroll back on the logs it will not roll anymore.

**Comment by demmm** [comment] 2022-06-28 18:32
What is needed is clearly spelled out in https://calamares.io/issues/

Issue reports wishing to ignore those basics will automatically be closed, help can't be offered any other way.

**Closed by demmm** 2022-06-28 18:32 UTC
Labels: help: needs-feedback

**Comment by Neo-29** [comment] 2022-06-28 20:23
![image](https://user-images.githubusercontent.com/90937180/176277919-56c010f7-3677-46bf-9aaf-01c890a5eae5.png)

Hope this is clearer ....

**Comment by Neo-29** [comment] 2022-06-28 20:24
> What is needed is clearly spelled out in https://calamares.io/issues/
> 
> Issue reports wishing to ignore those basics will automatically be closed, help can't be offered any other way.

No nothing is prompted even if I scroll down

**Comment by Neo-29** [comment] 2022-06-28 20:25
> And i see that the log is working here after closing calamares before.. it only "hangs" till you scroll it down again. Same happens when you scroll back on the logs it will not roll anymore. https://youtu.be/WVbaCHUMMgc

No ...Nothing happens even if I scroll down

**Comment by adriaandegroot** [comment] 2022-06-28 21:34
Can't reproduce, and, as demmm has pointed out, the more information you can provide, the better. There is **one** thing that comes to mind, possibly relevant: the log is read by a thread with the lowest priority, and the unpacking phase stresses a lot of processes and threads. If you have a single- or dual-core CPU, it might be overwhelmed and never get around to the update thread.

**Comment by Neo-29** [comment] 2022-06-28 21:57
> Can't reproduce, and, as demmm has pointed out, the more information you can provide, the better. There is **one** thing that comes to mind, possibly relevant: the log is read by a thread with the lowest priority, and the unpacking phase stresses a lot of processes and threads. If you have a single- or dual-core CPU, it might be overwhelmed and never get around to the update thread.

Tks for the reply.
I don't think it's linked to thread here.
I used to start the installer with the debug mode with no issues at all (even if I close calamares and re-open it).
This is really strange...
I may point out I'm using a virtual machine ( qemu or virtualbox) here.

I would give more informations if i could of course
