### ISSUE TITLE
Crash in partition module

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1195] opened 2019-07-05 10:45 UTC
I am testing 60 iso's these days for ArcoLinux. They were all build using the 3.2.10 and have a specific config for every desktop etc... The configuration files are the only difference and that is often just some images and a text.

It only happens sometimes (like very rarely) that we see this error. It was also particularly frustrating as it sometimes happens that when you immediately restart calamares in debugging via the terminal than it installed just fine... like calamares had changed something to the disk/partitions.

I had this one time opportunity to record all the data since this time the error occurred a second time.

This is the popup.

![20190705_122245](https://user-images.githubusercontent.com/36679406/60717333-cfc45b00-9f21-11e9-8f76-5b0ad15fd393.jpg)

And this is the corresponding log.
https://pastebin.com/w1AnVAGj

Solution:
1. gparted - delete all partitions and install again (no swap set)
2. manual install via calamares - choose gpt or mbr and start installation

I tried option 1 and the OS installed normally.

**Comment by adriaandegroot** [comment] 2019-07-07 20:39
See #1174 and #1170. I think this is yet another victim of the sfdisk backend being sensitive to things changing the disk outside of kpmcore itself.

**Comment by abucodonosor** [comment] 2020-02-16 17:27
Duplicate of #1174 and #1170

**Closed by abucodonosor** 2020-02-16 17:27 UTC
Labels: M duplicate, N kpmcore4, bug
