### ISSUE TITLE
If you connect to the Internet after calamares considers that you do not have Internet, calamares itself will automatically connect to the Internet, but the net install module will still say that there is no Internet

### ISSUE THREAD

**Issue by Boria138** [calamares/calamares#2153] opened 2023-05-29 11:08 UTC
**Describe the bug**
While I was turning on wi-fi in KDE because of their wallet, the timeout for checking the Internet ended and Calamares wrote that the Internet was needed to install the distribution, then when I connected to the Internet, the netinstaller module did not allow me to select packages, swearing at the lack of Internet, I had to close and open Calamares

**To Reproduce**
It is enough to turn on the Internet after the timeout is over

**Expected behavior**
the network installation is also available for viewing on the Internet

**Comment by demmm** [comment] 2023-05-29 13:32
As asked for many times now, follow proper procedure when filing issue reports, the least needed is what OS used, which Calamares version and the output when running Calamares (installation.log).
https://calamares.io/issues/
Fully use the issue template.
Since no version mentioned, closing now as duplicate of https://github.com/calamares/calamares/issues/1106 and fixed in 3.3.
Open a proper report if this is an issue with the 3.3 branch/Calamares alpha 3.3 release.

**Closed by demmm** 2023-05-29 13:32 UTC
