### ISSUE TITLE
Calamares closes LUKS and/or LVM device before trying to install to it

### ISSUE THREAD

**Issue by michael-db** [calamares/calamares#1564] opened 2020-11-02 17:35 UTC
Distribution lubuntu 20.04, but, as far as I can tell, this is a Calamares issue.
Calamares 3.2.20.

Before running Calamares, I have a luks-encrypted lvm partition opened
```
lsblk
...
└─sda5                8:5    0   186G  0 part
  └─cryptvol        253:0    0   186G  0 crypt
    ├─cryptvg-swap  253:1    0    16G  0 lvm
    └─cryptvg-linux 253:2    0   160G  0 lvm
```
I start Calamares, select manual partitioning, tell it that the root partition is to go /dev/cryptvg/linux (btrfs), get to the end of the procedure, it asks for confirmation to "Install Lubuntu on btrfs system partition /dev/cryptvg/linux", I say, Yes, please.

It crashes, complaining as follows:
```
Command '['btrfs', 'subvolume', 'create', '/tmp/calamares-root-2_q1ieog/@']' returned non-zero exit status 1.
None

Traceback:
File "/usr/lib/x86_64-linux-gnu/calamares/modules/mount/main.py", line 166, in run
    mount_partition(root_mount_point, partition, partitions)

  File "/usr/lib/x86_64-linux-gnu/calamares/modules/mount/main.py", line 94, in mount_partition
    subprocess.check_call(['btrfs', 'subvolume', 'create',

  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
```

From the log, it is "successfully" sabotaging itself by closing the device before it tries to write to it:
```
     ClearTempMountsJob finished. Here's what was done:
 ""
08:50:48 [8]: [JOBQUEUE]: Progress for Job[ 1 ]:  0 % completed
08:50:48 [8]: [JOBQUEUE]: Progress Overall:  2.32558 % (accumulated) +  0 % (this job) =  2.32558 % (total)
08:50:48 [6]: virtual void Calamares::JobThread::run()
     Starting job "Clear mounts for partitioning operations on /dev/sda"  (there are 32  left)
08:50:48 [6]: QStringList getPartitionsForDevice(const QString&)
     Reading from "/proc/partitions"
08:50:49 [6]: virtual Calamares::JobResult ClearMountsJob::exec()
     ClearMountsJob finished. Here's what was done:
 "Successfully closed mapper device /dev/mapper/cryptvg-linux.\nSuccessfully closed mapper device /dev/mapper/cryptvg-swap.\nSuccessfully closed mapper device /dev/mapper/cryptvol."
```

For me, this installer is broken. Is there any workaround, or must I get another distribution which does not use the Calamares installer?

**Comment by abucodonosor** [comment] 2020-11-02 19:18
LVM support is broken, in fact, I have no idea why is there right now.

https://github.com/calamares/calamares/issues?q=is%3Aissue+is%3Aopen+lvm

Aso Ubuntu and luks is such a thing, even without LVM.

@adriaandegroot 

can we make LVM optional, until someone fixes all bugs?

**Comment by kkofler** [comment] 2020-11-02 21:38
The main issue here is that the `ClearMountsJob` unmounts everything and prevents installing to the LUKS device, LVM is not really the issue here.

**Comment by archmunky** [comment] 2020-11-15 15:46
I can confirm this is also an issue with 20.04 versions of KDE Neon. I had to install an 18.04 version and upgrade from there.

**Comment by adriaandegroot** [comment] 2020-11-24 16:44
I'd need a scenario from @archmunky  or @michael-db how to get the system into this state in the first place (because I'm very much not-a-LVM-user). Then it becomes testable (for me).

There's a function `ClearMountsJob::getCryptoDevices()` which collects entries  from `/dev/mapper` to close; there's **specific** code handling Fedora, live-image-mapper-entries, so it wouldn't be that strange to add similar handling for "the LVM target of the installation of root is going to be on an existing LVM thingy".  I expect that will open the doors to more corner cases, but we can deal with them when they show up.

**Comment by archmunky** [comment] 2020-12-09 15:13
I have much the same process installing new KDE Neon on LVM-on-encrypted-LUKS partitions (lnx is my lvm vg). Here is my process:

`
# cryptsetup luksOpen /dev/sdb2 sdb2_crypt
# vgchange -ay
# lvcreate -n neon -L 42G lnx
# mkfs.ext4 /dev/lnx/neon (or /dev/mapper/lnx-neon) -- also use btrfs in fedora testing

// install as normal on new neon partition but do not reboot
// chroot to new install
// create the crypttab if necessary and update fstab
// update initramfs
// update grub
`

I end up with the same error message. Running lvs doesn't show any open logical volumes and sdb2_crypt is not open/unlocked.

The only workaround I've found for Neon is to use the iso from 20200716 based on 18.04 using an older version of Calamares and then just upgrading to the latest version.

**Comment by adriaandegroot** [comment] 2020-12-09 19:02
Thanks @archmunky  (and, now I look back at it, @kF13Ld ), that looks like an understandable set of steps to follow (is that "older Neon iso" really using Calamares, though?)

**Comment by archmunky** [comment] 2020-12-10 16:09
Good call. It looks like Neon 18.04 was using a skinned version of ubiquity that looks like Calamares. They fully moved to Calamares in the 20.04 release. I will download the latest Neon installer and try to install it in an existing LVM-on-LUKS and see if the issue is still occurring.

**Comment by Rawi666** [comment] 2020-12-12 12:54
I was able to install Neon 20.04 on LVM with LUKS if I removed whole logic in ClearMountsJob.cpp. So I think for now the workaround is to recompile calamares on live iso before installing neon :)
Just for curiosity - why does calamares unmount any volume before proceeding to installation? What's the reason for doing this? I think it should do no harm if during installations there are some unnecessary mounted partitions?

**Comment by NuclearNemo** [comment] 2020-12-13 17:21
I'm seeing the same problem when trying to install Neon 20.04 to a LV, withouth any encryption like LUKS involved. That makes it effectively impossible for me to install Neon on my machine.

I made up a minimal test case to hopefully make it easy to reproduce the problem with something like VirtualBox.

- Create a new VM with sufficient disk space (I chose 10G).
- Boot Neon image on that VM, run
`sudo cfdisk /dev/sda`
- Create a DOS partition table
- Create a single primary partition that can use all the disk space, partition type set to 'Linux LVM'
- Then create a simple LVM setup with one physical volume on the previously created partition, a volume group "myvg" and a single logical volume "mylv", and format it with ext4:
`sudo pvcreate /dev/sda1`
`sudo vgcreate myvg /dev/sda1k`
`sudo lvcreate -l 100%FREE -n mylv myvg`
`sudo mkfs.ext4 /dev/myvg/mylv   #without formating Calamares will try to delete the LV on install (and fail on that instead of file system creation)`
- Start Calamares and set the root partition for the new system to /dev/myvg/mylg, select "Format"
- It will fail with the message that `mkfs.ext4 /dev/myvg/mylv` failed, obviously because Calamares right before deactivated all volume groups on the system so that the path `/dev/myvg/mylv` doesn't exist. Debug output of Calamares shows a message like:
`10:41:56 [6]: virtual Calamares::JobResult ClearMountsJob::exec()`
`    ClearMountsJob finished. Here's what was done:`
 `"Successfully closed mapper device /dev/mapper/myvg--mylv."`

Hope this helps,
Jan

**Comment by kkofler** [comment] 2020-12-13 18:45
Yes, this also affects LVM devices. So all of: LVM only, LUKS only, LVM over LUKS, LUKS over LVM are affected. `clearmounts` wants to unmount all of these.

**Comment by frapell** [comment] 2020-12-17 00:06
@Rawi666 Care to share some steps on how you recompiled calamares? I am having the same issue trying to install on an LVM+LUKS, and while the error I get is different from what is reported here, I believe it is the same...

Here's the bug I reported in KDE issue tracker https://bugs.kde.org/show_bug.cgi?id=430443

**Comment by frapell** [comment] 2020-12-17 15:22
I was able to compile calamares using the instructions from here https://github.com/calamares/calamares/wiki/Develop-Guide#quick-deployment-script and I commented out this line  https://github.com/calamares/calamares/blob/ae09537beaf23b9d73ddde6d175e3c01e869629f/src/modules/partition/jobs/ClearMountsJob.cpp#L310 and then recompiled....

Unfortunately this didn't help and I couldn't install KDE Neon... I used the settings.conf provided here https://github.com/calamares/calamares/blob/ae09537beaf23b9d73ddde6d175e3c01e869629f/settings.conf should I tweak it? or is it ok for installing KDE Neon? (I couldn't find the one Neon uses...)

**Comment by Rawi666** [comment] 2020-12-17 15:34
@frapell 
Here is ClearMountsJob.cpp I used https://pastebin.com/1Uq7UDSQ
Don't even try to think about why I messed up this code because it would be more elegant to complete remove this job in order for neon to install.. ;)
I was just playing with it to understand how it works and this type of dummy returning data in tryXXX method worked. But it would be easier to just remove this job (I don't know why unmounting partitions prior to installing is needed here, but probably there was some reason. I just don't know it).

After recompiling calamares using guide you mentioned remember that script 'deploycala.py' compiles it to /usr/bin/calamares and this file is actually an important wrapper in neon.
So what you need to do is to make a copy of neons original /usr/bin/calamares, recompile calamares using deploycala.py (and remember about replacing ClearMountsJob.cpp) and then
mv -f /usr/bin/calamares /usr/bin/_neon.calamares
cp -f /path/to/backup/original/calamares /usr/bin/calamares

If by any means you don't want to tinker with it and you trust that binaries compiled by a stranger (me :) ) are safe you can just download this archive and
replace binares from 'modified' folder into / - this will replace calamares binaries in a way you don't need to recompile it.
Here is the link for binaries I recompiled and used for installing kde neon in virtualbox to install it on encrypted lvm
https://1drv.ms/u/s!AgDoERf-69v_ifRqe9xTNsIveDWeSg?e=i2nE2r

**Comment by frapell** [comment] 2020-12-17 15:40
@Rawi666 Thank you ! Will give it a try tonight and report back :)

**Comment by kF13Ld** [comment] 2020-12-18 19:38
@frapell: Thanks for the instructions. But I still don't understand how to get the self-compiled calamares to use the default KDE Neon Live calamares settings. Any hints?

**Comment by frapell** [comment] 2020-12-18 19:43
@kF13Ld Follow @Rawi666 instructions, works like a charm... I haven't replied back yet, because while indeed his instructions do work, it didn't in my case, because I have LVM inside LUKS, and when install finishes, it doesn't setup the needed bits and pieces for the crypto part... I need to do that manually now, and haven't had the time yet

**Comment by kfiresmith** [comment] 2020-12-19 15:22
+1 generally to the topic of providing solid support for custom partitioning that uses both LUKS and LVM.  On KDE Neon 20.04, as others have observed, it's quite broken.

This was my first encounter with Calamares and **love the concept**.  I've been looking for an excuse to provide additional monetary support to KDE, and it looks like while this isn't a KDE project, it is the project of a bunch of KDE devs, so I'd be happy to place a $100 USD bounty of Calamares working to provide LVM and LUKS support, donated into any KDE donation bucket the Calamares devs prefer.

**Comment by frapell** [comment] 2021-01-29 15:41
I promised to write the full details and I forgot, but since I had to do it again yesterday on a new machine, here goes...

You will need to manually create your LUKS partition and configure your LVM, but if you are looking at this ticket, I assume that part is done ;)

After booting the live NEON image
```
sudo cp -R /usr/bin/calamares /tmp/original_calamares
curl -LO https://calamares.io/deploycala.py
python3 deploycala.py
vim calamares/src/modules/partition/jobs/ClearMountsJob.cpp
```

For some reason, calamares would not only unmount all partitions, but also deactivate the LVM... to avoid that, here's a diff with my changes https://pastebin.com/cM0DQtSZ

After applying these changes, recompile:
```
python3 deploycala.py -n -p -i - N
sudo mv /us/bin/calamares /usr/bin/_neon.calamares
sudo mv /tmp/original_calamares /usr/bin/calamares
```

Make sure your LUKS partition is open and the LVM volumes are active and not mounted, and run `sudo calamares`

When install is done, do not reboot, you need to maunally fix the crypttab and initramfs since you don't have a keyfile

You can follow these instructions for mounting all partitions and chroot into your newly installed system https://askubuntu.com/a/88432

After you chroot into your installed system, edit `/etc/crypttab` and replace the `/crypto_keyfile.bin` with `none`
Then, edit your `/etc/default/grub` and fix the `GRUB_CMDLINE_LINUX` with values for your system as follows `GRUB_CMDLINE_LINUX="cryptopts=target=LUKS_NAME,source=/dev/disk/by-uuid/LUKS_ENCRYPTED_DISK_UUID,lvm=LVM_VG"` replacing `LUKS_NAME`, `LUKS_ENCRYPTED_DISK_UUID` and `LVM_VG` accordingly

Once everything is right, run `update-initramfs -k all -u` and when that's done, `update-grub`

If everything went fine, you should now be able to reboot into your new system

**Comment by NuclearNemo** [comment] 2021-01-29 18:05
@frapell Thanks a lot for the detailed instructions!
I tested it on my machine (LVM only, no LUKS, used current Neon unstable image) and managed to patch and compile Calamares. But the installer crashed with a segfault during the step where it copys all files to the target partition - so still no luck for me in installing Neon.

**Comment by frapell** [comment] 2021-01-29 18:14
@NuclearNemo Any specifics on the error? In my case I was seeing some error related to "bootstrap" and it was related to the VG being deactivated and so not really mounted in the /tmp temp folder

**Comment by NuclearNemo** [comment] 2021-01-29 21:42
@frapell  I didn't have debug output enabled, seemed there were no other related messages close to the segfault. VGs were activated and the installer was copying the files to the right location. Maybe I'll do another attempt the next days with debug output enabled.

**Comment by NuclearNemo** [comment] 2021-01-30 15:59
Today the Neon installation with the workaround worked without any crash, so I could not reproduce. The only difference was that this time I didn't specify any mountpoints in addition to rootfs in the installer. Happy to have finally found a way to install Neon :)

**Comment by thrdroom** [comment] 2021-03-09 13:27
@frapell 
I can't reproduce the way you installed neon.

In my first try, Calamares wouldn't show me the LUKS encrypted boot partition, only the LVM volumes were listed.
In every other try i did after the first one, the step `python3 deploycala.py` crashes the whole VM(live neon) at 13%(anything related geoIP).

Does anyone else has an idea how to achieve LVM on LUKS with Calamares installer/kde neon 20.04?
Thanks in advance

**Comment by frapell** [comment] 2021-03-09 14:15
@thrdroom Mmmhhh, not sure you have the same use case as we... you mention you have a LUKS boot partition, it is not my case, I have a boot partition (Not encrypted) and then an LVM-over-LUKS partition where I have my root, home, etc partitions...

If you want to have full disk encryption (Including /boot) you should just use the calamares UI to do that, and should work fine...

**Comment by Jorgen-P** [comment] 2021-04-09 07:45
My usual solution is to install Ubuntu using debootstrap. It should be doable for KDE Neon as well. I'm not sure any installer for any Ubuntu version or derivative has worked with custom LVM on LUKS for me, at best it allows the use of premade volumes (which usually means manually fixing something in fstab/crypttab). Some crash, some don't show the option, sometimes both. I just tried out neon (neon-user-20210401-0944, calamares 3.2.29) in a VM and calamares crashed. Also it would not rescan the disk when going back and forth, making troubleshooting way slower.

**Comment by NoxInmortus** [comment] 2021-05-20 09:46
Hello, this issue has been open since November 2020, anyone working on it ?

**Comment by archmunky** [comment] 2021-05-22 00:35
The only way I can get Calamares-based installers to work on my LVM system is to have a terminal running an infintite for loop that repeatedly calls "vgchange -ay" until the installation is completed.

**Comment by archmunky** [comment] 2021-06-17 02:57
Further note: the command to keep running "vgchange -ay" is run the following in a root terminal:

```
while true
do
vgchange -ay
done

```
and one more note: you much precreate the lvm logical volume and format it before install. do not tell calemares to format the logical volume because that causes a crash.

Has there been any progress on a permanent fix for this problem?

**Comment by xpseudonym** [comment] 2021-08-13 07:16
> The only way I can get Calamares-based installers to work on my LVM system is to have a terminal running an infintite for loop that repeatedly calls "vgchange -ay" until the installation is completed.

@archmunky thanks! But, you don't mention LUKS and now I assume you had no LUKS because I had no luck with LUKS (sorry, couldn't resist).
Installing from Debian Buster live to existing LVM on LUKS I was succesful until rebooting when I was dropped to the initramfs shell instead of a password prompt. From there I was able to run `cryptsetup open` on my luks partision but got stuck there with no lvm2 tools - `vgchange -ay` no file or directory.
Is there any way to make `vgchange` available in from within initramfs shell? Once my lvm volumes are available I figure I'll get booted and be able to `update-initramfs` to get a working system boot.
Thanks.

**Comment by xpseudonym** [comment] 2021-08-13 07:20
> The only way I can get Calamares-based installers to work on my LVM system is to have a terminal running an infintite for loop that repeatedly calls "vgchange -ay" until the installation is completed.

@archmunky thanks! But, you don't mention LUKS and now I assume you had no LUKS because I had no luck with LUKS (sorry, couldn't resist).
Installing from Debian Buster live to existing LVM on LUKS I was succesful until rebooting when I was dropped to the initramfs shell instead of a password prompt. From there I was able to run `cryptsetup open` on my luks partition but got stuck there with no lvm2 tools - `vgchange -ay` no file or directory.
Is there any way to make `vgchange` available in from within initramfs shell? Once my lvm volumes are available I figure I'll get booted and be able to `update-initramfs` to get a working system boot.
Thanks.

**Comment by xpseudonym** [comment] 2021-08-13 12:47
> @archmunky thanks! But, you don't mention LUKS and now I assume you had no LUKS because I had no luck with LUKS (sorry, couldn't resist).

Well, I don't know if @archmunky used LUKS or not, but after abandoning Debian and attempting the same LVM on LUKS install with the closely related PureOS I can report 100% success - including formating `/` and `/boot` partitions! I almost fell off my chair when I was presented with a password prompt on reboot! The only slight blemish was needing to force shutdown after being prompted to remove install media on the final reboot.

I don't want to get too ranty, but this success was after spending literally days attempting this setup following first @archmunky's instructions and then these instructions https://www.blakehartshorn.com/installing-debian-on-existing-encrypted-lvm/ which repeatedly failed on either base install or software install with Debian.

So, well done Purism!
Thx

**Comment by archmunky** [comment] 2021-08-14 03:30
actually, yes I do use LVM-on-LUKS. the trick is to continually be running "vgchange -ay" on a terminal during the install process, specifically when you press "Begin Installation" and it starts setting up the disk layout. Then the installation works correctly.

**Comment by xpseudonym** [comment] 2021-08-15 11:35
Yup, that's just what I did with PureOS, but not so with Debian - Debian installers (plural) were completely broken as above https://github.com/calamares/calamares/issues/1564#issuecomment-898434427.  It is a *very good* trick!  I ran gnome disks at the same time and you can see the mounted lvm partitions flicker as calamares unmounts them and your script remounts them - very satisfying to watch :)

But, it's not quite all roses in my garden, I've discovered that the swap partition wasn't set up.  See following.  Any suggestions?
```
$ free -h
               total        used        free      shared  buff/cache   available
Mem:           7.7Gi       1.9Gi       4.0Gi       408Mi       1.8Gi       5.2Gi
Swap:             0B          0B          0B
```
```
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a device; this may
# be used with UUID= as a more robust way to name devices that works even if
# disks are added and removed. See fstab(5).
#
# <file system>                                 <mount point>   <type>  <options>                               <dump>  <pass>
UUID=2F29-3128                                  /boot/efi       vfat    defaults,noatime                        0       2
UUID=b07d1afd-9f3f-44a5-a263-1aa963fc3fd3       /boot           ext4    defaults,noatime,discard                0       2
UUID=4bfefbd7-538e-46b2-bcf9-196f63c33362       /home           ext4    defaults,noatime                        0       2
UUID=97ee69ac-0ef9-4709-a860-090b79d1afd3       /opt            ext4    defaults,noatime                        0       2
UUID=e7f4c43b-c80f-4e92-bf30-bfe5f2067743       /               ext4    defaults,noatime                        0       1
UUID=5057c451-db29-4b74-ba22-07182b7c5ab2       /usr/local      ext4    defaults,noatime                        0       2
UUID=e5272990-d0f4-4003-bd1d-3899b337bb06       /var            ext4    defaults,noatime                        0       2
```
```
$ ls -lh /dev/mapper
total 0
crw------- 1 root root 10, 236 Aug 15 10:24 control
lrwxrwxrwx 1 root root       7 Aug 15 10:24 luks-ad83fc7d-28ff-482f-a874-b8fe1934d569 -> ../dm-0
lrwxrwxrwx 1 root root       7 Aug 15 10:24 VG_morgansmachine-LV_morgansmachine_home -> ../dm-6
lrwxrwxrwx 1 root root       7 Aug 15 10:24 VG_morgansmachine-LV_morgansmachine_opt -> ../dm-3
lrwxrwxrwx 1 root root       7 Aug 15 10:24 VG_morgansmachine-LV_morgansmachine_root -> ../dm-1
lrwxrwxrwx 1 root root       7 Aug 15 10:24 VG_morgansmachine-LV_morgansmachine_swap -> ../dm-4
lrwxrwxrwx 1 root root       7 Aug 15 10:24 VG_morgansmachine-LV_morgansmachine_usr--local -> ../dm-5
lrwxrwxrwx 1 root root       7 Aug 15 10:24 VG_morgansmachine-LV_morgansmachine_var -> ../dm-2
```
```
$ ls -lh /dev/disk/by-uuid
total 0
lrwxrwxrwx 1 root root 10 Aug 15 10:24 190da258-fb28-4894-bebe-881db0334225 -> ../../dm-4
lrwxrwxrwx 1 root root 10 Aug 15 10:24 2F29-3128 -> ../../sda1
lrwxrwxrwx 1 root root 10 Aug 15 10:24 4bfefbd7-538e-46b2-bcf9-196f63c33362 -> ../../dm-6
lrwxrwxrwx 1 root root 10 Aug 15 10:24 5057c451-db29-4b74-ba22-07182b7c5ab2 -> ../../dm-5
lrwxrwxrwx 1 root root 10 Aug 15 10:24 97ee69ac-0ef9-4709-a860-090b79d1afd3 -> ../../dm-3
lrwxrwxrwx 1 root root 10 Aug 15 10:24 ad83fc7d-28ff-482f-a874-b8fe1934d569 -> ../../sda3
lrwxrwxrwx 1 root root 10 Aug 15 10:24 b07d1afd-9f3f-44a5-a263-1aa963fc3fd3 -> ../../sda2
lrwxrwxrwx 1 root root 10 Aug 15 10:24 e5272990-d0f4-4003-bd1d-3899b337bb06 -> ../../dm-2
lrwxrwxrwx 1 root root 10 Aug 15 10:24 e7f4c43b-c80f-4e92-bf30-bfe5f2067743 -> ../../dm-1
```

**Comment by archmunky** [comment] 2021-08-15 16:45
It unmounts your swap partition too? That's odd. During the affected install, I'd make sure that your swap is available and mounted, then add "swapon /dev/sd##" to the script that continually activates all logical volumes.

**Comment by DanScharon** [comment] 2021-08-16 07:01
@xpseudonym yeah, it was the same for me as I also set up swap as a logical volume. As @archmunky said:
> and one more note: you much precreate the lvm logical volume and format it before install. do not tell calemares to format the logical volume because that causes a crash.
So I didn't choose formatting for the swap volume but then Calameres won't set it up as swap. But that's no problem, you can just set up the swap volume afterwards

**Comment by xpseudonym** [comment] 2021-08-16 14:38
@DanScharon Thanks Dan
> But that's no problem, you can just set up the swap volume afterwards

Done :)

**Comment by archmunky** [comment] 2021-09-06 02:37
Sadly even my continual vgchange running isn't working on the latest neon installer.

**Comment by archmunky** [comment] 2021-09-06 02:59
actually, it still works if root is ext4. if I try to install root to btrfs then it fails regardless of the vgchange. so maybe there are two bugs.

**Comment by apt-ghetto** [comment] 2021-09-06 14:27
Isn't LVM kind of superfluos with BtrFs?

**Comment by archmunky** [comment] 2021-09-07 15:18
I run multiple linux distros on my LVM-LUKS encrypted for security.

**Comment by vpal** [comment] 2021-10-21 20:08
A workaround that worked for me during a Manjaro - Gnome installation with `crypt > lvm > btrfs` setup:

1. When you activate your encrypted LUKS device call it live-WHATEVER this way it will not be deactivated.
2. Run the above suggested: `while true; do vgchange -ay; done`

I assume this is why the workaround works: https://github.com/calamares/calamares/blob/calamares/src/modules/partition/jobs/ClearMountsJob.cpp#L306
I'm not sure if the while loop is needed, have not tried without it maybe having the "right" naming is enough.
I did the installation twice so it likely is a stable solution.

**Closed** 2021-11-02 14:42 UTC
Labels: hacking: in-progress

**Comment by felsgaertner** [comment] 2021-11-29 20:10
I did a fresh install based on **debian-live-11.1.0-amd64-cinnamon+nonfree.iso** using the workaround mentioned in https://github.com/calamares/calamares/issues/1564#issuecomment-862877556.

Calamares regonized the volume group correctly, but Debian refused to boot afterwards.

The reason was simple and surprising: Calamares did not install the volume manager. To solve this, I needed to 
~~~ shell
sudo apt install lvm2
~~~
to get this missing component into the system.

**Comment by adriaandegroot** [comment] 2021-11-30 10:32
@felsgaertner that's more of a distro-issue than anything else;either it should always install the relevant tools, or should react to specific partitioning types. It's worth filing a downstream issue, and/or figuring out if a *shellprocess* or such bit in Calamares can do the job.

You can do an installation in a VM with `calamares -d` -- then you have an expanded log, and also the Calamares debug-window to work with -- to figure that out. If you **do** have specific findings, please open new issues rather than commenting on older, closed ones.

**Comment by ilmagico** [comment] 2024-02-20 22:04
Why is this issue closed? It doesn't look fixed, at least based on my experience just now with EndeavourOS (Calamares 23.11.2.4-1, based on their website).
I tried searching for other open issues, but while I see some related to LUKS (e.g. #1712), or maybe #1130 LUKS-on-LVM (LUKS inside a LVM volume), I don't see any about LVM-on-LUKS (LVM inside a LUKS partition), the closest is #1847.  It's also still a top web search result for "calamares lvm luks", so I figured I'll post this here for others.

Anyways, looking at the actual PR with the fix, it seems it only accounts for LVM volumes, but not LUKS. In my case, I was trying perform an installation over a LVM-on-LUKS setup that I created manually, and sure enough `ClearMountsJob` kicks in and unmounts everything.

The only workaround(s) that almost worked was to follow the instructions in [this comment](https://github.com/calamares/calamares/issues/1564#issuecomment-948979591):
* open the luks device with a `live-WHATEVER` name
* Run `while true; sleep 0.1; vgchange -ay; done` (I added a 0.1s sleep to avoid overloading the processor)

Even then, the bootloader installation failed because calamares didn't realize the LVM volumes were inside a luks partition, so it didn't setup the encryption  in grub. I had to patch calamares' config files (somewhere in `/etc/calamares/modules`, going by memory, forgot exactly where) on the live system to manually set `GRUB_ENABLE_CRYPTODISK=y`, that made it finish, but didn't set up a `/crypto_keyfile.bin`. Would've probably worked without this patch if I made a separate, unencrypted `/boot` partition, or if I could use systemd-boot. 

By the way, I had tried the latest Manjaro calamares installer as well, and I observed the same issue, but didn't try to see if the workaround works there as well (my guess is, it probably does).

**Comment by DonKatsu** [comment] 2024-03-07 10:46
Same with my recent experience trying to install to LVM on LUKS with CachyOS.
calamares -v reports `calamares 3.3.0.20240304-c4d26ca2-dirty`

To start, the installer will crash when attempting to create a volume group if I try to do the LVM on LUKS process through it on a blank drive. #2295?
When setting up the LVM group and volumes inside LUKS myself, then selecting the mount points in the installer with the LVM open, the installer closes the LVM and such then appears to be installing packages to the root partition. But it doesn't actually.
I somehow had managed to get it to work without knowing about that vgchange script, perhaps by having the KDE partition manager open? But when I tried to install a second time and kept failing, I found this issue and the script did the job.
After it finished, Done was clicked, and a boot was attempted, it didn't ask for the password and timed out dropping to an emergency shell. calamares didn't write the encrypt hook to /etc/mkinitcpio.conf. So an arch-chroot was needed to add and regenerate that. After that it booted no problem.
In my case I'm using systemd-boot for my bootloader.

**Comment by DIGist** [comment] 2024-03-21 02:14
I too am experiencing this problem.

**Comment by dalto8** [comment] 2024-03-27 11:08
First, this isn't bug.  Calamares is deliberately unmounting block devices prior to starting the install execution.

Could support be added to allow installing to a manually opened luks device?  Yes, it is possible.  However, it would take two things:
* We would have to think through the downsides of not unmounting and think through mitigations for those issues
* Someone would have to sign up and be interested in doing this work

Lastly, I think we would need to think about if removing that is even really the right thing.  For example, why do people want to manually unlock and mount a luks device in the first place?  Is it to work around some other limitation in the installer?  If so, it could make more sense to spend time on removing that limitation instead.

**Comment by michal-bultrowicz-hiauto** [comment] 2024-03-27 11:23
> Lastly, I think we would need to think about if removing that is even really the right thing. For example, why do people want to manually unlock and mount a luks device in the first place? Is it to work around some other limitation in the installer?

I do that because it's not possible to have a storage setup that fits me. I have one laptop set up with LVM containing two Linux distros, all in a LUKS container. And Calamares almost supports that. It allows me to pick the partitions I want and will install almost correctly if I use the hack mentioned above. I just need to tweak the Kernel options for LUKS.

>  If so, it could make more sense to spend time on removing that limitation instead.

I think detecting that LUKS or LVM were picked so that the setup doesn't unmount is easier to implement than handling all of the cases that people might have. A warning could be displayed somewhere, e.g. "you've chosen to install into custom partitions, the installer won't unmount anything".

**Comment by kkofler** [comment] 2024-03-27 11:34
Doing this kind of special-casing is inconsistent (violates the principle of least surprise) and a hack.

The proper fix is for Calamares to handle LVM over LUKS correctly, not a "don't unmount" hack that only papers over the problem.

**Comment by butla** [comment] 2024-03-28 19:44
@kkofler I don't know the code of Calamares. But from the outside I could argue, that screwing up the user's explicitly selected manual mounts is also violates the principle of least surprise ¯\_(ツ)_/¯ And the feature of "unmount always everything" seems misguided given that you essentially need to break it with a hack (keeping mounts busy to "protect" from an unmount) so that the setup actually carries on and does its job.

I think it's a fuzzy issue :) And, of course, I'm grateful for this useful software provided to me without a charge :)

Just leaving this piece of opinion here.

**Comment by archmunky** [comment] 2024-04-07 18:42
Here is my use case and why I feel bad every time I see Calamares. I have my entire disk encoded using LVM-on-LUKS. The LUKS encryption protects all data on the drive and the single large LVM container allows me to easily change the size of my logical volumes as needed. So I do need to unlock the existing LUKS to be able to install a new system. This has only been a problem on Calamares; other installers don't have this issue. If I hadn't discovered the "busy hack" using "vgchange -ay" above, I would never be able to install an OS that uses Calamares.

Again I have to ask: why is Calamares unmounting all drives? What am I missing?

**Comment by NuclearNemo** [comment] 2024-04-12 13:21
I can still reproduce the bug with current Kubuntu 24.04 daily images, when a) target for '/' is on a LV and b) no partition is marked for being formatted. The bug does not happen for me if there is at least one partition or LV being formatted (e.g. formatting the EFI System partition is sufficient).

For more detailed instructions how to reproduce see the downstream bug report:
https://bugs.launchpad.net/calamares/+bug/2061123

**Comment by dalto8** [comment] 2024-04-12 13:29
> I can still reproduce the bug with current Kubuntu 24.04 daily images, when a) target for '/' is on a LV and b) no partition is marked for being formatted. The bug does not happen for me if there is at least one partition or LV being formatted (e.g. formatting the EFI System partition is sufficient).
> 
> For more detailed instructions how to reproduce see the downstream bug report: https://bugs.launchpad.net/calamares/+bug/2061123

This looks like a different issue than what is being discussed here.

**Comment by mormegil-cz** [comment] 2024-06-18 11:37
> Lastly, I think we would need to think about if removing that is even really the right thing. For example, why do people want to manually unlock and mount a luks device in the first place? Is it to work around some other limitation in the installer? If so, it could make more sense to spend time on removing that limitation instead.

Right; for me, the idea was to install Manjaro Linux (inside a VM) using LVM and encryption. Whenever I tried to prepare the LVM layout inside the installer, it crashed (_ASSERT: "info" in file /build/calamares5/src/calamares-3.2.62/src/modules/partition/core/PartitionCoreModule.cpp, line 361_). After some googling, I learned (correctly? incorrectly?) that Calamares does not really support LVM installation, and I need to set up everything manually. So, I created the layout manually, started the installer, configured the layout there, everything seemed to run correctly now, until “The installer failed to delete partition”, after which I found out the installer has closed the LUKS partition, so it now obviously cannot write to it, and I discovered this report.

So… for me, the _primary_ motivation is, indeed, not “allow not unmounting”, but “make LVM (+encryption) setup working in the installer”. But I’d be content if the workaround of manual partition preparation would work. (But I think I’d argue that being able to use pre-configured partitions which use encryption, is also a use case which should be supported. (Which means… support re-mounting the LUKS partition (letting the user supply the password) afterwards?))

I was not able to set up LVM with separate /home partition at all, but I was able to install Manjaro on a LVM-managed LUKS-encrypted disk with just one common root LV using the `live-` trick above. (With the added complication that you need to complete the setup for booting from LUKS-encrypted root manually afterwards.)

**Comment by TheRammix** [comment] 2024-08-16 23:02
I have the same issue but I'm not even trying to use LUKS. Just trying to install Neon in LVM partitions. I set up everything separately so that I don't need any changes in this Calamares installer, open it, assign the mount points, and installer crashes with "Couldn't create partition" error.
Why an OS installer is made unable to install it in LVM, which is almost industry standard, is beyond me. This issue is open for a long time, I guess another OS would be a better choice than waiting for this to be resolved OR instead of weird (but possible) workarounds like installing it, rsyncing files to another place, recreating partition structure with LVM from scratch, copying files back. But that's too much of a fuss for such basic purpose, I don't need it THAT much.
