### ISSUE TITLE
Check if destination filesystem is not mounted, give user a warning

### ISSUE THREAD

**Issue by hubslave** [calamares/calamares#902] opened 2018-02-04 15:54 UTC
#### Submission type

  - [ ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

3.1.12, Artix

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

/boot on ext4, / on reiserfs, swap

#### What do you expect to have happen when Calamares installs?

Warning is displayed if any of the partitions cannot be mounted (especially /)

#### Describe the issue you encountered

/ failed to mount for unknown reason, Calamares started copying data to non-mounted folder (Unsquash filesystem 15%) but hang when tmpfs was filled.

```
[  668.772105] Out of memory: Kill process 3604 (calamares) score 73 or sacrifice child
[  668.772111] Killed process 3991 (rsync) total-vm:125600kB, anon-rss:26504kB, file-rss:0kB, shmem-rss:0kB

[  699.287801] Out of memory: Kill process 3604 (calamares) score 89 or sacrifice child
[  699.287810] Killed process 3604 (calamares) total-vm:1527248kB, anon-rss:137792kB, file-rss:0kB, shmem-rss:2192kB
```

#### Steps to reproduce the problem

> …

#### Include the installation.log (usually ~/Calamares/Calamares/Calamares.log, of the user Calamares runs as):

> …

**Comment by abucodonosor** [comment] 2018-02-05 03:34
Please provide an *full* installation log.
Additional a *full* dmesg of that box.

Also -> 'Out of memory' indicates your VM/box has not enough *memory*.

**Comment by hubslave** [comment] 2018-02-07 18:42
I didn't save the log and I'm afraid I don't have time to rerun the install now.
Probably the original issue can and must be fixed, but this is a feature request to add a sanity check to the installer.
Out of memory is only a symptom and can be misleading at first. But the real problem was root not mounted and all files copied to memory (tmpfs?) by installer. If my machine had more memory, it would just hide the problem.

**Comment by demmm** [comment] 2020-02-08 20:22
Closing.  It has been two years since the OP was asked to provide some much needed logs, no further response regarding this for all this time.
Please re-open if you can still reproduce and provide the asked for logs.

**Closed by demmm** 2020-02-08 20:22 UTC
Labels: help: needs-feedback

**Comment by Sakyce** [comment] 2023-01-31 17:21
Tried to install Manjaro GNOME Linux with calamares on a 8GB Surface Pro 4. Calamares get killed by the kernel because out of memory.
