### ISSUE TITLE
Typo in dialog (bios-grub)

### ISSUE THREAD

**Issue by davidak** [calamares/calamares#1894] opened 2022-03-02 15:54 UTC
**Describe the bug**

While testing the [new NixOS install](https://github.com/NixOS/nixpkgs/pull/161788) i found a typo in a dialog.

![Screenshot from 2022-03-01 22-47-55](https://user-images.githubusercontent.com/91113/156396334-869c1b3b-aaf6-48c3-994a-22205c036843.png)

The dialog refers to a flag called `bios_grub`, but it's actually `bios-grub`.

If you agree that this is an error, i would like to contribute a fix. I would replace it in the source code. Hope it works that way with translations.

It's actually correct in the russian translation: https://github.com/calamares/calamares/blob/9ab1667088f05d91614f07bd12f40118ae9f004b/lang/calamares_ru.ts#L2582

**To Reproduce**
1. Use GPT with BIOS system
2. Don't set the `bios-grub` flag
3. See dialog with typo

**Expected behavior**
No typos in dialog texts.

**Comment by adriaandegroot** [comment] 2022-03-02 16:19
Confirmed; the source says this:

```
src/modules/partition/PartitionViewStep.cpp
479:                             << "is a suitable bios_grub partition";
484:        cDebug() << Logger::SubEntry << "No suitable partition for bios_grub found";
599:                                          "<strong>bios_grub</strong> flag enabled.<br/><br/>"
```

A PR to fix this could take two approaches:

- just change those three strings (only one is user-visible, though); this is just three one-character changes
- get the name of the flag from KPMCore, which is also the source of the list-of-flag-names in that dialog; this means replacing the `bios_grub` in the user-visible string by `%1` (or some other number if there are already subsitutions like the product name) and then substituting in the string from KPMCore. That will ensure consistency, but is a little bit more code.

Either change could be PR'ed. Then I'll gripe about some minor things, you'll fix them, and it'll land for whatever next release there is. It'd be nice if you filled in something in `CHANGES-3.2` as well so that credit is given where due.

The roundtrip to fixing-the-translations takes a bit longer though: once the PR has landed, updated strings are pushed to Transifex (this happens usually once per release cycle, when strings change) and then it takes a while for TX to happen; generally updated strings land in a subsequent release. This could be short-circuited by editing the translation source files and adding that to the PR: replacing the source-message with whatever it gets changed to and updating the translated string (either to use `bios-grub` or `%2`) might do the trick, as long as the existing translations are easy-to-spot-the-english-name (e.g. that Russian translation could be updated by anybody).

**Comment by demmm** [comment] 2022-03-02 19:43
All documentation points to bios_grub being the correct way to set this flag, example:
https://www.gnu.org/software/parted/manual/html_node/set.html
So is kpmcore correct in using bios-grub? Introduced here:
https://invent.kde.org/system/kpmcore/-/commit/852c8c8516c20c0034151b7eee5f7497b206ca63

**Comment by davidak** [comment] 2022-03-03 14:20
@demmm that's exactly the question i want to have answered before doing any work that might get rejected.

Maybe you could ask Teo Mrnjavac <teo@kde.org> who did the change in kpmcore?

**Comment by adriaandegroot** [comment] 2022-03-03 21:03
@stikonas this one's for you (whether changing names in KPMCore is the right thing to do or not). @davidak a change to make the message in Calamares use what KPMCore says is the name of the flag, will not be rejected in Calamares. And that's one way to ensure consistency.

**Comment by stikonas** [comment] 2022-03-03 21:25
In terms of KPMcore, it doesn't matter what name we use. It's just arbitrary string now (since we don't use libparted).

Translations would lag if we do change in kpmcore too. So maybe we just use `bios-grub` in calamares?

**Comment by davidak** [comment] 2022-03-04 14:28
>it doesn't matter what name we use

technically that might be true. for quality and consistency it would be good if the frontend uses the same name as the low-level stuff, so issues can be (easier) debugged

but that might be a breaking change and brake a lot of projects, so it would be a hard decision and we might accept imperfection

what is the exact name of the flag that is applied to the partition?

>Translations would lag if we do change in kpmcore too. So maybe we just use bios-grub in calamares?

if i can just edit the translations in this repo and it's synced back to the translation platform, i can change it here

**Comment by stikonas** [comment] 2022-03-04 18:57
> what is the exact name of the flag that is applied to the partition?

We set GPT partition type to `21686148-6449-6E6F-744E-656564454649`. There is no exact name. In fact it's not even a flag, it's partition type.

**Comment by davidak** [comment] 2022-03-05 01:46
I  see.

> Using GNU Parted, you can set this using a command such as the following:
> 
> `parted /dev/disk set partition-number bios_grub on`
> 
> If you are using gdisk, set the partition type to ‘`0xEF02`’. With partitioning programs that require setting the GUID directly, it should be ‘`21686148-6449-6e6f-744e656564454649`’.

Source: https://www.gnu.org/software/grub/manual/grub/html_node/BIOS-installation.html

>`21686148-6449-6E6F-744E-656564454649` (which, when written to a GPT in the required little endian fields, forms the ASCII string "Hah!IdontNeedEFI"

Source: https://en.wikipedia.org/wiki/BIOS_boot_partition#Overview

>With gptfdisk's cgdisk utility, this is accomplished by setting the partition type to `0xEF02` and giving it a label of `gptbios`.

Source: https://wiki.gentoo.org/wiki/GRUB2/en#Partitioning_for_BIOS_with_GPT

So, since the lack of an official name/label/flag, every tool invents their own. This is terrible.

Calamares uses kpmcore to partition disks which flags are modeled after libparted, but replaced underscored by dashes for some reason.

@stikonas I don't know if there is a good reason for this divergence, but could we fix that in kpmcore without breaking everything? Is it just like a "display name" that people can adapt to when it slightly change?

**Closed** 2022-03-15 12:30 UTC
