### ISSUE TITLE
Should we remove LVM support from Calamares?

### ISSUE THREAD

**Issue by dalto8** [calamares/calamares#2343] opened 2024-06-15 19:16 UTC
LVM support in Calamares has many serious issues:
* https://github.com/calamares/calamares/issues/2295
* https://github.com/calamares/calamares/issues/1847
* https://github.com/calamares/calamares/issues/1135
* https://github.com/calamares/calamares/issues/1134
* https://github.com/calamares/calamares/issues/1132
* https://github.com/calamares/calamares/issues/1133
* https://github.com/calamares/calamares/issues/1130
* https://github.com/calamares/calamares/issues/1131

Many of these have been open for years.

Since nobody seems interested in fixing them and LVM support fails more than it works at this point, should we consider removing support until someone has time or interest to fix it?

**Comment by ptr1337** [comment] 2024-06-16 07:25
Sounds good to me. Its better to have the feature not included then having a broken feature.
From our side, we would welcome it.

**Comment by dalto8** [comment] 2024-06-18 12:23
> @dalto8 and @ptr1337 : since the LVM support is not totally broken and is working in many not-publicly-announced cases _(although with some workarounds, i.e. a user may have to keep a couple of terminal tabs with "cd /mnt" and "cd /mnt/boot" to keep them busy & prevent the premature Calamares unmounting of these partitions)_ - removing the LVM support will do more harm than good

What you are talking about is working around the LVM issues manually.

We wouldn't need the broken buttons in the partition UI for that.

**Comment by ram-on** [comment] 2024-06-19 19:37
No. LVM is a popular framework within the Linux community and should not be removed.

Instead the dev(s) should fix the code which has been broken for years.  I fail to understand why this issue has been on going for many years now.

**Comment by ak2766** [comment] 2024-08-31 04:07
I literally cannot work without LVM on Linux!

So, looks like I've been forced off of Ubuntu! The ride has been pleasant for sure, but no LVM is a deal breaker. Unless, is there a switch on the installer (via cli launch) that gives me that CAPABILITY to do as I please?

I could install on one huge 4tb partition, then shrink and repartition after install, but why?

**Comment by ak2766** [comment] 2024-08-31 05:33
OK - maybe I cannot install the os to lvm, but I've figured I can do manual formatting with 512gb for the OS, then leave the rest of the space empty

Once the in installer is done, all I then need to do is exit the installer (no reboot yet into OS) and add lvm manually and make changes to fstab.

After reboot, it all comes up as expected. So maybe there's still some dancing left to be had with Ubuntu!

**Comment by TNTBOMBOM** [comment] 2024-09-21 17:49
> So maybe there's still some dancing left to be had with Ubuntu!

Debian support LVM by default no? if you are interested..

**Comment by jkugler** [comment] 2024-10-25 22:36
No, the LVM support should be left in so it will be aware of LVM so you can do things like this with a partitioner before you install: https://joshuakugler.com/installing-kde-with-lvm-and-luks.html

If we completely removed LVM support, it would be unaware of LVs, and thus you could not set mount points in the installer.

**Comment by ak2766** [comment] 2024-10-26 02:02
@Nurmagoz 
> Debian support LVM by default no? if you are interested..

Unfortunately, I tried Debian in a VM and while it allows creation of volume group at install time, it too crashed when I tried adding a logical volume - same as Ubuntu prior to 24.04!

I believe the only way around this is to partition the drive beforehand (with live gparted cd) then complete the install or as I did  above.

But ultimately, the solution is to fix the main issue.  Hopefully, someone that has the necessary capability to do something about it is bitten hard by this bug/omission that they they go head down bum up in it...

**Comment by jkugler** [comment] 2024-10-26 02:42
@ak2766 See my blog post above. You can install a partitioner before invoking Calamares (if your LiveCD gives you that option).

**Comment by ak2766** [comment] 2024-10-26 06:12
@jkugler - That looks somewhat similar to how I solved it as well.  I'll try that on my next upgrade - Ubuntu 26.04 most likely.

**Comment by jkugler** [comment] 2024-10-26 06:32
@ak2766 Oh goodness...I hope Calamares is fixed by then. :)

**Comment by ak2766** [comment] 2024-10-26 08:00
Based on the bug from 2019 - 5 years ago now - I have a feeling your instructions will still be relevant when 26.04 comes out.  As sad as that sounds, it is the way of opensource and I understand why...

**Comment by killajoe** [comment] 2024-10-26 14:54
A project not changed over 5 years can be called obsolete or not?
Same for broken implementation it could be fixed or removed, if no one is able/willing to fix it, we should remove or disabled at least. May someone able could start reimplement it. 
Same counts for a lot corners on partition module. I would love to see we all start working together to fix the partition module.

**Comment by jkugler** [comment] 2024-10-26 19:04
@killajoe I suppose the ability to *create* LVM, etc. could be removed (for now), but I hope the ability to *use existing* LVM volume groups and logical volumes would remain so the work around in my blog post would still work.

**Comment by erikdubois** [comment] 2024-11-14 08:08
![image](https://github.com/user-attachments/assets/37679dd6-85a9-4b99-8444-10edff8aed54)
It would be a good idea to give the developers a choice to either show or not show the LVM option.

**Comment by hadmut** [comment] 2024-11-23 15:29
Well, I just – again, still with Ubuntu 24.04.1 – stubled upon the problem that I simply can't install Lubuntu (using Calamares) anymore the way I need it and the way it worked for the last 20 years. 

I do need an encrypted machine with an (small) system partition (ext4) and one or more (huge) systems with Filesystems suitable for virtualization and storage, such as ZFS. 

For around two decades, this wasn't ever a problem, all installers were able to deal with that. 

Nowadays we do have Calamares, the first installer in Ubuntu history, which completely fails to perform the task. (It just has this one task ...)

So rather than dropping the LVM support (without offering an alternative), you should rather drop the developers, or Calamares in common, because it causes a severe regression in Linux, and, at the end of the day, more damage than good. 

After all, what should be so difficult about LVM? It's a rather simple thing, well known for over 25 years.  Why, at all, do you bother with maintaining a Linux installer, if the task is too hard?


I hereby propose to give up Calamares and shut the project down, since it never reached full required functionality, and most probably, never will.

**Comment by kkofler** [comment] 2024-11-23 15:41
I have hidden the previous comment. Insulting the developers has never been a productive way to get something achieved. If more insults get posted here, I will have to lock the conversation, limiting it to contributors.

**Comment by hadmut** [comment] 2024-11-23 16:28
Falsely and publicly accusing someone of an offence is itself considered a felony in many countries, including the criminal codes both of Austria (§ 164 StGB) and Germany.

**Comment by kkofler** [comment] 2024-11-23 16:36
Quit the nonsense. I have not accused anyone of a criminal or even administrative-law or civil-law offense. Requesting that the Calamares developers should be dropped from the project or the project as a whole dropped is offensive, and I find it insulting. That does not mean that you have broken any law.

**Closed** 2024-12-24 21:29 UTC
Labels: feature: improvement
