### ISSUE TITLE
Could not unmount target system root /, Unmounting file systems failed 38/38

### ISSUE THREAD

**Issue by skygunner** [calamares/calamares#2381] opened 2024-10-08 12:19 UTC
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
Tried to install artix-xfce-dinit-20240823-x86_64 twice, but failed with the same error. (reboot for the 2nd time installation)
EFI boot, 64bit. 

part of the log (full log link is below).
```shell
2024-10-08 - 08:15:43 [6]:     Starting job "Unmounting file systems…" ( 38 / 38 ) 
2024-10-08 - 08:15:43 [6]: Calamares::JobResult unmountTargetMounts(const QString&)
2024-10-08 - 08:15:43 [6]:     Read 11 entries from "/tmp/calamares-root-0unyaos0/" 
2024-10-08 - 08:15:43 [6]:     .. Running QList("umount", "-lv", "/tmp/calamares-root-0unyaos0/var/log") 
2024-10-08 - 08:15:43 [6]:     .. Target cmd: QList("umount", "-lv", "/tmp/calamares-root-0unyaos0/var/log") Exit code: 32 output:
 umount: /tmp/calamares-root-0unyaos0/var/log: not mounted.
2024-10-08 - 08:15:43 [6]:     .. Running QList("udevadm", "settle") 
2024-10-08 - 08:15:43 [6]:     .. Running QList("sync") 
2024-10-08 - 08:15:44 [1]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
2024-10-08 - 08:15:44 [1]:     ERROR: Installation failed: "Could not unmount target system." 
2024-10-08 - 08:15:44 [6]:     .. - message: "Could not unmount target system." 
2024-10-08 - 08:15:44 [6]:     .. - details: The device '/dev/nvme1n1p5' is mounted in the target system. It is mounted at '/tmp/calamares-root-0unyaos0/var/log'. The device could not be unmounted.
2024-10-08 - 08:15:44 [6]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
2024-10-08 - 08:15:44 [6]:     Calamares will quit when the dialog closes. 
2024-10-08 - 08:15:44 [6]: void Config::doNotify(bool, bool)
2024-10-08 - 08:15:44 [6]:     Notification not sent; completion: failed 
2024-10-08 - 08:15:44 [6]: void {anonymous}::PowerManagementInterface::uninhibitSleep()
2024-10-08 - 08:15:44 [6]:     Sleep was never inhibited. 
```

**To Reproduce**
iso was booted via easy2boot usb boot stick, linux type.
on artix boot screen , choose boot from cd/dvd.
upon installation options, I choose to use offline installation,  install to a dedicated nvme drive, whole drive, 
manual partition as follows:
GPT table
512 MB size, mount point /boot/efi, fs  FAT32 with BOOT flag.
165GB /home btrfs
4GB swap linuxswap
16GB /var xfs
56GB /  btrfs (this is the partition causing error I believe). 
there's about 17MB at the end of the nvme not allocated.

**Expected behavior**
should work 

**Screenshots and Logs**
https://termbin.com/xn89
https://termbin.com/kxa6

**Additional context**

**Comment by demmm** [comment] 2024-10-08 13:17
Is this a report from a distro developer? If so, make sure to check other bug reports regarding this, there have been commits for this since 3.3.7 (latest release is 3.3.9).
If this is a report from an end user, this is probably not the right place to report:
https://calamares.io/issues/
https://calamares.io/issues/#end-users
Best report at your distro, so they can properly update & include the needed fixes.

Will be closed shortly, giving you time to report back whether end user or not.

**Comment by dalto8** [comment] 2024-10-08 13:41
This is a duplicate of https://github.com/calamares/calamares/issues/2366.

It is already fixed.

**Closed by dalto8** 2024-10-08 13:41 UTC

**Comment by skygunner** [comment] 2024-10-11 00:38
in #2366 it shows installation done and the installed system might be working. 

In my case I think its different.

The installer reported installation failed and the result system is not fully function (no bootloader, can manually boot to cli but with varirus errors, the gui does not start up). 
I've also tried to use ext4 instead of btrfs for / and it went through all good. So the problem here is not the installer forgot to unmount root, but it is not doing good with btrfs root. 
I notice btrfs root seems to have different characteristcs as after mounted in another os, the / contains varius folders starting with @ instead of normal linux root directory. This might causing the instllation errors I encountered, as ext4 root is good, btrfs root always failed to install. (on endeavouros btrfs root works for me)

**Comment by dalto8** [comment] 2024-10-11 01:29
From reviewing the logs, it looks like the same issue to me.

The reason EndeavourOS is working is because the fix came from EndeavourOS.  However, since it recently brought upstream and isn't in a release yet, most distros will not have it yet.
