### ISSUE TITLE
bootloader info displayed not matching actual value

### ISSUE THREAD

**Issue by jghodd** [calamares/calamares#2331] opened 2024-05-12 17:14 UTC
I was able to show, beyond any doubt, that the bootLoader variable going into the partition screen (or going out) has not been, and is not, set to the default value displayed on the bootloader menu button on the bottom of the screen - which says that the bootloader will be installed on the mbr of /dev/sda. The value of bootLoader is actually None, not the "/dev/sda" displayed on the menu button. This is either a change in behaviour from previous versions, a bug, or a configuration issue. Or it could even be that a change in your software is incompatible with virtualBox and it no longer recognizes a VBOX hard disk. I'm hoping this is a configuration issue, although I don't remember any setting for a default value for bootLoader.

I do have screenshots of the whole thing. I'll attach them in order.
![Screenshot_20240511_013122](https://github.com/calamares/calamares/assets/17838067/f1e7ccef-3441-4bde-a255-3f8aba43ff96)
![Screenshot_20240511_013305](https://github.com/calamares/calamares/assets/17838067/ddf6fc93-cbe5-4dc6-80c4-696284aca510)
![Screenshot_20240511_013441](https://github.com/calamares/calamares/assets/17838067/e14c8acc-6a39-4e3c-abef-827696769dcc)
![Screenshot_20240511_013519](https://github.com/calamares/calamares/assets/17838067/7610f0f0-7abc-4374-a97c-4c975967bc84)
![Screenshot_20240511_013722](https://github.com/calamares/calamares/assets/17838067/24d90279-f8a0-48c9-917f-78f0f99d76b8)
![Screenshot_20240511_021257](https://github.com/calamares/calamares/assets/17838067/f965a7de-132e-4a78-aafc-111a17c9ff1f)
![Screenshot_20240511_172930](https://github.com/calamares/calamares/assets/17838067/f580bcbb-9ee2-4b49-96d3-e9b21e62673a)

It appears I am missing the one step of returning to the partition screen and setting the bootloader to be installed on the master boot record of /dev/sda, but I do have the screenshots showing after I returned and re-selected what should have already been the default. Once I did this, the bootloader installed (last screenshot).

So, the question becomes, what is happening that might cause a mismatch between the menu button label (the presumed default) and the actual default of None?

Users will go with the assumed default - the one represented by the label on the bootloader menu button. Trying to leave instructions on how to do the 3-step to get the bootloader to set just isn't going to work. The underlying value of bootLoader should be what's on the menu button label (and the menu selection).

This is your code. Not one of my mods is included,other than a couple of config settings that were needed. The partition code is in C++ which , given enough time I could absorb, but *this is your code*. Why is this happening?

**Comment by dalto8** [comment] 2024-05-12 17:16
This is a duplicate of #2318, please don't open duplicate issues.

**Closed by dalto8** 2024-05-12 17:16 UTC

**Comment by jghodd** [comment] 2024-05-12 17:25
I won't open duplicate issues if y'all treat this seriously. I'd be ok with
reopening the one we started with.

Meanwhile, this is your code, not mine. If there is some condition that
could lead to your bootloader menu button being labeled and set correctly
but the underlying bootLoader variable doesn't match, then you're more
likely to figure it out than someone who's unfamiliar with the code-base.
This is your code.
