### ISSUE TITLE
ESP flag not available

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#891] opened 2018-01-07 22:50 UTC
Hi, I'm the maintainer of GeckoLinux, which is based on openSUSE Leap 42.3. Thus far up through Calamares 3.1.11 it can't set the ESP flag on a partition.

![screenshot from 2018-01-07 17-44-51](https://user-images.githubusercontent.com/2692138/34655143-17f9cbcc-f3d3-11e7-969e-c39428b51cd6.png)

![screenshot from 2018-01-07 17-44-29](https://user-images.githubusercontent.com/2692138/34655135-0d9cf492-f3d3-11e7-81ad-03044bb91fef.png)

kpmcore is at 3.0.3 for openSUSE Leap, so I imagine that might be the source of the problem? In that case this bug is invalid, but I wanted to make sure.

**Comment by philmmanjaro** [comment] 2018-01-07 23:14
Most likely a duplicate of https://github.com/calamares/calamares/issues/884

**Comment by philmmanjaro** [comment] 2018-01-07 23:24
**ESP** we support since [v2.1.0](https://github.com/KDE/kpmcore/commit/852c8c8516c20c0034151b7eee5f7497b206ca63). @stikonas any idea why **esp** is not available in SUSE?

**Comment by geckolinux** [comment] 2018-01-08 00:57
With a fresh VirtualBox disk, the "Erase disk" option works and creates a bootable GPT layout. However, when I run the live system again and try to re-install over top of that, Calamares does not offer the "Replace partition" option, only "Erase disk" and "Manual", and the manual option is what you see in the screenshots.

**Comment by stikonas** [comment] 2018-01-08 15:06
@philmmanjaro No idea. the list of available flags is obtained directly from libparted. And I think libparted only checks partition type (MBR or GPT).

**Comment by adriaandegroot** [comment] 2018-01-08 15:21
See also #884

**Comment by philmmanjaro** [comment] 2018-01-08 19:04
@geckolinux: please check if **swap** or so got automounted. See also https://github.com/calamares/calamares/issues/860

**Comment by geckolinux** [comment] 2018-01-09 12:46
@philmmanjaro 
> please check if swap or so got automounted

Thanks, I just checked and there is no swap partition, and nothing else gets automounted.

**Comment by geckolinux** [comment] 2018-01-09 12:49
@adriaandegroot Ah, that looks like the problem:
#884 https://github.com/calamares/calamares/issues/884#issuecomment-354281926

I just successfully installed after manually setting the "boot" flag. (It appears that the "ESP" flag doesn't even exist.)

So I guess the real bug is that it's not offering me any replace partition or automatic resizing options. Should I open a different bug report for that?

**Comment by adriaandegroot** [comment] 2018-01-09 13:04
As for the existence of the ESP flag: Calamares asks KPMCore, which asks the backend for available flags, which usually means asking libparted, .. so if parted isn't telling KPMCore *esp* exists as a flag, it won't be available. I don't think this is a Calamares issue. (I can't figure out if the command-line parted can tell you what flags exist or are available).

So I'm going to close this one.

**Closed by adriaandegroot** 2018-01-09 13:04 UTC

**Comment by geckolinux** [comment] 2018-01-09 13:08
@adriaandegroot  Thanks. I understand that Calamares just pulls the available flags from other components. But I do think this is a fairly significant UI issue, because it makes the user think that the installation will fail without the `esp` flag, when in reality it just needs `boot`.

**Comment by adriaandegroot** [comment] 2018-01-09 13:14
@geckolinux As for missing replace or alongside installation, please check the debugging output, it generally explains why a device is not available:

```
13:43:41 [1]: Removing unsuitable devices: 3 candidates. 
13:43:41 [1]:   .. Removing device with root filesystem (/) on it "/dev/sda" 
13:43:41 [1]: LIST OF DETECTED DEVICES: 
13:43:41 [1]: node      capacity        name    prettyName 
13:43:41 [1]: "/dev/sdb" 10733990400 "ATA VBOX HARDDISK" "ATA VBOX HARDDISK – 10,00 GiB (/dev/sdb)" 
```
.. that's the devices being cleaned up. When selecting a device, you get buttons applicable to your environment. Replace is available if it's going to fit, and you will see output like this:

```
13:43:46 [1]: Required  storage B: 6442450944 "(6GB)" 
13:43:46 [1]: Storage capacity  B: 10737383936 "(9GB)" for ""    length: 20971453 
13:43:46 [1]: Partition "" authorized for replace install. 
```

It's possible you're not getting a replace or alongside because the disk is too small. Keep in mind that Calamares applies several fudge-factors (I think 10% + 500MB) before accepting a partition for replace or alongside installation.

**Comment by adriaandegroot** [comment] 2018-01-09 13:15
@geckolinux Let's deal with ESP in #884, you've explained it there nicely (weird data point: my parted 3.2 can set boot and esp independently on a GPT partition table).

@geckolinux If you check the debug output and don't understand why you don't get a replace or alongside installation option, please file a separate issue.

**Comment by adriaandegroot** [comment] 2018-01-09 13:23
My apologies, I thought boot and esp could be set independently, but further experimentation with parted shows they toggle together -- and I can't get fdisk or gdisk to display flags at all.

**Comment by stikonas** [comment] 2018-01-09 13:25
Oh ok, so it's actually alternative for ESP (probably for compatibility reasons) but very confusing...

**Comment by geckolinux** [comment] 2018-01-09 13:26
@adriaandegroot Very good, I really appreciate the help.

@stikonas  Yes, definitely confusing. I sincerely hate the complexity that (U)EFI and GPT brings to the scene...

**Comment by geckolinux** [comment] 2018-01-09 13:50
@adriaandegroot  OK, upon further investigation it appears that I'm not getting automatic resize or replace partition options due to this same bug with the system not seeing/supporting the `esp` flag.

     08:45:47 [1]: Partition "/dev/sda3" authorized for replace install. 
     08:45:47 [1]: Required  storage B: 6442450944 "(6GB)" 
     08:45:47 [1]: Storage capacity  B: 5467648 "(0GB)" for ""    length: 10679 
     08:45:47 [1]: WARNING: system is EFI but there's no EFI system partition, DISABLING alongside and     replace features.

**Comment by stikonas** [comment] 2018-01-09 15:01
@geckolinux can you check if Partition Manager shows ESP flag?

**Comment by feren** [comment] 2019-05-19 11:12
I'm now getting this issue on my Feren OS 64-Bit ISO after having updated Calamares to the latest version.

**Comment by stikonas** [comment] 2019-05-19 11:21
> I'm now getting this issue on my Feren OS 64-Bit ISO after having updated Calamares to the latest version.

What is the version of kpmcore?

> 
>     * GParted shows 'esp' as a flag option
It would be more useful to know if KDE Partition Manager shows it. That might help us know if bug is in kpmcore of calamares.

> 
>     * Calamares does not let the user set the 'esp' flag in Manual Partitioning

**Comment by feren** [comment] 2019-05-19 11:31
kpmcore: 4.0.0-0xneon+18.04+bionic+build10

As for KDE Partition Manager, hang on... it's being awkward at starting up...

Also update: - Calamares still complains about the lack of an esp flag.

**Comment by feren** [comment] 2019-05-19 11:38
KDE Partition Manager only lists 'boot' and 'bios-grub' partitions. It's also Version 4

**Comment by stikonas** [comment] 2019-05-19 11:59
> KDE Partition Manager only lists 'boot' and 'bios-grub' partitions. It's also Version 4

Oh, that's because boot is ESP on GPT partitions. We simply don't display same thing twice.

`FlagEsp [[deprecated("Use PartitionTable::Flag::Boot")]] = Boot` in 
https://invent.kde.org/kde/kpmcore/blob/master/src/core/partitiontable.h#L108

**Comment by feren** [comment] 2019-05-19 12:20
![image](https://user-images.githubusercontent.com/11057934/57982112-d0b83080-7a38-11e9-9f1e-6efc53cd6157.png)

**Comment by feren** [comment] 2019-05-19 12:47
@stikonas Hmm... Ubuntu's grub-efi-amd64-signed package fails to install without the 'esp' flag... (Calamares said it'd give it 'boot' flag)

![image](https://user-images.githubusercontent.com/11057934/57982375-a10b2780-7a3c-11e9-9420-cc1eb899923a.png)

**Comment by stikonas** [comment] 2019-05-19 12:50
> @stikonas Hmm... Ubuntu's grub-efi-amd64-signed package fails to install without the 'esp' flag... (Calamares said it'd give it 'boot' flag)
> 
> ![image](https://user-images.githubusercontent.com/11057934/57982375-a10b2780-7a3c-11e9-9420-cc1eb899923a.png)

Can you check what is the partition type for /boot/efi? E.g. with sudo sfdisk /dev/sda --json


It should be `C12A7328-F81F-11D2-BA4B-00A0C93EC93B`

**Comment by feren** [comment] 2019-05-19 12:53
Yep, it appears to be that string.

**Comment by stikonas** [comment] 2019-05-19 12:56
> Yep, it appears to be that string.

Then I think this is some other bug that you are encountering. ESP partition type was set correctly. For some other reason, grub does not want to install into it. Is /boot/efi properly mounted to /dev/sda1?

**Comment by feren** [comment] 2019-05-19 13:00
I'll scrap the current partition table and try a new one in Manual Partitioning, just to be sure... I'm currently testing in VirtualBox so I'm ready to keep trying in case.

**Comment by feren** [comment] 2019-05-19 13:07
Hopefully this'll work... 
![image](https://user-images.githubusercontent.com/11057934/57982607-65259180-7a3f-11e9-87e3-c75fbf4b6607.png)

**Comment by feren** [comment] 2019-05-19 13:08
Didn't get a warning this time during Users, so that's a good start... hopefully.

**Comment by feren** [comment] 2019-05-19 13:30
Installation was successful... well that case is closed... that was odd.
