### ISSUE TITLE
[FEAUTER REQUEST]: with automatic disk partitioning, make it possible in which file system to do the markup.

### ISSUE THREAD

**Issue by saber716rus** [calamares/calamares#2080] opened 2022-12-12 16:51 UTC
**Is your feature request related to a problem? Please describe.**
Concerns the disk partitioning function

**Describe the solution you'd like**
Using automatic markup, you can:
1) select the file system of the root directory (/)
2) create a separate directory /home and specify which file system to format (provided there is a second disk)

**Describe alternatives you've considered**
Or the creation of certain scripts that could be edited, and the markup would be performed in accordance with these scenarios.

**Additional context**
In the screenshot, I indicated the approximate location of the button or selection window.
![Screenshot_om_rock_2022-12-12_19:33:59](https://user-images.githubusercontent.com/22714555/207104095-e3ba4de9-9299-40d6-b13b-255f27b1d9eb.png)

**Comment by dalto8** [comment] 2022-12-12 16:56
#1 is already supported.  It needs to be enabled in `partition.conf`

**Comment by saber716rus** [comment] 2022-12-12 17:12
> The first item is already supported. It needs to be enabled in `partition.conf` by setting the file systems you want to offer.
what about a separate /home directory?

**Comment by dalto8** [comment] 2022-12-12 17:14
> what about a separate /home directory?

That is also supported via `partition.conf` but it is not user configurable as you have described.

**Comment by saber716rus** [comment] 2022-12-12 17:16
> > what about a separate /home directory?
> 
> That is also supported via `partition.conf` but it is not user configurable as you have described.

thanks for the clarification.

**Comment by demmm** [comment] 2022-12-12 18:23
For `erase disk` option, this is implemented, enable it in [partition.conf](https://github.com/calamares/calamares/blob/calamares/src/modules/partition/partition.conf#L173)
Result:
![Screenshot_20220920_224207](https://user-images.githubusercontent.com/5360485/207123130-4a9622e8-55ca-44aa-a609-7fce1d927707.png)
For /home, see https://github.com/calamares/calamares/blob/calamares/src/modules/partition/partition.conf#L196

If this is a feature request to also implement for `replace`, then it is a duplicate of https://github.com/calamares/calamares/issues/1911

Closing this one, if more questions for the replace option, continue at the above linked.

**Closed by demmm** 2022-12-12 18:23 UTC
