### ISSUE TITLE
Release 3.3.0~alpha or similar?

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#1999] opened 2022-06-24 00:55 UTC
I'd like to have a clean 3.3.0 tarball that I can just patch.

Are we there yet? What do we consider "there"? Looking for thoughts and opinions.

(By the way, I'm happy to help in any way that I can when it comes to release management upstream, just say the word.)

**Comment by adriaandegroot** [comment] 2022-06-26 19:34
I can roll tarballs from the *calamares* branch with 3.3.0 markings just fine. I'm not particularly **keen** on it, since it's clear that a lot of distro's don't read any of the release notes or announcements, and making it even easier for them to shoot themselves in the foot and then complain over non-public channels (this is not a diatribe at you Simon) seems like a bad idea.

I'll try rolling an `-a1` kind of release just to see if the release scripts support that.

**Comment by demmm** [comment] 2022-06-26 20:03
>a lot of distro's don't read any of the release notes or announcements

Even if waiting a whole lot longer until 3.3 is complete stable, many will still get a terrible experience, since they will **have** to read, otherwise (for example) the mounting changes will completely fail for them.
And as a little feedback, KaOS did release a stable ISO last week, with Calamares from 3.3, all very smooth (download numbers are hard to tally, but looks to be over 5000, so that should have garnered lots of bug reports, if Calamares was not ready).

**Comment by adriaandegroot** [comment] 2022-06-26 22:45
- scripts adapted so that they do the right thing with `-alpha1` style suffixes
- About box shows the version (either the stated version or git version, depending on how Cala is built and whether it's set to release mode)

I ran the release script, and there are test failures:

```
The following tests FAILED:
         31 - load-grubcfg (Failed)
         32 - load-grubcfg-1 (Failed)
        109 - validate-bootloader-bootloader (Failed)
        112 - validate-fstab-fstab (Failed)
        113 - validate-grubcfg-grubcfg (Failed)
        114 - validate-grubcfg-2 (Failed)
        115 - validate-grubcfg-3 (Failed)
        116 - validate-grubcfg-4 (Failed)
        124 - validate-mount-1 (Failed)
        125 - validate-mount-2 (Failed)
        126 - validate-mount-3 (Failed)
        128 - validate-netinstall-netinstall (Failed)
        135 - validate-services-systemd-services-systemd (Failed)
        147 - validate-welcome-welcome (Failed)
        165 - partitiondevicestest (Failed)
```

The validate ones are due to config-file changes becoming de-synchronised from schema-file changes (or, in bootloader's case, something bogus sneaking into the schema). Those tests are easy to run (you need to be able to run `ci/configvalidator.py`) and fix up, I think.

**Comment by adriaandegroot** [comment] 2022-06-26 22:46
> The remaining tests (31, 32, 165) that failed here are because I'm running them on a FreeBSD machine, which doesn't have Plymouth or sfdisk :)

**Comment by tsimonq2** [comment] 2022-06-27 00:01
Thank you! Again, not particular on **when**, just wanted to ask what **qualifies** as Alpha 1 :)

Let me know if I can help you with the tooling or testing at all. I'll ping async.

**Comment by adriaandegroot** [comment] 2022-06-27 22:04
There's a different set of test failures on KaOS now, but the schema-validation is fixed. If you're OK with building from the GH-generated tarball, `v3.3.0-alpha1` will do. I guess that makes it possible to report regressions against the alpha, now, so that (remember, community-maintainence) eventually an alpha2 can happen.

**Comment by adriaandegroot** [comment] 2022-06-30 19:38
Closing this one, since there is an -alpha1 tag now (no uploaded tarballs though).

**Closed by adriaandegroot** 2022-06-30 19:38 UTC

**Comment by killajoe** [comment] 2022-06-30 20:33
not to open this up again.. but you can patch also without a tarball or just go to create your own tarballs on a fork. 
It is more like a devel/git version but it does work for testing 3.3
