### ISSUE TITLE
kpmcore doesn't support dosfstools 4.2 yet, which fails to create GPT partitions

### ISSUE THREAD

**Issue by ezsit55** [calamares/calamares#1637] opened 2021-02-12 23:45 UTC
Never mind. Sorry.

**Comment by apt-ghetto** [comment] 2021-02-13 09:19
Could you please close the issue, if there is no problem?

**Comment by philmmanjaro** [comment] 2021-02-14 11:23
Seems there was a [change](https://github.com/KDE/kpmcore/compare/v20.12.1...v20.12.2) made, which might create some issue. We should double-check this, especially with GPT partition creations.

@stikonas @arcolinuxz

**Comment by stikonas** [comment] 2021-02-14 11:27
That change only fixes out of bounds access in fstab parsing. I don't see how that might cause GPT creation to fail. Did 20.12.1 work?

**Comment by ezsit55** [comment] 2021-02-14 15:27
This was the change that seems to have preceded the problem:

As the sfdisk man page says on the option '--wipe' that
specifies whether or not to wipe signatures in order
to avoid collisions:

> When this option is not given, the default is auto,
> in which case signatures are wiped only when in interactive mode

but sfdisk is not run in interactive mode here, since
stdin does not refer to a terminal, and the sfdisk
man page says:

> It [i.e. sfdisk] runs in interactive mode if executed on terminal
> (stdin refers to a terminal).

Therefore, explicitly pass the '--wipe=always' option to
sfdisk so that old signatures are wiped when a new partition
table is created.

Bug: 431628

**Comment by stikonas** [comment] 2021-02-14 15:33
> This was the change that seems to have preceded the problem:
> 
> As the sfdisk man page says on the option '--wipe' that
> specifies whether or not to wipe signatures in order
> to avoid collisions:
> 
> > When this option is not given, the default is auto,
> > in which case signatures are wiped only when in interactive mode
> 
> but sfdisk is not run in interactive mode here, since
> stdin does not refer to a terminal, and the sfdisk
> man page says:
> 
> > It [i.e. sfdisk] runs in interactive mode if executed on terminal
> > (stdin refers to a terminal).
> 
> Therefore, explicitly pass the '--wipe=always' option to
> sfdisk so that old signatures are wiped when a new partition
> table is created.
> 
> Bug: 431628

This change is not even on 20.12 branch, it definitely couldn't have caused it.

These are the only changes that are in released versions:
https://invent.kde.org/system/kpmcore/-/commits/release/20.12

Maybe something else got updated in the meantime and broke GPT?

**Comment by ezsit55** [comment] 2021-02-14 15:55
The current output of Calamares debug, trying to manually create partitions on an EFI system with GPT:

```
08:40:27 [1]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
    ERROR: Installation failed: "The installer failed to create partition on disk 'VBOX HARDDISK'." 
    ..  - message: "The installer failed to create partition on disk 'VBOX HARDDISK'." 
    ..  - details: ==========================================================================================
Create a new partition (512.00 MiB, fat32) on ‘/dev/sda’
==========================================================================================
==========================================================================================
Job: Create new partition on device ‘/dev/sda’
==========================================================================================
==========================================================================================
Command: sfdisk --force --append /dev/sda
==========================================================================================
==========================================================================================
Command: sfdisk --list --output Device,UUID /dev/sda
==========================================================================================
==========================================================================================
Job: Create file system ‘fat32’ on partition ‘/dev/sda1’
==========================================================================================
==========================================================================================
Command: mkfs.fat -F32 -I -v /dev/sda1
==========================================================================================
==========================================================================================
Command: sfdisk --part-type /dev/sda 1 EBD0A0A2-B9E5-4433-87C0-68B6B72699C7
==========================================================================================
==========================================================================================
Job: Set the file system label on partition ‘/dev/sda1’ to ""
==========================================================================================
Setting label for partition ‘/dev/sda1’ to 

==========================================================================================
Command: fatlabel /dev/sda1 
==========================================================================================

08:40:27 [6]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
    Calamares will quit when the dialog closes. 
08:40:27 [6]: void CalamaresUtils::callQmlFunction(QQuickItem*, const char*)
    QML "onLeave()" is missing. 
08:40:27 [6]: void FinishedPage::setUpRestart()
    FinishedPage::setUpRestart(), Quit button setup= "never" command= "systemctl -i reboot"
```
This just started happening after kpmcore went to 20.12.2-1, as far as I can tell. gdisk out put is:

```
GPT fdisk (gdisk) version 1.0.6

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with protective MBR; using GPT.

Command (? for help): p
Disk /dev/sda: 121634816 sectors, 58.0 GiB
Model: VBOX HARDDISK   
Sector size (logical/physical): 512/512 bytes
Disk identifier (GUID): 9BBF3E28-B539-0C43-B764-2FCEB94000A6
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 33
First usable sector is 2048, last usable sector is 121634782
Partitions will be aligned on 2048-sector boundaries
Total free space is 120584159 sectors (57.5 GiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048         1050623   512.0 MiB   0700  

Command (? for help): i
Using 1
Partition GUID code: EBD0A0A2-B9E5-4433-87C0-68B6B72699C7 (Microsoft basic data)
Partition unique GUID: 2BF01F7B-1F25-9048-84D9-631AA9FDF1C9
First sector: 2048 (at 1024.0 KiB)
Last sector: 1050623 (at 513.0 MiB)
Partition size: 1048576 sectors (512.0 MiB)
Attribute flags: 0000000000000000
Partition name: ''

```

**Comment by stikonas** [comment] 2021-02-14 16:00
Ok, so maybe it's fatlabel command that failed. That's nothing to do with sfdisk though.

It's a bit strange though that `fatlabel /dev/sda1` does not have another argument to set the label. E.g. `fatlabel /dev/sda1 LABEL`.

**Comment by stikonas** [comment] 2021-02-14 16:02
What is your fatlabel version. It might be that your fatabel got upgraded (and possibly with some change that is not backward compatible) and kpmcore or calamares does not support it yet.

**Comment by ezsit55** [comment] 2021-02-14 16:03
Also concerning is that sfdisk is using the wrong GUID for the ESP. I know I selected the boot flag and that should change the GUID to the proper ESP.

**Comment by stikonas** [comment] 2021-02-14 16:12
> Also concerning is that sfdisk is using the wrong GUID for the ESP. I know I selected the boot flag and that should change the GUID to the proper ESP.
> 
> Also, I have the partition.conf settings to name the ESP to EFI. That is not being passed to sfdisk when setting the label?

fatlabel is part of dosfstools. Or run `fatlabel --version` just like you do with any other command line tool...

I just tested with KDE Partition Manager, setting boot flag correctly sets GUID for the ESP. So Calamares probably doesn't call it correctly, so the problem is in calamares, not kpmcore. Anyway, open a new bug for that. It's a separate issue.

**Comment by ezsit55** [comment] 2021-02-14 16:14
Thanks stikonas. fatlabel version is: fatlabel 4.2 (2021-01-31)

**Comment by stikonas** [comment] 2021-02-14 16:17
> Thanks stikonas. fatlabel version is: fatlabel 4.2 (2021-01-31)

Ok, so that's what causes it. If you can downgrade it for now. I'll have to update mine and investigate.

**Comment by stikonas** [comment] 2021-02-14 16:18
https://bugs.kde.org/show_bug.cgi?id=432941

**Comment by ezsit55** [comment] 2021-02-14 16:20
stikonas, thank you!

**Comment by kkofler** [comment] 2021-02-14 16:46
@stikonas:
> It's a bit strange though that `fatlabel /dev/sda1` does not have another argument to set the label. E.g. `fatlabel /dev/sda1 LABEL`.

I think that's an artifact due to how the command lines are printed: the "missing" argument is actually an empty string "" that is not visible in the output.

The issue might be that fatlabel 4.2 chokes on empty strings as labels.

**Comment by stikonas** [comment] 2021-02-14 19:53
> @stikonas:
> 
> > It's a bit strange though that `fatlabel /dev/sda1` does not have another argument to set the label. E.g. `fatlabel /dev/sda1 LABEL`.
> 
> I think that's an artifact due to how the command lines are printed: the "missing" argument is actually an empty string "" that is not visible in the output.
> 
> The issue might be that fatlabel 4.2 chokes on empty strings as labels.

It looks like this is deliberate.

`fatlabel: labels can't be empty or white space only`

**Comment by kkofler** [comment] 2021-02-14 21:20
Looks like you now have to pass the `-r` flag instead of an empty string as label to reset the label (and it will also actually set the label to "NO NAME" rather than "").

**Comment by stikonas** [comment] 2021-02-14 22:58
> Looks like you now have to pass the `-r` flag instead of an empty string as label to reset the label (and it will also actually set the label to "NO NAME" rather than "").

Yeah, and old version of dosfstools does not have `-r` flags. If I try to use it then it just sets label to `-r`.

**Comment by ezsit55** [comment] 2021-02-14 23:51
It might be a lot to think about, but I find sgdisk to be very reliable when dealing with gpt partitions. The syntax is fairly straight forward. It just will not work with mbr partitions. There is always parted.

**Comment by stikonas** [comment] 2021-02-14 23:55
> It might be a lot to think about, but I find sgdisk to be very reliable when dealing with gpt partitions. The syntax is fairly straight forward. It just will not work with mbr partitions. There is always parted.

We use `sfdisk` in kpmcore (used to be parted but it was not too suitable in the longer term). Anyway, this problem has nothing to do with GPT. It's because dosfstools made an incompatible change to behaviour/command line flags.

Like I said the simplest fix would be to just add `-r` flag when label is empty.

**Comment by ezsit55** [comment] 2021-02-14 23:58
Why have sfdisk apply a label when it is unnecessary? On an mbr partition the label is wanted, on a gpt partition, the label is not needed.

**Comment by stikonas** [comment] 2021-02-15 00:04
> Why have sfdisk apply a label when it is unnecessary? On an mbr partition the label is wanted, on a gpt partition, the label is not needed.

It's not sfdisk that applies label. Neither sfdisk nor other low level tools like sgdisk know anything about labels. Labels are higher level stuff. sfdisk just edits partition table (at the begining of the disk or also at the end of the disk in case of GPT).

It's kpmcore library (probably at the request of Calamares) or maybe due to some internal call.

**Comment by stikonas** [comment] 2021-02-15 00:09
`fstab` is a bit orthogonal to this. You can use labels/uuid/partitoin path or gpt uuid / gpt partition name for mounting file systems. But that unrelated to applying label to fs.

And the reason why we set label to empty when it's not needed, is that it's probably due to kpmcore's design:
kpmcore deals with Partition and Filesystem objects. kpmcore users (e.g. Calamares) create Partition object with required properties and ask kpmcore to create that partition. Therefore, kpmcore is kind of unaware whether it setting label is necessary or not. Even if label empty, maybe that partition on the disk had non-empty label, so it has to run that operation of setting empty label.

**Comment by ezsit55** [comment] 2021-02-15 00:11
Thanks for the explanation. I knew I was out of my league with programming. :)

**Comment by killajoe** [comment] 2021-02-18 09:21
A tested workaround till a version of kpmcore working with latest dosfstools is available is to simply downgrade or use a rebuilded version of dosfstools 4.1 on the ISO's. 
EndeavourOS tested this and it is working without issue, arcolinux also reported using older dosfstools fixed it for them.
If you have a deep wish to proof:

https://github.com/endeavouros-team/ISO/releases/download/0-EndeavourOS-development-ISO-releases/endeavouros-devel-cal36-systemdboot-dosfsdowngrade-2021.02.17-x86_64.iso
https://github.com/endeavouros-team/ISO/releases/download/0-EndeavourOS-development-ISO-releases/endeavouros-devel-cal36-systemdboot-dosfsdowngrade-2021.02.17-x86_64.iso.sha512sum

**Comment by erikdubois** [comment] 2021-02-18 09:49
ArcoLinux acknowledges the solution. Downgrade the dosfstools.

**Comment by kkofler** [comment] 2021-02-18 12:12
Well, that doesn't really fix the problem. We won't be able to just downgrade dosfstools on Fedora. (Rawhide has 4.2 now.)

**Comment by stikonas** [comment] 2021-02-18 12:14
> Well, that doesn't really fix the problem. We won't be able to just downgrade dosfstools on Fedora. (Rawhide has 4.2 now.)

I'll patch `kpmcore` tomorrow, so 21.04 will have a fix.

**Comment by arcolinuxz** [comment] 2021-02-18 16:22
that is what we like to read

**Comment by ezsit55** [comment] 2021-02-18 17:20
I just did a video test of the latest Siduction with dosfstools 4.2 and Calamares failed at the same point. I then used KDE Partition Manager to successfully partition the disk. Now, if kmpcore is at the heart of KDE Partition Manager, and Partition Manager worked without a problem, how is the problem in kpmcore? I would think the problem lies somewhere in how Calamares is calling kpmcore.
https://youtu.be/pnl14WWWzIc

**Comment by stikonas** [comment] 2021-02-18 17:26
> I just did a video test of the latest Siduction with dosfstools 4.2 and Calamares failed at the same point. I then used KDE Partition Manager to successfully partition the disk. Now, if kmpcore is at the heart of KDE Partition Manager, and Partition Manager worked without a problem, how is the problem in kpmcore? I would think the problem lies somewhere in how Calamares is calling kpmcore.
> https://youtu.be/pnl14WWWzIc

That's because you gave it a label. The problem only happens when you don't set the label.

**Comment by ezsit55** [comment] 2021-02-18 17:30
Dosfstools no longer allows empty labels, but it also changed the way labels are reset. In the specific use case of creating a fat32 partition for the ESP, there is no label to reset as the partition does not exist yet. Would it not be simpler to just set a label in kpmcore IF the partition is being created? This would not affect pre-existing partitions.

**Comment by stikonas** [comment] 2021-02-18 17:34
> Dosfstools no longer allows empty labels, but it also changed the way labels are reset. In the specific use case of creating a fat32 partition for the ESP, there is no label to reset as the partition does not exist yet. Would it not be simpler to just set a label in kpmcore IF the partition is being created? This would not affect pre-existing partitions.

kpmcore does set labels if it is supplied with one. It's just that Calamares has no idea at all what FS label is. Well, I'll take a look at kpmcore tomorrow and see what I can do.

(Sorry, clicked the wrong button and edited your comment instead of replying. Hopefully restored now)

**Comment by ezsit55** [comment] 2021-02-18 17:37
No problem stikonas. Thanks for the answers. It will be interesting to see how other installers deal with the changes to dosfstools. I wonder if Debian Bulseye will even have dosfstools 4.2? :-)

**Comment by stikonas** [comment] 2021-02-19 17:55
kpmcore is now fixed. (In case of empty labels I set the label to `NO_LABEL`).

I've backported the fix to 20.12.3.

**Comment by arcolinuxz** [comment] 2021-02-20 06:12
For the interested
https://github.com/KDE/kpmcore/commit/36dfae351ffac48134e2697b4fc1024e7557e319

**Comment by arcolinuxz** [comment] 2021-02-20 07:47
Installed ArcoLinux with latest calamares-git commit and latest kpmcore-git commit and latest dosfstools 4.2.1.
@stikonas @adriaandegroot

@stikonas If you can make a new tag then Arch Linux will make a new release. Maybe another confirmation from someone to doublecheck.

We can create EFI partitions again.
![cal4](https://user-images.githubusercontent.com/36679406/108588179-19142900-7358-11eb-8be3-dce93239e81a.png)
![cal3](https://user-images.githubusercontent.com/36679406/108588087-a86d0c80-7357-11eb-9e23-07db256cc3f8.png)
![cal2](https://user-images.githubusercontent.com/36679406/108588089-aa36d000-7357-11eb-9eec-3f1620fdcda3.png)
![cal1](https://user-images.githubusercontent.com/36679406/108588092-aacf6680-7357-11eb-8e58-df3057d123bd.png)

**Comment by stikonas** [comment] 2021-02-20 10:07
> Installed ArcoLinux with latest calamares-git commit and latest kpmcore-git commit and latest dosfstools 4.2.1.
> @stikonas @adriaandegroot
> 
> @stikonas If you can make a new tag then Arch Linux will make a new release. Maybe another confirmation from someone to doublecheck.
> 
> We can create EFI partitions again.
> ![cal4](https://user-images.githubusercontent.com/36679406/108588179-19142900-7358-11eb-8be3-dce93239e81a.png)
> ![cal3](https://user-images.githubusercontent.com/36679406/108588087-a86d0c80-7357-11eb-9e23-07db256cc3f8.png)
> ![cal2](https://user-images.githubusercontent.com/36679406/108588089-aa36d000-7357-11eb-9eec-3f1620fdcda3.png)
> ![cal1](https://user-images.githubusercontent.com/36679406/108588092-aacf6680-7357-11eb-8e58-df3057d123bd.png)
> 
> After installation
> 
> ![cal5](https://user-images.githubusercontent.com/36679406/108588320-c2f3b580-7358-11eb-8935-29d5e9eafd47.png)

kpmcore releases are now part of KDE Release Service. That means it will be released together with all other software (like Kate/Dolphin, etc) on 4 March (tagging is done on 1 March).

**Comment by kkofler** [comment] 2021-02-20 11:59
> In case of empty labels I set the label to `NO_LABEL`

Can't you check (through `--help` output or something) whether `fatlabel` supports the `-r` flag? I believe this has been done in other such cases in `kpmcore`.

**Comment by geckolinux** [comment] 2021-02-20 14:38
Thanks a lot for the fix. Since I need to get a release out I'm going to manually substitute the dosfstools 4.1 RPM from openSUSE Leap instead of the Tumbleweed version. Shouldn't be any issues with that right?

**Comment by stikonas** [comment] 2021-02-20 14:43
Yes, that's fine.

On 20 February 2021 14:38:50 GMT, GeckoLinux <notifications@github.com> wrote:
>Thanks a lot for the fix. Since I need to get a release out I'm going
>to manually substitute the dosfstools 4.1 RPM from openSUSE Leap
>instead of the Tumbleweed version. Shouldn't be any issues with that
>right?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/calamares/calamares/issues/1637#issuecomment-782691415

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ezsit55** [comment] 2021-03-12 01:58
Kpmcore 20.12.3-1 was released March 4, 2021 and fixed the issue.

**Closed** 2021-03-12 01:57 UTC
Labels: N partitioning, bug: upstream
