### ISSUE TITLE
It should be possible for uefi installations  __not__ to run a grub install

### ISSUE THREAD

**Issue by agaida** [calamares/calamares#1256] opened 2019-10-13 15:07 UTC
**Describe the bug**
in legacy installations one has the option to select a target where to install grub or not to install grub at all. For UEFI installations there is no such option aka grub is installed everytime. This has an major impact on multiboot-systems. So it should be configurable.
This is a follow up to https://github.com/calamares/calamares/issues/517

**To Reproduce**
Just install more than one system with Calmares - next boot will bring up the grub menu from the latest installed system.

**Expected behavior**
There should be an option similar to legacy installations

**Screenshots and Logs**
![](https://i.imgur.com/Fo9y1yM.png)
![](https://i.imgur.com/Xg0LFbz.png)

**Additional context**

The easyiest approach would be: 
* just don't care if there is an efi directory / a efi partition
* don't run the grub-install $foo - done.

This implies that the fresh installed system isn't started at reboot and that the bootloader configuration of the system which handles the boot loader has to be updated. Default should be to just install grub.

**Comment by demmm** [comment] 2020-02-08 20:51
Duplicate of https://github.com/calamares/calamares/issues/517

**Closed** 2020-02-16 17:28 UTC
Labels: M duplicate, feature: new
