### ISSUE TITLE
BTRFS - volumes not correctly added to fstab

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#796] opened 2017-09-11 10:42 UTC
According to the [german Youtube review](https://www.youtube.com/watch?v=sk9h4vh50WY) it seems, that BTRFS volumes don't get properly added to **fstab**. I've to recreate the issue once more, to find some pointers on how to fix this ...

**Comment by abucodonosor** [comment] 2017-09-12 05:25
@philmmanjaro 

to follow this guy is really HARD .. anyway he is funny :-)

I see what is wrong already .. you simple hit #797 
( also the guy forgot to tell swap is missing too )

The problem we see is the following:

-  LANG being used is de_DE

* /boot ext2 ( not translated )
* / btrfs ( translated Btrfs but the check is different for root in is our modules )
* swap  swap ( translated Linux-Swap )

this is what we get back from KPMcore with his configuration:

```
"/dev/sda1" mtpoint: "/boot" fs: QVariant(QString, "ext2")
"/dev/sda2" mtpoint: "/" fs: QVariant(QString, "Btrfs")
"/dev/sda3" mtpoint: "" fs: QVariant(QString, "Linux-Swap")

```
And your bftrfs problems starting from there now:

https://github.com/calamares/calamares/blob/master/src/modules/fstab/main.py#L187

``` 
     if (partition["fs"] == "btrfs" .... <-- won't trigger since is now Btrfs

```
Same situation for swap also for sure swap was not written to grub.cfg 

Also for sure LUKS installations are broken.

You can do a simple test for that..

Fire up any of your ISO in qemu/vbox in de_DE.. goto terminal 

``` LC_ALL=C sudo -E calamares -d ```

Now open another tab , do a mount to see tmp_root_mount_point and chroot to there.
Wait installation finishes and cat etc/fstab .. all should be fine.

Do now the same with de_DE :)

A quick an dirty hack for now  would be to have a small rm_function() in your
ISO creation script(s) and before you umount your rootfs image run it and
rm -rf all kpmcore locales so you have on your ISO just plain en_US for KPMcore.

I use something similar to workaround that for now since it break with a lot laguages.

I hope this helps you fixing that..

**Comment by abucodonosor** [comment] 2017-09-12 10:32
@philmmanjaro 

not really about that issue but found out btrfs is broken with luks+systemd .. leftover
from #730 .. will fix that in a bit

**Comment by philmmanjaro** [comment] 2017-09-12 10:39
@adriaandegroot & @stikonas: I've tested now my last changes. Seems to work now.

**Comment by abucodonosor** [comment] 2017-09-12 10:46
@philmmanjaro 
https://github.com/abucodonosor/calamares/commit/457fa9fab88b7b0bed83ff94c4084ce1b669b94d

( now your btrfs user should be happy )

**Comment by adriaandegroot** [comment] 2017-09-14 10:37
Closing this one because I merged the stuff from @abucodonosor , and fixed the (un)translation of the fs names just now -- messing around in all the uses of the fs-label, instead of fixing it at the source, is patching symptoms instead of the cause.

**Closed by adriaandegroot** 2017-09-14 10:37 UTC

**Comment by philmmanjaro** [comment] 2017-09-14 12:06
Yes, it makes totally sense.
