### ISSUE TITLE
Error in Calamares Installer on Debian Bookworm: Boost.Python Error in Job "mount"

### ISSUE THREAD

**Issue by Yassine-cdev** [calamares/calamares#2382] opened 2024-10-09 15:03 UTC
### **During the installation of Debian Bookworm (using Calamares), the installation fails with the following error message:
Boost.Python error in job "mount".**
The error seems to occur when Calamares tries to mount the partitions. Below is the detailed error log from Calamares:
<class 'Boost.Python.ArgumentError'>
Python argument types in
libcalamares.utils.mount(str, str, str, list)
did not match C++ signature:
mount(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > device_path, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > mount_point)
mount(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > device_path, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > mount_point, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > filesystem_name)
mount(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > device_path, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > mount_point, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > filesystem_name, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > options)

System Information:

Live Environment: The issue is occurring while using a live USB environment for the installation.
Partition Layout (from lsblk)
NAME      MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0       7:0    0   2.7G  1 loop /usr/lib/live/mount/rootfs/filesystem.squashfs
                                    /run/live/rootfs/filesystem.squashfs
sda         8:0    1  57.3G  0 disk 
└─sda1      8:1    1   2.8G  0 part /usr/lib/live/mount/medium
                                    /run/live/medium
sdb         8:16   1  14.6G  0 disk 
└─sdb1      8:17   1  14.6G  0 part /media/van/ESD-USB
nvme0n1   259:0    0 238.5G  0 disk 
├─nvme0n1p1
│         259:2    0   300M  0 part /tmp/calamares-root-ye7qfh7j/boot/efi
└─nvme0n1p2
          259:3    0 238.2G  0 part /tmp/calamares-root-ye7qfh7j
Steps Taken:

I tried running the installer, but it failed with the error mentioned.
Manually checked and mounted partitions.
Attempted to use fsck and mount manually, no issues there.
Possible Cause: The issue seems to be related to a mismatch between the Python function signature and the expected C++ signature in the Calamares mount function, which causes it to fail when trying to mount the partitions.
 **Could someone help resolve this issue or provide guidance on how to bypass or fix the partition mount error?**

**Comment by demmm** [comment] 2024-10-09 16:18
This seems to be a report from an end user:
https://calamares.io/issues/
https://calamares.io/issues/#end-users
Far better to contact your distribution to see if it is an issue known there, or ask them to backport the needed fixes.
Seems to be a duplicate of https://github.com/calamares/calamares/issues/2366 and https://github.com/calamares/calamares/issues/2381

**Closed by demmm** 2024-10-09 16:18 UTC
