### ISSUE TITLE
Crashes straight after launching on KDE Neon Developer Edition ISO

### ISSUE THREAD

**Issue by Silver-Saucepan** [calamares/calamares#1746] opened 2021-08-04 11:08 UTC
I reported this on the KDE bugtracker: [bug 440553](https://bugs.kde.org/show_bug.cgi?id=440553) and have been advised to report it here.

Calamares crashes on launch when installing KDE neon Developer Edition

**To Reproduce**
1. Download KDE neon developer edition ISO (I'm using neon-developer-20210802-1847.iso)
2. Burn it onto a USB stick
3. Reboot
4. Click "Install System"

OBSERVED RESULT
Installer starts and briefly shows it's welcome/select language screen before it crashes and the crash handler is displayed

EXPECTED RESULT
Installation process does not crash

**Screenshots and Logs**
~/.cache/calamares/session.log is not created

**Additional context**
I get the same behaviour on a VM set-up as described on [https://github.com/calamares/calamares/wiki/Test-Guide](url)

**Comment by demmm** [comment] 2021-08-04 21:04
Can you start Calamares without the partition module? Meaning, comment out the two instances of `partition` in settings.conf (can be /etc/calamares/settings.conf or /usr/share/calamares/settings.conf, former has precedent).
I can replicate the crashing, debug points to this commit mostly https://github.com/calamares/calamares/commit/e0b8942242648b076ec608062fd95b6d5fe3bff3
Starts fine if partition module is not loaded.

**Comment by Silver-Saucepan** [comment] 2021-08-04 21:32
No settings.conf in either of those locations, but found one in /calamares/desktop/settings.conf  
Commenting out the two lines with the word "- partition", calamares no longer crashes, but it fails to initialise with the message that the bootloader@bootloader module couldn't be loaded

**Comment by demmm** [comment] 2021-08-04 21:39
Can you also run with ` sudo calamares -d`? Re-add partiton.
My crash report:
```
Application: Calamares (calamares), signal: Segmentation fault

[KCrash Handler]
#4  Calamares::PrettyRadioButton::setText (this=this@entry=0x0, text=...) at /usr/src/debug/calamares/src/libcalamaresui/widgets/PrettyRadioButton.cpp:50
#5  0x00007f82231859ca in ChoicePage::retranslate (this=this@entry=0x1938f50) at /usr/src/debug/calamares/src/modules/partition/gui/ChoicePage.cpp:143
#6  0x00007f8223185f80 in ChoicePage::ChoicePage (this=0x1938f50, config=<optimized out>, parent=<optimized out>) at /usr/src/debug/calamares/src/modules/partition/gui/ChoicePage.cpp:1>
#7  0x00007f822314b242 in PartitionViewStep::continueLoading (this=0x1798930) at /usr/src/debug/calamares/src/modules/partition/PartitionViewStep.cpp:73
#8  0x00007f822314b41e in operator() (__closure=0x1564a50) at /usr/src/debug/calamares/src/modules/partition/PartitionViewStep.cpp:668
#9  QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, PartitionViewStep::setConfigurationMap(const QVariantMap&)::<lambda()> >::call (arg=<optimized out>, f=...>
#10 QtPrivate::Functor<PartitionViewStep::setConfigurationMap(const QVariantMap&)::<lambda()>, 0>::call<QtPrivate::List<>, void> (arg=<optimized out>, f=...) at /usr/include/qt5/QtCore>
#11 QtPrivate::QFunctorSlotObject<PartitionViewStep::setConfigurationMap(const QVariantMap&)::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *>
#12 0x00007f82a4847a34 in void doActivate<false>(QObject*, int, void**) () from /usr/lib/libQt5Core.so.5
#13 0x00007f82a464b8a5 in QFutureWatcherBase::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#14 0x00007f82a5d6faaf in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#15 0x00007f82a48130da in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#16 0x00007f82a4815da1 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#17 0x00007f82a4867d53 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () from /usr/lib/libQt5Core.so.5
#18 0x00007f82a0d11fdb in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#19 0x00007f82a0d12258 in ?? () from /usr/lib/libglib-2.0.so.0
#20 0x00007f82a0d122ff in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#21 0x00007f82a4867430 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#22 0x00007f82a4811c7b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#23 0x00007f82a481987c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#24 0x0000000000413b29 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/calamares/src/calamares/main.cpp:165
[Inferior 1 (process 847033) detached]
```

**Comment by Silver-Saucepan** [comment] 2021-08-04 22:08
Terminal output attached.  Doesn't look very useful to me :-(

[calamares.txt](https://github.com/calamares/calamares/files/6934640/calamares.txt)

**Comment by jriddell** [comment] 2021-08-05 11:37
I did a git bisect on the last good build we had but there are some commits which did not built so it didn't get an exact answer.  It concluded:

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
616f3d4fd7feb0ebfcab0b664403026866da1950
e0b8942242648b076ec608062fd95b6d5fe3bff3
e8cb5c621a1b1383c2f1648bd8ecc49fea99c829
We cannot bisect more!

**Comment by adriaandegroot** [comment] 2021-08-05 12:37
Confirmed, fix is in-progress.

**Comment by demmm** [comment] 2021-08-05 12:42
In case feedback needed, https://github.com/calamares/calamares/commit/2820316d16aba7a7f58708f193d8da3ace46f029, makes it so that cala starts again, but still crashes when changing locale in the welcome page.

**Comment by adriaandegroot** [comment] 2021-08-05 12:57
Amusingly (for some value of "amusing" the crash @demmm mentions, only happens because **previously** the waiting-widget was never translated, because the code was wrong; now the code is right but still wrong in a different way). Fixed in the new release.

**Comment by demmm** [comment] 2021-08-05 13:25
For me, crashing is fixed.

**Comment by adriaandegroot** [comment] 2021-08-05 13:31
Release 3.2.41.1 is out, fixing this one.

**Closed by adriaandegroot** 2021-08-05 13:31 UTC
