### ISSUE TITLE
Wrong minimum /boot/efi partition size requirement

### ISSUE THREAD

**Issue by xeroling** [calamares/calamares#1803] opened 2021-10-05 12:48 UTC
**Describe the bug**
While installing Feren OS, I got this warning, the /boot/efi partition has to be 314 TiB in size 

**To Reproduce**
1. Boot Feren OS 2021.10 live usb 
2. ... Choose manual partitioning 
3. Set the `/` mount point on ssd partition 5 (ext4 - 47GB)
4. set `/home` mount point On hdd partition 3 (ext4 - 94GB)
5. set `/boot/efi` partition to be the same one Windows is using (ssd partition 2 (vfat - 121MiB))
6. proceed... (Warning appears asking for 314TiB)

**Expected behavior**
Once i set the (`/` on ext4) & (`/boot/efi` on the same 121mib windows boot partition)  partitions, I get no warning usually
Note: this same method worked fine for kde neon - ubuntu - zorin os - basically none gave me such a warning

**Screenshots and Logs**
![20211005_052919](https://user-images.githubusercontent.com/24789792/136022413-044f49c9-dd40-4095-90f4-ea2a39c72a5a.jpg)

**Additional Context**
I ignored it and the installation was successful

**Comment by demmm** [comment] 2021-10-05 14:37
Duplicate of https://github.com/calamares/calamares/issues/1796
Fixed in Calamares 3.2.44.3.

**Closed by demmm** 2021-10-05 14:37 UTC
