### ISSUE TITLE
Package Manager error pacman

### ISSUE THREAD

**Issue by Henryws** [calamares/calamares#1748] opened 2021-08-11 16:30 UTC
**Describe the bug**
I setup an arch linux iso with kde preinstalled and booted into it in virtualbox. I used `makepkg` to install [calamares](https://github.com/arch-linux-calamares-installer/alci-pkgbuild/blob/master/calamares/alci-calamares-dev/calamares-3.2.40-1/PKGBUILD) and [config files](https://github.com/arch-linux-calamares-installer/alci-pkgbuild/blob/master/alci-calamares-config-dev/PKGBUILD). So I start to install arch. But when the install process gets to installing packages, it fails with `pacman -S --noconfirm plasma-meta`. Logs say that the package db files are an unrecognized archive format

**To Reproduce**
1: Install [archuseriso](https://github.com/Hep-OS/archuseriso/)
2: Create a KDE iso
3: Boot in virtualbox
4: Install the calamares PKGBUILD and relevant depdencies
5: Install the calamares config PKGBUILD

**Expected behavior**
For it to download and install `plasma-meta`

**Screenshots and Logs**
![image](https://user-images.githubusercontent.com/58742515/129067269-174122b5-77ae-4cd0-b111-7619fe480148.png)

[log](https://transfer.sh/1KMH6Jz/calamareslog)

**Comment by killajoe** [comment] 2021-08-11 16:57
"unrecognized archive format"  caused by a BUG in pacman where it takes 404 page code as the db file... .. caused when mirrors are not working..   you could see that if you would open the db files  ;)  
So you simply need better mirrors to be used..

**Comment by Henryws** [comment] 2021-08-11 16:59
> "unrecognized archive format"  caused by a BUG in pacman where it takes 404 page code as the db file... .. caused when mirrors are not working..   you could see that if you would open the db files  ;)  
> 
> So you simply need better mirrors to be used.. 
> 
> 
> 
> 

How would I view those?

**Comment by adriaandegroot** [comment] 2021-08-11 20:29
To see the files, `more /var/lib/pacman/sync/community.db` will show you .. well, if it's a proper archive, it will look like garbage, and if it's not an archive but a 404 page, it will look like HTML. While experimenting with some of @killajoe 's ISO images I had exactly that -- one mirror was consistently returning a 404 page which contained a mailchimp advertisement; all the `.db` files were 613kB in size because it was a huge ad :disappointed: 

Once the archive is corrupt, I don't think any subsequent run of pacman will fix them; you'd have to rm the archives and then run pacman again and hope (?) it picks different mirrors somehow. I ended up going through mirrors selection -- @killajoe has that as a startup feature -- and pickling Germany and disabling Netherlands. That fixed it for me.

This isn't a Calamares issue, so I'm going to close it.

**Closed by adriaandegroot** 2021-08-11 20:29 UTC

**Comment by Henryws** [comment] 2021-08-11 22:39
running `more /var/lib/pacman/sync/community.db` say's they aren't text files
