### ISSUE TITLE
"ESP Boot flag not set" pop-up when Edit option is used.

### ISSUE THREAD

**Issue by arunpyasi** [calamares/calamares#1373] opened 2020-04-09 15:17 UTC
**Describe the bug**
A clear and concise description of what the bug is. Please include 32/64 bit machine details, EFI/BIOS details, and disk setup.

- Environment : Oracle VM
- On a machine with existing Lubuntu.
- 64 bit machine
- EFI
- 30 GB allocated to the drive.

**To Reproduce**
1. Select "An existing FAT32 partition that you want to setup for ESP" (make sure not to delete it or create new one.)
2. Click on Edit button
3. Select boot flag with FAT32 mount point as /boot/efi
4. Press the Next button and the warning that "ESP flat not set" will popup.

**Expected behavior**
There should be no "ESP flag not set" pop-up and it should allow further setup.

**Screenshots and Logs**
![image](https://user-images.githubusercontent.com/5819908/78910923-4ee45200-7aa5-11ea-98ce-48d9929e9489.png)
![image](https://user-images.githubusercontent.com/5819908/78910944-56a3f680-7aa5-11ea-91d0-3fba23e5ff20.png)
![image](https://user-images.githubusercontent.com/5819908/78910963-5d326e00-7aa5-11ea-919a-1d2b34a12fd2.png)

**Comment by abucodonosor** [comment] 2020-04-09 15:25
Dupe of #1192

**Comment by abucodonosor** [comment] 2020-06-09 00:26
https://github.com/calamares/calamares/commit/cb99f446b3f119f2e378b5d625093173eedb73b0

**Closed by abucodonosor** 2020-06-09 00:26 UTC
Labels: M duplicate
