### ISSUE TITLE
RAID0 Issues

### ISSUE THREAD

**Issue by julioesc** [calamares/calamares#806] opened 2017-09-17 02:14 UTC
[Using Google translator]
Hi, I'm having trouble installing Manjaro 17.0.5 using RAID 0. My motherboard is an ASRock Fatal1ty Z170 Gaming K4. In Manjaro 16 I could install without problems. When executing the command "lsblk" the partitions inside raid0 / dev / md126 are detected. However, in the calamares are not listed.

When accessing this problem https://github.com/calamares/calamares/issues/794, I edited the file located in /usr/lib/calamares/modules/initcpiocfg/main.py including in HOOKS:

    hooks = ["base", "udev", "autodetect", "modconf", "block", "mdadm_udev", "keyboard",
             "keymap"]

I also edited the /etc/mkinitcpio.conf file. I executed the command "mkinitcpio -p /etc/mkinitcpio.d/linux49.preset.It executed without errors.I ran the calamares again and continued without detecting RAID0.

I went back to the files, I added to MODULES "ext4" "dm_mod" "raid0". I did everything again, without success.

What has changed in this version in relation to the calamares contained in the Manjaro 16? I could start again from this version but it is not compatible with the intel kaby lake video (my geforce died), so it is only possible through 17.

**Comment by philmmanjaro** [comment] 2017-09-17 07:46
Which exact version of **Calamares** was used in the **v16** version of Manjaro you're able to install?

**Comment by wolfyrion** [comment] 2017-09-17 08:46
I am having the same problem with ASRock Fatal1ty  X399 trying to raid 0 2x NVme disks.

I manually created the raid and mount it but the installer cannot recognize the Raid drive.
If there was an option for the installer to do a blind installation, I mean somehow to manually point the raid drive(/dev/md0) and installer perform the installation.Also at the end if the installer asked in which drive to install Grub , that would be awesome. After that we can manually configure mkinitcpio,fstab and so on.

I have checked also other distros like (Antergos, Chakra and so on) but none is supporting automated Raid Installation.
I can do manually installation of Arch or Debian but is a bit of hassle to even bother with that...

SSD's nowadays are getting cheaper and cheaper and many people would want to do raid 0 there SSD Drives so it would be nice if the installer was giving us that option Automated or even Manually.

I am willing to test any ISO in order to test Calamares Raid functionality if you are planning to develop it.

**Comment by julioesc** [comment] 2017-09-17 10:44
@philmmanjaro 2.4.5-1

**Comment by abucodonosor** [comment] 2017-09-17 14:33
Please guys .. BUG -> Feature Request .. Once again _there is nothing like RAID_ support
right now in calamares .. To support RAID ( and not only RAID ) we need:

1) RAID support in GUI
2) some mdadm python module
3) once 1 and 2 is done support for the initramfs modules
4) probably fstab , bootloader , grubcfg LUKS support ..

**Comment by demmm** [comment] 2017-09-18 12:53
Closing as not a bug, user is trying to do things not supported in Calamares at this stage.
Add your voice to the feature requests for RAID.

**Closed by demmm** 2017-09-18 12:53 UTC
