### ISSUE TITLE
CAL-439: Use present LUKS+LVM+Partitions

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#597] opened 2017-01-06 20:34 UTC
Jira issue originally created by user salamandar:

I installed several systems with already present LUKS+LVM.
I want to preserve the present home/swap/data partitions inside LVM.
It's currently not possible : 
* The manual partitionning only shows the LUKS container and it can only be fully replaced
* The "Replace a partitions with the new system" also replaces the whole LUKS container.

It's the case even with the LUKS container decrypted. I did not try it with a non-encrypted LVM system, so I don't know if it's related to LUKS, LVM, or both.

**Comment by Pointedstick** [comment] 2017-04-21 19:01
This is LVM, not LUKS. I have the same problem with my unencrypted LVM volume group. Calamares simply doesn't speak LVM yet: https://github.com/calamares/calamares/issues/427. So this is likely a duplicate of that.

**Comment by adriaandegroot** [comment] 2017-09-07 20:53
Close as dup of #427

**Closed by adriaandegroot** 2017-09-07 20:53 UTC
Labels: improvement
