### ISSUE TITLE
Firefox does not start with pkexec

### ISSUE THREAD

**Issue by apt-ghetto** [calamares/calamares#1217] opened 2019-08-11 09:23 UTC
**Describe the bug**
`pkexec` (because of _com.github.calamares.calamares.policy_) changes the `$DISPLAY` and `$XAUTHORITY` environment variables and runs Calamares with elevated privileges. If you launch Firefox from Calamares, Firefox is started as root, but won't run, because the session is owned by a regular user (this is the desired behaviour).
It is never a good idea to run Firefox as `root`, especially on live-systems where Firefox is usually outdated.

**To Reproduce**
1. Boot live-system (I have tried it with Lubuntu 19.10)
2. Open a terminal and execute `pkexec calamares`
3. On the welcome screen, click on "Lubuntu support"

**Expected behavior**
Firefox opens and is usable and is running only as `root`, if the whole session is running as `root`.

**Screenshots and Logs**
```
16:43:00 [0]: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/lubuntu/.Xauthority which is owned by lubuntu.)
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/lubuntu/.Xauthority which is owned by lubuntu.)
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/lubuntu/.Xauthority which is owned by lubuntu.)
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: chromium: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: chromium-browser: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: google-chrome: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'https://lubuntu.me/links/'
```

**Additional context**
In Lubuntu, we use
```
Exec=bash -c "export BROWSER='sudo -H -u lubuntu firefox'; sudo -E calamares"
```
to circumvent this limitation. Obviously we use `sudo` instead of `pkexec`. But we were evaluating to switch to `pkexec`. That is also why I discovered this behaviour.

**Possible short-term solution**
Run external processes such as Firefox only as user, who owns the X11 session. (The user might be also `root`, although this is discouraged.)

**Possible long-term solution**
Calamares (the GUI/client part) should be run only as regular user (or `root`, if the whole session is owned by `root`). Actions, which really need elevated privileges such as partitioning, should be run separately (as a system process).
For example (for illustrative purposes, I don't know, if there is a KDE equivalent), the gvfs admin backend allows to edit a file owned by `root` in an editor with regular privileges.
This long-term solution should then also work with Wayland.

**Comment by adriaandegroot** [comment] 2019-08-13 21:30
This is basically a duplicate of #1051 (webview causes errors because WebEngine doesn't like to be root) #747 (wayland fails to start, because it wants to be root) and #523 (accessibility of a Qt-app-running-as-root), rolled into one.

There's a long-term plan to make it possible to run Calamares as non-root, and KPMCore does pretty well in that regard but all the **other** bits of Calamares (especially the Python modules running random commands through `os.system()`) haven't been looked at in this regard. I'd recommend running Calamares as non-root from your installer medium and then filing issues (or better yet, PRs) for the issues you find then.

**Comment by abucodonosor** [comment] 2020-02-16 17:26
Duplicate of #1051

**Closed by abucodonosor** 2020-02-16 17:26 UTC
Labels: M duplicate, bug
