### ISSUE TITLE
RAID support

### ISSUE THREAD

**Issue by rippin93** [calamares/calamares#794] opened 2017-09-10 21:46 UTC
I tried installing manjaro-16.06 on a RAID 0 array but this didn't work out well for me.

Could you please add mdadm_udev to the HOOKS array in /etc/mkinitcpio.conf so they are mounted by fstab on boot so people with a RAID do not have to rebuild their initramfs image themselves?

This was also issued in calamares/calamares-manjaro#10 but not in this bugtracker.

Greetings,

Daniel

**Comment by philmmanjaro** [comment] 2017-09-10 22:10
Is this still current as **v17.0.4** is our latest release of Manjaro.

**Comment by abucodonosor** [comment] 2017-09-11 00:51
@philmmanjaro 

Also here this seems to be an issue since nothing checks for an RAID HOOK by default.

https://github.com/calamares/calamares/blob/master/src/modules/initcpiocfg/main.py#L99

Anyway I don't know how the mkinitcpio.conf looks like in manjaro :)

The question is.. Do we need add this upstream or let distros handle RAID ?

**Comment by philmmanjaro** [comment] 2017-09-11 06:50
@abucodonosor: what is needed to support RAID? In general the [configuration of RAID](https://wiki.archlinux.org/index.php/RAID#Update_configuration_file_2) seems to differ for some systems ...

**Comment by adriaandegroot** [comment] 2017-09-11 09:16
Please provide information on how the disks are set up, in detail, with full logs of commands issued elsewhere, as well as what you expect to have happen when Calamares installs. This is the same as with LVM issues: I can't test something if you don't tell me first what it is you are doing.

**Comment by abucodonosor** [comment] 2017-09-11 16:29
@philmmanjaro 

since the user need to do the most things from comandline anyway ,
there is nothing like auto-layout for RAID right now , at least some tools should
be on the ISO also the initramfs should have some support for RAID.

In your case mdadm and mdadm HOOKS for mkinitcpio ( and probably some HOWTO )

**Comment by rippin93** [comment] 2017-09-11 22:11
@adriaandegroot: I for myself was not able at all to install manjaro on my RAID 0 array which leads to the fact that i cannot provide the commands i used.

I would have expected calamares to auto-detect, that I try to install on a RAID 0 array or at least to mount the array so i can manually create the partitions I want to use.

**Comment by abucodonosor** [comment] 2017-09-12 05:31
@rippin93 

calamares doesn't have any software RAID auto-support right now.

**Comment by adriaandegroot** [comment] 2017-09-14 07:43
Closing as "unclear what is being asked". I guess it means "add *mdadm_udev* to the `hooks` list in `modify_mkinitcpio_conf()` in the *initcpiocfg* module, under certain circumstances", but without the circumstances or means to reproduce the setup, can't do much.

**Closed by adriaandegroot** 2017-09-14 07:43 UTC
