### ISSUE TITLE
We should not only check if ESP flag exists, also if it get set.

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#884] opened 2017-12-27 08:11 UTC
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

Based on the findings of https://github.com/calamares/calamares/issues/880

#### Info regarding which version of Calamares is used, which Distribution

**v3.1.11** upstream. Any Distro.

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

You try to install on a EFI system without having the proper flags **boot** and **esp** set for your ESP fat32 partition.

#### What do you expect to have happen when Calamares installs?

Not only to check for already existing **esp** flag, but also to check if the flag get set, after the user corrected the needed setting, when shown the original warning message:

<img src=https://camo.githubusercontent.com/9c2b3a1982b72183fd26f33f7dc0ee71f2e7b3e4/68747470733a2f2f666f72756d2e6d616e6a61726f2e6f72672f75706c6f6164732f64656661756c742f6f726967696e616c2f33582f662f372f663732303638373663633864313139393065666466323265336261613666643761373537306637362e706e67>

#### Describe the issue you encountered

When not checking for **esp** flag to be set you will still see the warning, even it will be corrected in a future step and therefore the system will boot just fine.

#### Steps to reproduce the problem

* don't set the needed flag **esp** on your **fat32** partition
* click **next** after done with your manual partitioning
* you get the warning to set **esp** flag properly
* go back and correct it
* you still see the warning, even it will be corrected in a future step

**Comment by philmmanjaro** [comment] 2017-12-27 08:16
I searched the code and found this:

* Current **EFI** check got introduced with **v3.1-beta2**: https://github.com/calamares/calamares/commit/0c7b7ed0892958851a28e4d532a06d541152343b
* Check then got moved to `onLeave()` with **v3.1-beta2**: https://github.com/calamares/calamares/commit/fb5b48528b2debb13969ee89058d6dadf435f6e6

So it was never modified since creation, to check also things happen to flags in a later step.

**Comment by adriaandegroot** [comment] 2017-12-28 12:35
Ah, ok .. so this is about the UI (warning when it shouldn't).

**Comment by philmmanjaro** [comment] 2017-12-28 12:48
Exactly. The regression not able to set the flag is fixed in **kpmcore-3.2** and **master** branch, however the message still occurs when we are about to set the flags in a later step. That option was not thought of yet.

**Comment by geckolinux** [comment] 2018-01-09 12:55
Maybe it's just my ignorance, but the UI warning makes me think that there should be a flag available named `ESP` or `esp`. But everything seems to indicate that such a flag doesn't even exist anymore, and it's actually the `boot` flag that is needed.

https://wiki.archlinux.org/index.php/EFI_System_Partition#GPT_partitioned_disks
> Create a FAT32 partition and in Parted set/activate the `boot` flag

https://www.rodsbooks.com/efi-bootloaders/principles.html
> In GPT fdisk, ESPs are displayed as having a type code of EF00, and most libparted-based tools use a "boot flag" (and a redundant "esp flag") to identify the ESP.

This is an openSUSE Leap 42.3 based EFI system that boots correctly. Note that no `esp` flag is available according to libparted:
![screenshot from 2018-01-09 07-54-35](https://user-images.githubusercontent.com/2692138/34721830-5e5a3292-f512-11e7-9e22-adebaeaa960c.png)

**Comment by adriaandegroot** [comment] 2018-01-09 13:48
This issue contains two parallel issues, as @geckolinux carefully points out: the ESP and boot flags are the same ones -- possibly this applies only to recent libparted's, though, since others **do** have an ESP flag in the list.

The UI message should definitely be massaged.

The UI should also know when the flag has been set.

**Comment by geckolinux** [comment] 2018-01-09 14:07
An additional bug that stems from this is that Calamares won't offer automatic resize or replace partition options when it can't find an `esp` flag:

automatic resize or replace partition options due to this same bug with the system not seeing/supporting the `esp` flag.

     08:45:47 [1]: Partition "/dev/sda3" authorized for replace install. 
     08:45:47 [1]: Required  storage B: 6442450944 "(6GB)" 
     08:45:47 [1]: Storage capacity  B: 5467648 "(0GB)" for ""    length: 10679 
     08:45:47 [1]: WARNING: system is EFI but there's no EFI system partition, DISABLING alongside and     replace features. 

Should I open a separate bug for this issue?

**Comment by adriaandegroot** [comment] 2018-01-09 15:07
Zeroing in on this:
 - in the MSDOS partitioning scheme, boot and esp flags are distinct; boot=1 (bit 0) and esp=131072 (bit 17) in the flag word
 - in the GPT partitioning scheme, boot and esp are synonyms; boot=1 (bit 0) and esp is too

Source: https://www.gnu.org/software/parted/manual/parted.html#set

KPMCore has an enum for these, which names FlagBoot and FlagEsp according to the MSDOS scheme. Calamares code checks for FlagEsp in various places -- i.e. using the MSDOS flag value (bit 17) even when Esp should alias to Boot (bit 0). So that is why it is not finding your Esp (Boot) partition on a GPT-style partition table -- it is looking at the wrong bit.

**Comment by adriaandegroot** [comment] 2018-01-09 16:17
@geckolinux In master 637d6ad and e3b7a28 it should at least find your partitions, and not warn if you've set boot (when there's no esp flag available, on a gpt table).

It does not yet fix @philmmanjaro 's original problem that once the flag **is** set, it still thinks it isn't .. but that's for another round of fixes (e.g. tomorrow).

**Comment by philmmanjaro** [comment] 2018-01-09 20:03
@adriaandegroot: yeah. This bug report is just for finding a way to not only check if **esp** or **boot** was already set. It is fine to inform the user once. However, we should also check if this flag is about to be set. If **boot** is fine and **esp** not needed, we may should change it to **boot** only. @stikonas any further information on the **esp** or/and **boot** flag need?

**Comment by stikonas** [comment] 2018-01-09 20:08
@philmmanjaro Well, once we move to sfdisk backend, we won't have **boot** flag on GPT partitions. It will be **esp** flag.

Like I explained in some other bug report, all these flags on GPT are simply partition types. The same is true for MBR except for **boot** flag which is actually a flag, you can set it independently of the partition type on MBR.

**Comment by philmmanjaro** [comment] 2018-01-09 20:20
@stikonas: right. so we keep the code with **esp** flag as is, but check if it will be set so the user don't get nagged by the warning screen, even when he already is about to "correct" it. Is there an ETA on the **sfdisk** branch being merged?

**Comment by stikonas** [comment] 2018-01-09 20:23
@philmmanjaro sfdisk branch is actually merged in git. But

1. It is not released yet. And full functionality needs unreleased util-linux 2.32 (to unset **boot** flag on MBR). Everything else should work with util-linux 2.31.1.
2. Default backend is still libparted.

I think there should be one release where sfdisk backend is present but not default.

**Comment by philmmanjaro** [comment] 2018-01-09 20:28
@stikonas thx for the detailed info as always. I see no rush either. Sure we will test it on Manjaro.

**Comment by philmmanjaro** [comment] 2018-01-14 21:46
I added Adriaan's work on [checking for flags](https://github.com/manjaro/calamares/commit/2e07c28db0bea95530b4287209badcf8d44bdc93) to our build of **CAL v3.1.12-3**. Lets see if that works now better.

**Comment by adriaandegroot** [comment] 2018-05-14 19:59
I can no longer reproduce the original problem, so I'm closing this one. Updating the flags now gets rid of the warning message.

**Closed by adriaandegroot** 2018-05-14 19:59 UTC
Labels: Partitioning, improvement
