### ISSUE TITLE
CAL-466: Fallback of filesystem in legacy BIOS

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#627] opened 2017-02-22 20:02 UTC
Jira issue originally created by user ShalokShalom:

https://gist.github.com/anonymous/800e9c5ff045afc4d533c289ed608ede
https://gist.github.com/anonymous/d07ef176eb2e5bd998662c9def588e7b

Its not reproduceable now on any other device.

**Comment by demmm** [comment] 2017-09-07 16:12
Since not reproducible, and seems distro specific, closing.  Reopen if you can create a scenario how to reproduce.

**Closed by demmm** 2017-09-07 16:12 UTC
Labels: bug
