### ISSUE TITLE
Installation error - boost python error in packages

### ISSUE THREAD

**Issue by erikdubois** [calamares/calamares#1037] opened 2018-09-30 16:27 UTC
I can not give too much detail about the issue at hand. I post this for one of our users.

What do I know?
ArcoLinuxB 18.9.5 Xfce
Calamares 3.2.1-1
Content of iso : https://pastebin.com/xyKNhWB1

One of our users, from India working behind a proxy, has send us this error and asks for help.

![img_20180930_165144597](https://user-images.githubusercontent.com/10594806/46259814-fca09900-c4dd-11e8-9b44-d72b6f7fcaf2.jpg)

You can ask him more info on our forum.
https://arcolinuxforum.com/viewtopic.php?f=90&t=854&p=3286&sid=9fa0c449a6bbcd9b6d570a17d4b0832a#p3286

**Comment by philmmanjaro** [comment] 2018-10-01 01:39
Well, the issue seems simple. Behind a proxy and therefore the fresh system has no internet. Since you have a module relying on that the installation failed.

He  should rerun the installation from within a terminal using `sudo -E calamares -d` and paste the whole terminal output.

On the other hand find out which module tries to update the system and make the installation possible also without internet connection. Manjaro for example you can install without internet.

**Comment by philmmanjaro** [comment] 2018-10-03 17:10
Well, the terminal output could have been simply exported to a textfile. Most terminals support **select all** and **copy**. Anyway, it is OK. The error is with the module **packages** in line 253 not able to update the DB (update_db). Also it seems not to be the latest module from **master**. Also I recommend to enable `skip_if_no_internet: true` in **packages.conf**. The issue is simply not being able to properly detect internet connection and trying to ping a server which is not working via the proxy. In general I don't recommend modules needing internet connection.

**Comment by arcolinuxz** [comment] 2018-10-03 17:17
The thing is .... I have a MacBook pro laptop here - no Lan and when I install I do not go on my wifi. So no internet and it installs fine.
After reboot then I enable the wifi.
Can there be a line in there why mine passes and his not. We keep calamares changes to a minimum so follow your version?
In our packages.conf it says indeed `skip_if_no_internet: false` - still it installs on mine.

**Comment by arcolinuxz** [comment] 2018-10-03 17:48
ok will tell him to disable his internet.
Hope he has an hardware button to do that.

**Comment by philmmanjaro** [comment] 2018-10-03 18:17
Network-Manager normally supports it via UI to disconnect.

**Comment by kkofler** [comment] 2018-10-03 21:36
You may want to set a different `internetCheckUrl` in `welcome.conf`.

**Comment by kkofler** [comment] 2018-10-03 21:41
Also, NetworkManager can be configured to check connectivity, and if that does not work as expected, it will report unavailable Internet to applications such as Calamares:
https://wiki.archlinux.org/index.php/NetworkManager#Checking_connectivity
That too might not be configured optimally on your image.

**Comment by erikdubois** [comment] 2018-10-04 15:57
Thanks for the assist - it seems the user can now install ArcoLinux. 
Will change the setting in our calamares and do some more testing and roll out like that.

> Also I recommend to enable skip_if_no_internet: true in packages.conf.

Closing now

**Comment by erikdubois** [comment] 2018-10-04 16:00
Ps. the user sends his thanks to the Calamares team

**Comment by erikdubois** [comment] 2018-10-04 16:45
Can we reopen this one?

**Comment by erikdubois** [comment] 2018-10-04 16:47
I changed the code in module packages.conf to skip_if_no_internet:true
and tried to similate the fact that I do not have internet - networkmanager disconnected.
Then he still tries to do a pacman -Sy - Did I do something wrong. Or should the code be revisited.

![test](https://user-images.githubusercontent.com/10594806/46489436-ad23db00-c805-11e8-87fc-bbc09e1523b3.jpg)

**Comment by philmmanjaro** [comment] 2018-10-04 17:17
Please compare the code with the one upstream. Is it the latest?

**Comment by arcolinuxz** [comment] 2018-10-04 17:37
Made a new calamares on 3.2.2 and will advise further. 
No assistance needed at this point.

**Comment by arcolinuxz** [comment] 2018-10-04 18:33
Installing calamares 3.2.2 from this[ pkgbuild](https://github.com/arcolinux/arcolinux-pkgbuild-3party/blob/master/calamares-3.2.2/PKGBUILD) results in a message that the following modules could not be loaded **services**. I see no folder called services in my modules. I guess I am missing some package or is there an other reason? There is no significant difference between Calamares 3.2.1 from this [pgkbuild](https://github.com/arcolinux/arcolinux-pkgbuild-3party/blob/master/calamares-3.2.1/PKGBUILD). So 3.2.1 works and 3.2.2 does not....

I can not test this issue unless we solve this.

![calamares](https://user-images.githubusercontent.com/36679406/46494778-fd099e80-c813-11e8-9d34-f784145a9ab4.jpg)

**Comment by erikdubois** [comment] 2018-10-04 20:31
I went back to Calamares 3.2.1 and I discovered something odd.
I added the code `skip_if_no_internet: false` to packages.conf but this had not the effect I had expected.

I read in the last version of calamares that the whole module is skipped if there is no internet. 

I discovered that because in that package.conf is a bunch of Calamares packages I uninstall afterwards. So they never got deleted on my laptop (no internet connection) but everything installed fine on my virtualbox (with internet connection).

Skipping the whole uninstallation of packages in packages.conf can (I think) not be the intention. We can still clean up the local applications even if we do not have internet. Just a thought I would like to share.

**Comment by philmmanjaro** [comment] 2018-10-04 21:04
@arcolinuxz: Sorry, but it seems you didn't read the [release notes](https://calamares.io/calamares-3.2.2-is-out/). **services** got renamed. I even have mentioned it on my end [here](https://gitlab.manjaro.org/packages/extra/calamares-git/blob/master/PKGBUILD#L72).

**Comment by erikdubois** [comment] 2018-10-04 21:15
thanks for getting back to me - will give it another go

**Comment by kkofler** [comment] 2018-10-05 09:35
For now, you can configure 2 instances of the `packages` module (see the webview instances example for how to do it), one with `skip_if_no_internet: true` and one with `skip_if_no_internet: false`.

**Comment by adriaandegroot** [comment] 2019-01-09 12:38
Yes, multiple instances is the way to go. Then you do one which is not-skipped-when-no-internet, which uses *try_install*, and one which **is** skipped-when-no-internet.

I'm closing this one as "can be fixed in configuration downstream" .. @erikdubois , if you find that the documentation -- on the wiki or in the config example -- please file a PR with fixes (or ask for specific documentation things in an issue and I can sit down to it).

**Closed by adriaandegroot** 2019-01-09 12:38 UTC

**Comment by marine1988** [comment] 2019-05-22 22:13
After antergos news I search and all people say that Arco is the most close distribution and by the troubles I'm having with the installer I think they right
