### ISSUE TITLE
pages bar squished when maximized 

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1085] opened 2019-02-12 15:50 UTC
When maximizing the window the list of pages on the left hand side gets squished with inconsistent spacing on the left and the right side of the text, which looks super weird.

screenshot. note the amount of space between the red lines and the actual "border". I think this would look heaps better if the spacing was the same on either side of the text, and as I recall that is how it used to be?

![screenshot_20190212_164646](https://user-images.githubusercontent.com/809987/52648105-30f18080-2ee6-11e9-8752-a51a7c45a7a9.png)

**Comment by adriaandegroot** [comment] 2019-02-12 16:21
Can't reproduce with default branding. (Either starting as fullscreen, hitting maximize, or enlarging the window). Your *maximizing* looks like *enlarging* to me, though .. it's not maximized by the window decoration, or by screen size.

**Comment by apachelogger** [comment] 2019-02-12 16:36
Huh!

As it turns out: if your screen is too small and you open cala it will squish like shown in the screenshot. I think this is basically below 1024 width, so super edge case. I don't think this is worth pursuing.

**Comment by adriaandegroot** [comment] 2019-02-14 23:15
Yes, below a certain size the sidebar gets squashed away. This might be solved by calculating a new font size for the sidebar, but it's a lot of work for an edge case. Closing this as "not worth it for now".

**Closed by adriaandegroot** 2019-02-14 23:15 UTC
