### ISSUE TITLE
no timezones to  dropdown

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1476] opened 2020-08-04 10:17 UTC
**Describe the bug**
timezone dropdown has no actual timezones. I cannot choose America as region and North_Dakota/Beulah as tz :((

**To Reproduce**
1. https://files.kde.org/neon/images/focal-preview/unstable/
2. start calamares
3. click next
4. no timezones available

**Expected behavior**
there should be tzs

**Screenshots and Logs**
(not too useful it appears:)[cala.log](https://github.com/calamares/calamares/files/5021508/cala.log)
![Screenshot_20200804_121256](https://user-images.githubusercontent.com/809987/89282782-54653980-d64c-11ea-8c7d-eeb44a7ac68f.png)

**Comment by demmm** [comment] 2020-08-04 10:41
Duplicate of https://github.com/calamares/calamares/issues/1469

**Closed** 2020-08-07 06:36 UTC
Labels: M duplicate
