### ISSUE TITLE
CAL-376: Calamares crashes on libcalamares_viewmodule_partition.so

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#528] opened 2016-06-14 16:11 UTC
Jira issue originally created by user TPG:

Teo, Calamares executed in X11 environment crashes:

13:16:31 [1]: enoughStorage, enoughRam, hasPower, hasInternet, isRoot:  true true true true true 
Backtrace has 13 calls on stack:
  13: /usr/lib64/libparted.so.2(ped_assert<ins>0x32) [0x7ff049c68226]
  12: /usr/lib64/libparted.so.2(ped*device_begin_external*access</ins>0) [0x7ff049c68653]
  11: /usr/lib64/libparted.so.2(ped*disk*new<ins>0x19) [0x7ff049c6a909]
  10: /usr/lib64/qt5/plugins/libpmlibpartedbackendplugin.so(</ins>0x7e5b) [0x7ff0496d4e5b]
  9: /usr/lib64/qt5/plugins/libpmlibpartedbackendplugin.so(<ins>0x653a) [0x7ff0496d353a]
  8: /usr/lib64/calamares/modules/partition/libcalamares*viewmodule_partition.so(*ZN19PartitionCoreModule4initEv</ins>0x44) [0x7ff042c03544]
  7: /usr/lib64/calamares/modules/partition/libcalamares*viewmodule_partition.so(*ZN19PartitionCoreModuleC2EP7QObject<ins>0xe1) [0x7ff042c03251]
  6: /usr/lib64/calamares/modules/partition/libcalamares*viewmodule_partition.so(*ZN17PartitionViewStep23initPartitionCoreModuleEv</ins>0x1f) [0x7ff042c338bf]
  5: /usr/lib64/calamares/modules/partition/libcalamares*viewmodule*partition.so(<ins>0x8417b) [0x7ff042c4f17b]
  4: /usr/lib64/libQt5Core.so.5(</ins>0xa9d2c) [0x7ff051629d2c]
  3: /usr/lib64/libQt5Core.so.5(<ins>0xabe0c) [0x7ff05162be0c]
  2: /lib64/libpthread.so.0(</ins>0x700d) [0x7ff05066400d]
  1: /lib64/libc.so.6(clone+0x6d) [0x7ff0511a6b4d]

More info on external bug report.

**Comment by AeroStun** [comment] 2017-07-06 20:21
Info add: this bug is still present (on the last Netrunner installer) on specific platforms. I'll have to investigate this, but today I was trying to install Netrunner on an ASUS ROG for a friend, and this error came up. Back home I fire up VMWare, and I got no problem intalling it on a VM.
I'll keep you up on the results of the research

**Comment by adriaandegroot** [comment] 2017-09-07 10:08
This was reported again as #782 , and is now fixed with Calamares 3.1.4 -- at least, the crashes that were happening there, which I could reproduce. Since the code has changed a great deal since the 2-series, the backtraces in this issue no longer apply.

**Closed by adriaandegroot** 2017-09-07 10:08 UTC
Labels: bug
