### ISSUE TITLE
Problem after installation

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [calamares/calamares#916] opened 2018-03-08 22:12 UTC
I had a strange problem during the installation of Manjaro Cinnamon v (17.1.6)
I chose to install Manjaro Cinnamon at sda5 as in the picture and I chose the boot loader to be in the same location, but after the installation the installer formatted sda1 (Windows partition) and sda10 (Manjaro KDE partation) which I didn't chose to be formatted!
![screenshot from 2018-03-08 14-14-17](https://user-images.githubusercontent.com/29783425/37179343-fcb8250e-232d-11e8-83d0-a6c562d4ca9a.png)

**Comment by adriaandegroot** [comment] 2018-03-09 09:45
You should probably take this up with Manjaro first. That said, no, Calamares should not format partitions you have not told it to format. This is manual partitioning, though .. are you sure you didn't leave a "format partition" on in one of the other partitions? Is the problem reproducible? (er .. which in this context means "can you destroy your computer *again*?" I guess)

**Comment by ahmed-elsayed2017** [comment] 2018-03-13 18:55
I posted this problem in Manjaro forum first, and someone told me to post my problem here.

I didn't try to install Manjaro Cinnamon again, because I was afraid for this to happen again.

I installed Manjaro KDE with no problem at all with the same procedures I've done before.

**Comment by philmmanjaro** [comment] 2018-03-13 19:29
@ahmed-elsayed2017: our bugtracker for **CAL** is [here](https://github.com/manjaro/calamares/issues). Since we use the same framework and only the DE is differnt, I see no issue with **CAL** at all. We always recommend to save your personal data first, as always thinks may happen. Since the KDE ISO worked, it is fine. Why the Cinnamon ISO failed on your end, I currently don't know. Can you point me to the forum post of yours, so I may also check up on it?

**Comment by adriaandegroot** [comment] 2018-03-16 10:50
Thanks to @abucodonosor on IRC -- looks like the bootloader (GRUB) is going to be installed on /, which is sda5, which in turn is a partition in the *extended* partition area. GRUB doesn't support that, does it?

**Comment by kkofler** [comment] 2018-03-16 12:05
As far as I know, it does. But of course GRUB won't boot from a partition on its own, so you need to have a working bootloader in the MBR and that bootloader has to support chainloading from extended partitions.

**Comment by abucodonosor** [comment] 2018-03-16 13:35
@kkofler 

It does install with force flag but won't boot .. at least not on that setup.. 
grub-install will give you a nice warning about that stuff eg:

```
grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..

```
Also even it boots by luck on any chages to 'whatever is the bootloader in MBR'
UUID= calcualtion will break..

**Comment by adriaandegroot** [comment] 2018-05-10 11:48
Closing as downstream-bug, feedback-timeout.

**Closed by adriaandegroot** 2018-05-10 11:48 UTC
Labels: Downstream bug
