### ISSUE TITLE
Rootless Calamares, native Wayland support without Xwayland

### ISSUE THREAD

**Issue by adrelanos** [calamares/calamares#2268] opened 2024-01-03 10:48 UTC
If calamares is started without root rights, it shows:

> the installer is not running with administrative rights

Quote Jan 4, 2018 https://calamares.io/calamares-3.2-plan-revised/

> Rootless Calamares (e.g. not running as root) has not been worked on at all; at the same time, KPMCore has done a great deal of work to be able to run rootless, so progress has been made regardless. Accessibility has been addressed through a patch to Qt, which is unfortunately stalled in Qt’s bug tracker. So rootlessness for accessibility purposes is still desired. I don’t want to make any promises for rootless functionality before 3.2.0.

Quote Aug 25, 2020 https://calamares.io/calamares-summer/

> Tidying up partitioning remains a big issue, as does rootless operation (which is also necessary for better accessibility).

Also also a short mention here: https://github.com/calamares/calamares/issues/2024#issuecomment-1193007820

Other than that, I haven't found any issue for it.

I suppose Rootless Calamares hasn't been completed yet. Hope you're OK leaving this ticket open for reference.

I also presume that this is the precondition for Calamares native Wayland support (without Xwayland).

**Comment by dalto8** [comment] 2024-01-03 12:51
> Other than that, I haven't found any issue for it.

Yeah, it is basically tracked here: https://github.com/calamares/calamares/issues/1294

This is, admittedly, a non-obvious place for it.

**Comment by stikonas** [comment] 2024-03-23 00:25
Wayland and rootless are not related. There is nothing in wayland stopping root'ed clients, e.g. try running
`sudo QT_QPA_PLATFORM=wayland XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR konsole` and it will start as wayland client.

**Comment by dalto8** [comment] 2024-04-08 23:45
Closing as a duplicate of #1294

**Closed by dalto8** 2024-04-08 23:45 UTC

**Comment by kkofler** [comment] 2024-04-09 07:15
> Wayland and rootless are not related. There is nothing in wayland stopping root'ed clients

Some compositors disallowed it initially. Maybe some still do, not sure. Most accept clients running under root now.
