### ISSUE TITLE
File system selection for replace and install alongside

### ISSUE THREAD

**Issue by CookieSource** [calamares/calamares#2019] opened 2022-07-10 09:05 UTC
**Is your feature request related to a problem? Please describe.**
In the current Calamares installer file system can be an optionally provided if you clear the disk however this option of file system selection is not available in replace a partition or install alongside

**Describe the solution you'd like**
Just like the erase disk option the ability to select a file system
**Describe alternatives you've considered**
Manual partitioning :)
**Additional context**
![image](https://user-images.githubusercontent.com/36531905/178138368-ee2242b9-04df-41f0-be04-8bc58aa1d9c6.png)
![image](https://user-images.githubusercontent.com/36531905/178138373-48a29797-4369-46e9-9736-5a6b45ad9e1d.png)

**Comment by demmm** [comment] 2022-07-10 09:59
Duplicate of https://github.com/calamares/calamares/issues/1911

**Closed by demmm** 2022-07-10 09:59 UTC
Labels: M duplicate
