### ISSUE TITLE
Use btrfs subvolumes as partitions are used.

### ISSUE THREAD

**Issue by lawmanuk** [calamares/calamares#807] opened 2017-09-18 18:00 UTC
#### Submission type

  - [ X] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> …
3.1.4 used with Manjaro 17.04 XFCE.  Not sure which sub version of 3.1.4 as doesn't state in about box.

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 
Standard MSDOS Partition table with different partitions for linux / windows.

> …

#### What do you expect to have happen when Calamares installs?

Want to be able install OS / Home etc. into specific BTRFS subvolumes, much as we can currently install into partitions.

Eg.  Currently Linux Mint installs into following subvolumes when installing on BTRFS system.
1. Root = @ subvolume
2. Home = @home subvolume.

When trying to install Manjaro via Calamares on same BTRFS partition, manjaro tries to install on the exact same named subvolumes, so wouldn't work.

Instead, please allow custom subvolume names to be created.
eg. 
1. New Root = @rootmanjaro
2. New Home = @homemanjaro

Then booting Manjaro would boot @rootmanjaro, whereas booting Mint from same btrfs volume would boot @ .

Would also be helpful if you allowed adding additional subvolumes to be mounted / created.

eg. 
1.  Create and mount on boot data subvolume = @data subvolume
2.  Mount on boot other subvolumes = mint @ subvolume
3.  Also ability to rename subvolumes if required.

> …

#### Describe the issue you encountered

> …

#### Steps to reproduce the problem

> …

#### Include the installation.log:

> …

**Comment by abucodonosor** [comment] 2017-09-18 18:52
Kind dupe of  #586..

**Comment by lawmanuk** [comment] 2017-09-18 18:58
similar to #586.. but requesting for some additional flexibility in setting up.

**Comment by abucodonosor** [comment] 2017-09-18 19:44
@lawmanuk 

Yes but both would need same changes in GUI.. I let both open for now

**Comment by adriaandegroot** [comment] 2022-07-02 15:33
Firly sure the current btrfs subvolumes options can support this from the distro-side. If not, would be best to re-file with a PR attached.

**Closed by adriaandegroot** 2022-07-02 15:33 UTC
Labels: feature: improvement, feature: new
