### ISSUE TITLE
Autologin in GDM not working

### ISSUE THREAD

**Issue by codesardine** [calamares/calamares#1919] opened 2022-04-12 08:02 UTC
Selecting autologin box in the installer is not working for GDM

**Comment by adriaandegroot** [comment] 2022-04-12 11:57
Please take a look at https://calamares.io/issues/ on how to effectively report issues. An ISO link in particular makes all the difference here. What is the full path of your GDM executable? What is the full path of the GDM configuration file that it reads?

**Comment by Chrysostomus** [comment] 2022-04-13 06:47
I can't reproduce the issue on the latest gnome developement isos. For me gdm autologin was enabled without issues. Package version 3.2.53-2, built against commit b895fae85c331c0203b3f02e7c0c2ce663e2dd24.

**Comment by adriaandegroot** [comment] 2022-04-13 12:41
Assuming Manjaro can figure it out internally (or re-open, give me a shout in chat then), closing.

**Closed by adriaandegroot** 2022-04-13 12:41 UTC
