### ISSUE TITLE
welcome module GEOIP url service unavailable 

### ISSUE THREAD

**Issue by killajoe** [calamares/calamares#1305] opened 2020-01-21 13:31 UTC
EndeavourOS calamares:
[https://github.com/endeavouros-team/Calamares_current](https://github.com/endeavouros-team/Calamares_current)

**Describe the bug**
GOEIP auto check is not working anymore

**To Reproduce**
1. enable GEOIP checking to get locale set up automatic in welcome module
2. https://geoip.kde.org/v1/ubiquity url is not available and language/timezone will not be set automatic on install (internet check is positive)

**Expected behavior**
auto setup of locale and timezone on install process

**Screenshots and Logs**
open 
[https://geoip.kde.org/v1/ubiquity](https://geoip.kde.org/v1/ubiquity)
will show:
Service Unavailable
This is permanent now, as it was not working sometimes before also, server seems to be down.
```
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.4.18 (Ubuntu) Server at geoip.kde.org Port 443
```

**Additional context**
try to change url to [https://freegeoip.app/xml/](https://freegeoip.app/xml/) was working but they seem to have limitations and are not free to use.

**Comment by monetaryabyss** [comment] 2020-01-21 13:46
I think the intention of this is that the choice of the geoip service is left up to the deployer and that the example provided in the module is just an example.
You could try to change to https://ipapi.co/ it too has limitations however there is a free tier. They provide a json feed at https://ipapi.co/json

**Comment by Portergos** [comment] 2020-01-24 00:42
Ok, it's possible to use https://ipapi.co/ for both json and xml, however timezone is not properly selected maybe because calamares is set to use "time_zone" or something?
Can you tell me if can i change calamares to accept "timezone" or "TimeZone"?
Thanks for the help!
Fernando.

**Comment by monetaryabyss** [comment] 2020-01-24 01:16
In Lubuntu this is our [welcome module](https://phab.lubuntu.me/source/calamares-settings-ubuntu/browse/master/lubuntu/modules/welcome.conf$25). As you see we are using the `country` code. In the [locale module](https://phab.lubuntu.me/source/calamares-settings-ubuntu/browse/master/lubuntu/modules/locale.conf$8) we use `timezone`. 
Hope that helps a bit.
Dan

**Comment by adriaandegroot** [comment] 2020-01-24 11:24
There's a couple of angles to this:

 - the *welcome* module uses GeoIP to find a country (and so, automatically select a language for the interface)
 - the *locale* module uses GeoIP to find a timezone and location (for localization)

Both are configured separately, and, as @monetaryabyss points out, for the *welcome* module you need to set it to get the country part of the data, while in the *locale* module you need to set it to something else.

But that's not the problem this issue is originally about: it's that the KDE GeoIP service is not responding, i.e.
```
adridg@localhost:~/src/calamares> curl https://geoip.kde.org/v1/ubiquity
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at geoip.kde.org Port 443</address>
</body></html>
```
That's not actually a Calamares issue: it's an external service (provided by the KDE community) and problems with it should be reported there. If the service were providing data in a new format, then it'd be a Calamares issue (to fix parsing or whatever). In any case, I talked to @apachelogger (who set that stuff up on the KDE side) and it turns out that the GeoIP provider behind the KDE service has changed **its** terms of service, and so the KDE bits no longer can connect to it. The problem is being looked into upstream -- er.. sidestream maybe? -- and I'm going to close this issue as "not under Calamares's control".

(Using ipapi.co is fine, @Portergos , you need to set it up with a suitable selector like @monetaryabyss says; thanks you all for helping each other)

**Closed by adriaandegroot** 2020-01-24 11:24 UTC

**Comment by Portergos** [comment] 2020-01-24 16:36
Agreed, this is not a calamares bug.
Anyway you already helped us and i'll check locale module to set other config.
Thank you very much for helping!

**Comment by apachelogger** [comment] 2020-01-27 11:06
quick FYI: the geoip.kde service is up and running again
