### ISSUE TITLE
Cant load libraries

### ISSUE THREAD

**Issue by krolmiki2011** [calamares/calamares#2417] opened 2024-12-23 10:09 UTC
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
A clear and concise description of what the bug is. Please include 32/64 bit machine details, EFI/BIOS details, and disk setup.

**To Reproduce**

**Expected behavior**

Cant load libraries for example we need python 3.12 but i installed 3.13

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Calamares has an installation log (usually `~/.cache/calamares/session.log`), please check it for confidential information and attach it if possible.

**Additional context**

**Comment by demmm** [comment] 2024-12-23 11:55
The issue template is there for a reason....
Make sure to provide needed info, issue report as is is useless and will be closed shortly (unless needed info is provided).
Is this a report from an end user?  Then go to your distribution first:
https://calamares.io/issues/#end-users

If this is a report from a distro developer, rebuilding Calamares when you update python is up to you and not a bug.

**Comment by krolmiki2011** [comment] 2024-12-23 12:09
For first calamares uses old python libraries when is a python 1.13 plus i have a screenshoot

**Comment by demmm** [comment] 2024-12-23 12:14
Closing, as this is not a Calamares issue.
As noted, rebuilds on newer libraries is up to you, or if you are an end user, report to your distro that they need to rebuild.

**Closed by demmm** 2024-12-23 12:14 UTC

**Comment by krolmiki2011** [comment] 2024-12-23 12:18
I Creating my own distro

**Comment by demmm** [comment] 2024-12-23 12:19
Then make sure to rebuild Calamares on proper Python version.

**Comment by krolmiki2011** [comment] 2024-12-23 12:23
But i use Arch base and in arch python version = 3.13.1 and boost-libs=1.86.0 so why are You update libcalamares to support new versions?

**Comment by demmm** [comment] 2024-12-23 12:44
This is not a help channel:
https://calamares.io/issues/#developers-of-distributions
If you don't understand how distro library updates require rebuilds of consumers of said libraries, go to the Clamares Matrix channel for more questions.
Closing this issue for comments now.
