### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by ChameleonScales** [calamares/calamares#695] opened 2017-03-14 16:31 UTC
When I start Calamares installer, it crashes right after opening. The weirdest thing is that I succesfully installed manjaro from the exact same live USB on the same computer yesterday. I hope I didn't do something bad to my computer.
```
/usr/bin/calamares_polkit %f
qt5ct: using qt5ct plugin
15:19:35 [1]: Calamares version: 3.1.0 
Translation: Calamares: Using system locale: "en_US"
Translation: Qt: Using default locale, system locale one not found: "en_US"
15:19:35 [1]: Default font ===== 
Pixel size:    -1 
Point size:    10 
Point sizeF:   10 
Font family:   "Cantarell" 
Metric height: 17 
15:19:35 [1]: Font height: 17 
15:19:35 [1]: Available languages: ("ar", "ast", "bg", "ca", "cs_CZ", "da", "de", "el", "en", "en_GB", "es_MX", "es", "eu", "fr", "hr", "hu", "id", "is", "it_IT", "ja", "lt", "nl", "pl", "pt_BR", "pt_PT", "ro", "ru", "sk", "sv", "th", "tr_TR", "zh_CN", "zh_TW") 
15:19:35 [1]: CalamaresApplication thread: 0x18ead00 
15:19:35 [1]: Using log file: "/root/.cache/Calamares/Calamares/Calamares.log" 
15:19:35 [1]: Using Calamares settings file at "/etc/calamares/settings.conf" 
15:19:35 [1]: Using Calamares branding file at "/usr/share/calamares/branding/manjaro/branding.desc" 
15:19:35 [1]: WARNING: the selected branding component does not ship translations. 
15:19:35 [1]: Loaded branding component "manjaro" 
15:19:35 [1]: STARTUP: initQmlPath, initSettings, initBranding done 
15:19:35 [1]: STARTUP: initModuleManager: module init started 
15:19:35 [1]: STARTUP: initModuleManager: all modules init done 
15:19:35 [1]: STARTUP: initJobQueue done 
15:19:35 [1]: Proposed window size: 1020 612 
15:19:35 [1]: STARTUP: CalamaresWindow created; loadModules started 
15:19:35 [1]: Initial locale  "en_US" 
15:19:35 [1]: ViewModule "welcome@welcome" loading complete. 
15:19:35 [1]: WARNING: cannot acquire a list of available locales. The locale and localecfg modules will be broken as long as this system does not provide  * a /usr/share/i18n/SUPPORTED file 	OR  * a well-formed /etc/locale.gen 	OR  * a complete pre-compiled locale-gen database which allows complete locale -a output. 
15:19:35 [1]: ViewModule "locale@locale" loading complete. 
15:19:35 [1]: ViewModule "keyboard@keyboard" loading complete. 
15:19:35 [1]: ViewModule "partition@partition" loading complete. 
15:19:35 [1]: ViewModule "users@users" loading complete. 
15:19:35 [1]: ViewModule "summary@summary" loading complete. 
15:19:35 [1]: Module "partition@partition" already loaded. 
15:19:35 [1]: QML import paths: ("/usr/share/calamares/qml", "/usr/bin", "qrc:/qt-project.org/imports", "/usr/lib/qt/qml") 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: Module "locale@locale" already loaded. 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: Module "keyboard@keyboard" already loaded. 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: Module "users@users" already loaded. 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [0]: void Calamares::Module::loadConfigurationFile(const QString&) bad module configuration format "/usr/share/calamares/modules/umount.conf" 
15:19:35 [1]: LAST VS IS EVS! 
15:19:35 [1]: ViewModule "finished@finished" loading complete. 
15:19:35 [1]: STARTUP: loadModules for all modules done 
15:19:36 [1]: STARTUP: Window now visible and ProgressTreeView populated 
15:19:36 [1]: Need at least storage bytes: 8482560409 
15:19:36 [1]: Need at least ram bytes: 1073741824 
15:19:36 [1]: enoughStorage, enoughRam, hasPower, hasInternet, isRoot:  true true true true true 
No layout variant specified on the command line
Trailing -variant option ignored
15:19:36 [1]: xkbmap selection changed to:  "us" - "" 
terminate called after throwing an instance of 'YAML::ParserException'
  what():  yaml-cpp: error at line 18, column 21: illegal map value
/usr/bin/calamares_polkit: line 6:  1583 Aborted                 (core dumped) pkexec --disable-internal-agent "/usr/bin/calamares" "$@"
```

I also have this error when starting the live USB, dunno if it's related :

![](http://i.imgur.com/kYRSMsR.jpg)

**Comment by shadeslayer** [comment] 2017-03-14 16:33
```
terminate called after throwing an instance of 'YAML::ParserException'
```
Your calamares config is not valid YAML

**Comment by oberon2007** [comment] 2017-03-14 16:38
Which ISO did you use for this?

**Comment by philmmanjaro** [comment] 2017-03-14 17:57
Seems we have to check our config files created by **manjaro-tools**.

**Comment by ChameleonScales** [comment] 2017-03-14 18:34
I used manjaro-xfce-17.0-stable-x86_64.iso

**Comment by philmmanjaro** [comment] 2017-03-14 18:45
@ChameleonScales: which locale was used?

**Comment by ChameleonScales** [comment] 2017-03-14 22:15
Not sure what you mean by locale. I downloaded the iso via [this link](https://sourceforge.net/projects/manjarolinux/?source=typ_redirect) (given in https://manjaro.org/get-manjaro/ in "Direct download (64-bit)") and burnt it with a simple `dd` command.

**Comment by philmmanjaro** [comment] 2017-03-15 06:56
With locale I mean, which language was chosen on boot up. English?

**Comment by shadeslayer** [comment] 2017-03-15 14:36
From my very quick testing in KVM with that ISO, calamares seems to start just fine here.

**Comment by ChameleonScales** [comment] 2017-03-15 14:54
Yes English

**Comment by ChameleonScales** [comment] 2017-03-15 14:56
I fear this issue is very particular since as I said, it worked one day before on the same computer.

**Comment by shadeslayer** [comment] 2017-03-17 16:37
```
15:19:35 [0]: void Calamares::Module::loadConfigurationFile(const QString&) bad module configuration format "/usr/share/calamares/modules/umount.conf" 
```

Could you make sure that file is valid YAML?

**Comment by ChameleonScales** [comment] 2017-03-22 16:02
I'm currently keeping my installation and will get back to this issue in some days.

**Comment by ChameleonScales** [comment] 2017-03-27 18:58
Well, I just re-tried and for a strange reason I got no error on boot-up and Calamares worked fine. I really don't know why since I used the same live USB on the same computer.
But good for me I guess !

**Comment by Madh93** [comment] 2017-04-05 18:00
**ISO:** manjaro-xfce-17.0-stable-x86_64.iso
**Date:** 2017-04-03

Default configuration. Same calamares output.

Locale Output:

    LANG=en_US.UTF-8
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=

YAML file (`/usr/share/calamares/modules/umount.conf`):
    
    ---
    #scrLog:       "/path/to/installation.log"
    #destLog:      "/var/log/installation.log"
    # example when using the Calamares created log:
    #srcLog:      "/root/.cache/Calamares/Calamares/Calamares.log"
    #destLog:     "/var/log/Calamares.log"
    # example when creating with a sudo calamares -d log:
    #srcLog:      "/home/live/installation.log"
    #destLog:     "/var/log/installation.log"

**Comment by shadeslayer** [comment] 2017-05-07 10:31
Seems like this is a duplicate of #686

**Comment by Gibbz** [comment] 2017-05-07 13:14
yeah looks like it!
Im getting this error too! But a different line number...
What can i do to help?

https://pastebin.com/cHbP5q2y

**Comment by philmmanjaro** [comment] 2017-05-07 19:31
`/usr/share/calamares/modules/umount.conf` is the stock file without modification. This issue is really weird ...

**Comment by philmmanjaro** [comment] 2017-05-07 19:42
What happens when the file `/etc/calamares/modules/umount.conf` would look like this?

```
---
srcLog:      "/root/.cache/Calamares/Calamares/Calamares.log"
destLog:    "/var/log/Calamares.log"
```

**Comment by Gibbz** [comment] 2017-05-08 01:27
(01:24:13 [0]: void Calamares::Module::loadConfigurationFile(const QString&) bad module configuration format "/usr/share/calamares/modules/umount.conf" )
here is my umount.conf:

> ---
> #scrLog:       "/path/to/installation.log"
> #destLog:      "/var/log/installation.log"
> # example when using the Calamares created log:
> #srcLog:      "/root/.cache/Calamares/Calamares/Calamares.log"
> #destLog:     "/var/log/Calamares.log"
> # example when creating with a sudo calamares -d log:
> #srcLog:      "/home/live/installation.log"
> #destLog:     "/var/log/installation.log"
>

**Comment by Gibbz** [comment] 2017-05-08 02:00
ok i dont belive the issue to be the umount.conf, as on a machine that installs i have exactly the same umount, and the same umount error in the log!

Heres a log of a working one:
https://pastebin.com/TBs96uR4

**Comment by Gibbz** [comment] 2017-05-08 02:24
ok ive managed to get around the crash by disconnecting the network!
Either physically, or through the network manager. Then launch the installer and it works!

I guess something in the network check if failing...

**Comment by philmmanjaro** [comment] 2017-06-02 10:41
Duplicate of https://github.com/calamares/calamares/issues/686

**Comment by adriaandegroot** [comment] 2017-06-02 10:41
I'm going to close this as a dup of #686 and the continuing discussion there.

**Closed by adriaandegroot** 2017-06-02 10:41 UTC
Labels: bug
