### ISSUE TITLE
Calamares does not detect internal drives when it is written on that drive

### ISSUE THREAD

**Issue by mdhishamsayed** [calamares/calamares#2157] opened 2023-06-15 10:21 UTC
**Describe the bug**
Lets consider a OS image, for example lets take Liya or Garuda or etc.. Whenever we write the image to one partition of hard-disk drive, it does not recognise other partitions, for example, lets take a ISO image of Liya or garuda or any other os which uses calamares, then we write the iso image to one partition of the drive (internal) and then boot from it and then start calamares, it says that there are no drives to install on, but there are partitions on that drive.
microsoft windows installer does not have this issue as it recognises all the partitions (no comparison here)
**To Reproduce**
1. Download a Arch-Based or any ISO which has calamares
3. Write that image to one partition of the internal drive by doing "sudo dd if=<iso image> of=/dev/sda<x partition number> conv=sync status=progress"
4. then add menuentry to grub or somehow boot from that partition
5. then launch calamares
6. See error

**Expected behavior**
Calamares should recognise the hard drive and shall install on it.
Pop_OS! installer has implemented it (system76 computers come with a recovery partition)

**Screenshots and Logs**
Nothing.

**Additional context**
Can be reproduced in calamares 62 and 61 branches (3.3.0 branch not tested)
related to #2088

**Comment by killajoe** [comment] 2023-06-15 11:36
Calamares is an installer application.. ISO files are not created with Calamares and distribution using different framework for the ISO creation.

This is nothing calamares is used for.

**Comment by kkofler** [comment] 2023-06-15 11:49
That is not the issue. The issue is that Calamares filters out any and all disks which contain any kind of ISO anywhere from the list of available installation targets. This was designed to avoid attempting to install on a USB stick used for installation, overwriting the installation media while it is still needed, but the check is just overreaching and broken. This is a known issue. There are already several reports of it, see #545, #2088, #2157. See also the related #913.

Closing as a **duplicate**.

**Closed** 2023-06-15 13:03 UTC
