### ISSUE TITLE
CAL-447: Swap not activated and has no entry in /etc/fstab

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#606] opened 2017-01-19 13:34 UTC
Jira issue originally created by user pagnotta:

When using 'Erase Disk' option to automatically partition the disk, a swap file is created on the system during install. But when running the installed system, the swap partition is not activated and has not entry in /etc/fstab.

It can easily be replicated by using one of the mentioned Distribution releases and installing it. Then

swapon -show

would return nothing,

free -h

shows a 0B swap partition.

There is a discussion on the topic in the Manjaro forums: 

https://forum.manjaro.org/t/manjaro-xfce-16-10-3-fresh-installation-but-swap-partition-not-activated-automatically/15159

A simple workaround is to manually enter the swap partition into the /etc/fstab after installation.

**Comment by Pointedstick** [comment] 2017-04-21 22:55
Confirmed. One consequence of this is that hibernation is not enabled at install-time.

**Comment by adriaandegroot** [comment] 2017-09-04 12:47
Test with Manjaro 17.04 KDE:

 - non-encrypted system, install to disk /dev/sda (the only one in the system), choose entire disk. System has UUID= lines in fstab for both / and swap. Swap is enabled, and swapon -show lists /dev/sda2 as in use.
 - encrypted system, install to desk /dev/sda, entire disk .. system has UUID= lines in fstab for both / and swap, but those are the device UUIDs, not the inner luks UUIDs. Swap is not enabled, swapon -show lists no swap.

Since it's the encrypted case that is causing problems, i'm closing this as a duplicate of #730

**Closed by adriaandegroot** 2017-09-04 12:47 UTC
Labels: bug

**Comment by Pointedstick** [comment] 2017-09-04 13:31
Did you test the unencrypted LVM case?

**Comment by adriaandegroot** [comment] 2017-09-04 14:01
@Pointedstick This issue doesn't mention LVM. If anyone wants LVM stuff looked at, there is going to have to be an issue filed, or one of the existing LVM issues commented, with "do this, this, and this" (e.g. in #427) to actually do an LVM setup, because I can't test otherwise.

**Comment by Pointedstick** [comment] 2017-09-04 14:18
Oh whoops, forgot there was already an issue for that.
