### ISSUE TITLE
Add more language option to language selector in welcome page

### ISSUE THREAD

**Issue by linlinger** [calamares/calamares#1741] opened 2021-07-29 11:18 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I start Calamares and  select languages.As you know there are simplified Chinese and Traditional Chinese. In China there are three regions speak and using traditional Chinese. They are Hong Kong Macao and Taiwan.  To be more specifically. 
**Describe the solution you'd like**
The language selector should add two language options. One is Traditional Chinese (Hong Kong) , the other is  Traditional Chinese (Macao).

**Describe alternatives you've considered**
Also you could make it simple and less confusing . Change  to Simplified Chinese and Tradition Chinese. 

**Additional context**
No for now.

**Comment by adriaandegroot** [comment] 2021-07-30 22:53
zh_HK has been added, since that's now available in Transifex.

**Comment by adriaandegroot** [comment] 2021-09-06 14:10
Closing this, as "zh_HK has been added" and there doesn't seem to be an effort to add a Macao variant in Transifex.

Looking at the language selector more closely, I'm not sure I understand the original problem, either: there's two listings (three now, since HK is there) for Chinese: Chinese (China) which is represented in Chinese as "simplified Chinese (China)" "简体中文（中国)" and Chinese (Taiwan) which is represented as "traditional Chinese (Taiwan)" "繁體中文（中國)" so the choice simplified / traditional is already there.

Unless the issue is that "traditional Chinese" doesn't necessarily mean "Taiwan", and that the underlying idea is "there should be simplified and traditional, without naming countries/places, in the language drop-down." If **that** is the case (I could stand behind that, although then I'd drop zh_HK again unless there are real language differences between zh_HK and zh_TW) that is easy enough to do in the `specialCase()` function in `locale/Translation.cpp` (`locale/Label.cpp` before 3.2.43).

**Closed by adriaandegroot** 2021-09-06 14:10 UTC

**Comment by linlinger** [comment] 2021-09-06 15:00
There should be simplified and traditional, without naming countries/places, in the language drop-down. That's what I mean.
zh_HK and zh_TW is almost same but some minor differences in grammar or describe a certain thing.
