### ISSUE TITLE
Calamares Manjaro crash

### ISSUE THREAD

**Issue by supagu** [calamares/calamares#728] opened 2017-05-06 13:00 UTC
On the manjaro installer I get the following error:

ran the command from the live cd/usb: sudo -E calamares -d

End of the terminal displays: 07:37:36 [0]: void Calamares::Module::loadConfigurationFile(const QString&) bad module configuration format "/usr/share/calamares/modules/umount.conf" 07:37:36 [1]: LAST VS IS EVS! 07:37:36 [1]: ViewModule "finished@finished" loading complete. 07:37:36 [1]: STARTUP: loadModules for all modules done 07:37:37 [1]: STARTUP: Window now visible and ProgressTreeView populated 07:37:37 [1]: Need at least storage bytes: 8482560409 07:37:37 [1]: Need at least ram bytes: 1073741824 07:37:37 [1]: A battery exists, checking for mains power. 07:37:37 [1]: enoughStorage, enoughRam, hasPower, hasInternet, isRoot: true true true true true 07:37:37 [8]: getting bad sectors failed for "/dev/sda" : No such file or directory No layout variant specified on the command line Trailing -variant option ignored 07:37:37 [1]: xkbmap selection changed to: "us" - "" terminate called after throwing an instance of 'YAML::ParserException' what(): yaml-cpp: error at line 20, column 80: illegal map value Aborted

Any idea what this is, or how to fix it?

**Comment by shadeslayer** [comment] 2017-05-07 10:31
Duplicate of #686

**Closed by shadeslayer** 2017-05-07 10:31 UTC
